# Multi-modal Model V8-Team - Team Only (No Position Zone)

이 노트북은 Tuned H96에 team_id만 추가한 버전입니다 (position_zone 제거).

## 주요 변경 사항 (V8-Team)

1. **Team ID Embedding** (dim=8):
   - 팀별 플레이 스타일 학습
2. **Position Zone 제거**:
   - start 좌표에서 자동 계산하는 zone은 노이즈로 판단되어 제거
   - 팀 정보만 사용하여 더 깔끔한 학습
3. **Preprocessor**: preprocessing_multimodal_team.py
4. **Model**: MultiModalNetV8Team

## 기대 효과
- Tuned H96: 13.6
- V8-Zone (with position): 13.6
- **V8-Team 목표: 13.0~13.5** (노이즈 제거로 개선 기대)

In [1]:
import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence, pad_sequence
from sklearn.model_selection import GroupKFold
import cv2  # OpenCV Import
from tqdm import tqdm
import joblib

from src.models_multimodal_v8_team import MultiModalNetV8Team, EuclideanLoss, MaskedSeqEuclideanLoss

# [v7 Fix] Use Fixed Preprocessor (No Rounding)
from src.preprocessing_multimodal_team import FootballPreprocessorMultimodalTeam

# Fold-specific Seeds for Diversity
FOLD_SEEDS = {
    1: 42,
    2: 43,
    3: 44,
    4: 45,
    5: 46,
    6: 47,
    7: 48,
    8: 49,
    9: 50,
    10: 51,
}

# Set Seed
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {DEVICE}")

Device: cuda

## 1. 데이터 로드 및 전처리 (Preprocessing V2.5)

## 2. 이미지 생성 및 증강 (Random Y-Flip)

In [2]:
# Load Raw Training Data
train_df = pd.read_csv("train.csv")
print(f"Loaded {len(train_df)} rows")

Loaded 356721 rows

In [3]:
class MultiModalDataset(Dataset):
    def __init__(self, episodes, img_size=(68, 105), augment=False, cache_images=True):
        self.episodes = episodes
        self.H, self.W = img_size
        self.augment = augment
        self.cache_images = cache_images
        self.img_cache = None
        
        # [v7 Fix] Image Caching (Speed Optimization)
        if self.cache_images:
            print(f"Pre-rendering {len(episodes)} images (Cache Enabled)...")
            # Generate Base Images (No Augmentation applied yet)
            self.img_cache = [self._generate_image(ep['cont']) for ep in tqdm(episodes, desc="Caching Images")]

    def __len__(self):
        return len(self.episodes)

    def _generate_image(self, cont_data):
        # [v6 Optimization] Fast Generation with OpenCV
        img_np = np.zeros((2, self.H, self.W), dtype=np.float32)
        if len(cont_data) == 0:
             return torch.tensor(img_np, dtype=torch.float32)

        seq_len = cont_data.shape[0]
        
        xs = cont_data[:, 0]
        ys = cont_data[:, 1]
        
        # 좌표 변환 (0~1 -> Grid)
        # Note: Input is float (fixed preprocessor), map to int index
        x_idxs = (xs * (self.W - 1)).round().astype(int).clip(0, self.W - 1)
        y_idxs = (ys * (self.H - 1)).round().astype(int).clip(0, self.H - 1)
        
        for t in range(seq_len):
            px, py = x_idxs[t], y_idxs[t]
            
            # Channel 0: Dots
            img_np[0, py, px] = 1.0
            
            decay_val = (t + 1) / seq_len
            
            # Channel 1: Line
            if t > 0:
                prev_px, prev_py = x_idxs[t-1], y_idxs[t-1]
                cv2.line(img_np[1], (prev_px, prev_py), (px, py), color=decay_val, thickness=1)
            else:
                img_np[1, py, px] = decay_val
        return torch.tensor(img_np, dtype=torch.float32)

    def __getitem__(self, idx):
        data = self.episodes[idx]
        
        cont = data['cont'].copy()
        target = data['target'].copy()
        
        # Augmentation Logic (Y-Flip)
        if self.augment and random.random() < 0.5:
            # 1. Flip Continuous Features
            cont[:, 1] = 1.0 - cont[:, 1] # start_y
            cont[:, 3] = 1.0 - cont[:, 3] # end_y_prev
            cont[:, 5] = -cont[:, 5]      # dy_prev (Vector Flip)
            target[1] = 1.0 - target[1]   # Target Flip
            
            # 2. Get Image
            if self.cache_images:
                # Retrieve Base Image from Cache
                base_img = self.img_cache[idx]
                # Apply Flip (Y-Flip = Flip H dimension = dim 1)
                img = torch.flip(base_img, [1])
            else:
                img = self._generate_image(cont) # Generate from flipped coords
        else:
            # No Augmentation
            if self.cache_images:
                img = self.img_cache[idx]
            else:
                img = self._generate_image(cont)
        
        cont_tensor = torch.tensor(cont, dtype=torch.float32)
        cat_tensor = torch.tensor(data['cat'], dtype=torch.long)
        target_tensor = torch.tensor(target, dtype=torch.float32)
        
        # Deep Supervision Targets
        seq_len = cont.shape[0]
        aux_target = np.zeros((seq_len, 2), dtype=np.float32)
        if seq_len > 1:
            aux_target[:-1] = cont[1:, 0:2]
        aux_target[-1] = target # Last step target is GT
        aux_target_tensor = torch.tensor(aux_target, dtype=torch.float32)
        
        return img, cont_tensor, cat_tensor, target_tensor, aux_target_tensor

## 3. 모델 아키텍처 (GRU 적용)

In [4]:
class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super(SpatialAttention, self).__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x_cat = torch.cat([avg_out, max_out], dim=1)
        x_out = self.conv(x_cat)
        return self.sigmoid(x_out)

class ImprovedCNN(nn.Module):
    def __init__(self):
        super(ImprovedCNN, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(2, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128), nn.ReLU(),
        )
        self.sa = SpatialAttention()
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(128, 128)
        
    def forward(self, x):
        x = self.features(x)
        sa_map = self.sa(x)
        x = x * sa_map
        x = self.pool(x).flatten(1)
        x = F.relu(self.fc(x))
        return x

class LSTMAttention(nn.Module):
    def __init__(self, hidden_dim):
        super(LSTMAttention, self).__init__()
        self.attention = nn.Linear(hidden_dim, 1)
    def forward(self, rnn_output):
        attn_weights = torch.softmax(self.attention(rnn_output), dim=1)
        return torch.sum(attn_weights * rnn_output, dim=1)

class MultiModalNetV6(nn.Module):
    def __init__(self, input_dim_cont, num_types, num_results, gru_hidden=96):
        super(MultiModalNetV6, self).__init__()
        self.cnn = ImprovedCNN()
        self.type_emb = nn.Embedding(num_types, 8)
        self.result_emb = nn.Embedding(num_results, 8)
        
        total_input_dim = input_dim_cont + 8 + 8
        self.gru_hidden = gru_hidden
        
        # [변경] Split GRU (Anti-Leakage)
        # Forward와 Backward를 물리적으로 분리하여, Forward GRU에 미래 정보가 유입되는 것을 원천 차단
        self.gru_fwd = nn.GRU(
            input_size=total_input_dim,
            hidden_size=gru_hidden,
            num_layers=2, # Multi-layer OK (Forward끼리만 연결됨)
            batch_first=True,
            bidirectional=False, # 단방향
            dropout=0.1
        )
        
        self.gru_bwd = nn.GRU(
            input_size=total_input_dim,
            hidden_size=gru_hidden,
            num_layers=2,
            batch_first=True,
            bidirectional=False, # 단방향
            dropout=0.1
        )
        
        self.gru_attn = LSTMAttention(gru_hidden * 2)
        self.gru_fc = nn.Linear(gru_hidden * 2, 128)
        
        # [New] Deep Supervision Head
        # Use ONLY Forward Hidden State for Aux Output
        self.aux_fc = nn.Linear(gru_hidden, 2) 
        
        self.fusion_fc = nn.Sequential(
            nn.BatchNorm1d(256), nn.Dropout(0.3),
            nn.Linear(256, 128), nn.ReLU(),
            nn.Linear(128, 2)
        )

    def forward(self, img, cont, cat, lengths):
        # 1. Feature Extraction
        img_feat = self.cnn(img)
        emb_type = self.type_emb(cat[:, :, 0])
        emb_result = self.result_emb(cat[:, :, 1])
        x_seq = torch.cat([cont, emb_type, emb_result], dim=2)
        
        # 2. Forward GRU
        packed_fwd = pack_padded_sequence(x_seq, lengths.cpu(), batch_first=True, enforce_sorted=False)
        out_fwd_packed, _ = self.gru_fwd(packed_fwd)
        out_fwd, _ = pad_packed_sequence(out_fwd_packed, batch_first=True)
        
        # 3. Backward GRU (Manual Flip)
        # Reverse sequence for backward pass
        # Note: Padding should remain at the end, so we need careful reversal?
        # pack_padded_sequence handles lengths correctly, verifying...
        # For simplicity and correctness with variable lengths:
        # We can just reverse the input tensor in time dim, pack, run GRU, unpack, reverse back.
        # But we need to handle padding.
        
        # Optimized Backward Strategy:
        # Since we use pack_padded_sequence with enforce_sorted=False, 
        # we can just flip the non-padded parts? Or just flip the whole tensor and let pack handle it?
        # Actually, PyTorch's pad_packed_sequence output is padded with zeros.
        # It's safer to rely on PyTorch's bidirectional implementation but we can't because of the leakage.
        # So manual flip is needed.
        
        # Manual Flip Logic:
        x_seq_bwd = x_seq.clone()
        for i, length in enumerate(lengths):
            x_seq_bwd[i, :length] = x_seq[i, :length].flip(0)
            
        packed_bwd = pack_padded_sequence(x_seq_bwd, lengths.cpu(), batch_first=True, enforce_sorted=False)
        out_bwd_packed, _ = self.gru_bwd(packed_bwd)
        out_bwd, _ = pad_packed_sequence(out_bwd_packed, batch_first=True)
        
        # Reverse output back to original order
        for i, length in enumerate(lengths):
            out_bwd[i, :length] = out_bwd[i, :length].flip(0)
            
        # 4. Concatenate: [Forward, Backward]
        # out_fwd: [B, L, H], out_bwd: [B, L, H]
        gru_out_combined = torch.cat([out_fwd, out_bwd], dim=2) # [B, L, H*2]
        
        # 5. Main Output (Legacy)
        gru_ctx = self.gru_attn(gru_out_combined)
        seq_feat = F.relu(self.gru_fc(gru_ctx))
        concat_feat = torch.cat([img_feat, seq_feat], dim=1)
        final_out = self.fusion_fc(concat_feat)
        
        # 6. Aux Output (Deep Supervision)
        # Use ONLY out_fwd (Pure Past->Future info)
        aux_out = self.aux_fc(out_fwd) # [B, L, 2]
        
        return final_out, aux_out

class EuclideanLoss(nn.Module):
    def __init__(self):
        super(EuclideanLoss, self).__init__()
    def forward(self, pred, target):
        pred_real = pred * torch.tensor([105.0, 68.0], device=pred.device)
        target_real = target * torch.tensor([105.0, 68.0], device=target.device)
        return torch.mean(torch.sqrt(torch.sum((pred_real - target_real)**2, dim=1) + 1e-6))
        
class MaskedSeqEuclideanLoss(nn.Module):
    def __init__(self):
        super(MaskedSeqEuclideanLoss, self).__init__()
        
    def forward(self, pred, target, lengths):
        # pred: [B, L, 2]
        # target: [B, L, 2]
        # lengths: [B]
        
        mask = torch.arange(pred.size(1), device=pred.device)[None, :] < lengths[:, None]
        mask = mask.unsqueeze(-1) # [B, L, 1]
        
        pred_real = pred * torch.tensor([105.0, 68.0], device=pred.device)
        target_real = target * torch.tensor([105.0, 68.0], device=target.device)
        
        diff = pred_real - target_real
        dist = torch.sqrt(torch.sum(diff**2, dim=2) + 1e-6) # [B, L]
        
        # Masking
        dist = dist * mask.squeeze(-1)
        
        return dist.sum() / mask.sum()

## 4. 학습

In [5]:
def multimodal_collate_fn(batch):
    imgs, conts, cats, targets, aux_targets = zip(*batch)
    imgs_batched = torch.stack(imgs, dim=0)
    lengths = torch.tensor([len(c) for c in conts], dtype=torch.long)
    conts_padded = pad_sequence(conts, batch_first=True)
    cats_padded = pad_sequence(cats, batch_first=True)
    targets = torch.stack(targets, dim=0)
    aux_targets_padded = pad_sequence(aux_targets, batch_first=True)
    return imgs_batched, conts_padded, cats_padded, lengths, targets, aux_targets_padded

In [6]:
# [v7 Fix] Leakage-Free Training Function
# Now receives Raw DataFrame instead of transformed episodes
def train_multimodal_v8_team(train_df, n_splits=10, epochs=100, batch_size=64, lr=0.001):
    gkf = GroupKFold(n_splits=n_splits)
    groups = train_df['game_id'] 
    
    fold_scores = []

    # Get dimensions from first fold (will be same for all folds)
    input_dim_cont = None
    num_types = None
    num_results = None
    
    # K-Fold Loop
    for fold, (train_idx, val_idx) in enumerate(gkf.split(train_df, groups=groups)):
        
        # Set fold-specific seed for diversity
        fold_seed = FOLD_SEEDS[fold + 1]
        seed_everything(fold_seed)
        print(f"[Fold {fold+1}] Seed fixed to {fold_seed}")
        print(f"\n=== Fold {fold+1}/{n_splits} ===")
        
        # 1. Split Raw Data
        train_sub_df = train_df.iloc[train_idx].copy()
        val_sub_df = train_df.iloc[val_idx].copy()
        
        # 2. Fit Preprocessor (Inside Loop -> No Leakage)
        preprocessor = FootballPreprocessorMultimodalTeam()
        preprocessor.fit(train_sub_df)

        # Get dimensions (only once, on first fold)
        if input_dim_cont is None:
            input_dim_cont = preprocessor.get_input_dim()
            num_types, num_results, num_teams = preprocessor.get_num_classes()
            print(f"Model Dimensions: input={input_dim_cont}, types={num_types}, results={num_results}, teams={num_teams}")
        
        # 3. Transform Data
        # 3. Transform Data
        train_episodes = preprocessor.transform(train_sub_df, is_train=True)
        val_episodes = preprocessor.transform(val_sub_df, is_train=True) # Val also needs targets
        
        input_dim_cont = preprocessor.get_input_dim()
        num_types, num_results, num_teams = preprocessor.get_num_classes()
        
        # 4. Dataset & Loader (With Caching)
        # Train: Cache Enabled, Augment Enabled
        train_dataset = MultiModalDataset(train_episodes, augment=True, cache_images=True)
        # Val: Cache Enabled, No Augment
        val_dataset = MultiModalDataset(val_episodes, augment=False, cache_images=True)
        
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=multimodal_collate_fn, drop_last=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, collate_fn=multimodal_collate_fn)
        
        # Model (Split-GRU v6 Architecture)
        model = MultiModalNetV8Team(input_dim_cont, num_types, num_results, num_teams).to(DEVICE)
        
        criterion_main = EuclideanLoss()
        criterion_aux = MaskedSeqEuclideanLoss() 
        
        optimizer = optim.Adam(model.parameters(), lr=lr) 
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)
        
        best_dist = float('inf')
        best_state = None
        patience_counter = 0
        patience_limit = 15
        
        for epoch in range(epochs):
            model.train()
            train_loss = 0
            
            # Tqdm for progress tracking (optional, maybe noisy for user logs)
            # for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
            for batch in train_loader:
                imgs, cont, cat, lengths, target, aux_target = batch
                imgs, cont, cat, lengths, target, aux_target = imgs.to(DEVICE), cont.to(DEVICE), cat.to(DEVICE), lengths.to(DEVICE), target.to(DEVICE), aux_target.to(DEVICE)
                
                optimizer.zero_grad()
                pred, aux_pred = model(imgs, cont, cat, lengths)
                
                loss_m = criterion_main(pred, target)
                loss_a = criterion_aux(aux_pred, aux_target, lengths)
                
                loss = loss_m + 0.5 * loss_a
                loss.backward()
                optimizer.step()
                train_loss += loss.item()
            
            train_loss /= len(train_loader)
            
            model.eval()
            val_dists = []
            with torch.no_grad():
                for batch in val_loader:
                    imgs, cont, cat, lengths, target, aux_target = batch
                    imgs, cont, cat, lengths, target, aux_target = imgs.to(DEVICE), cont.to(DEVICE), cat.to(DEVICE), lengths.to(DEVICE), target.to(DEVICE), aux_target.to(DEVICE)
                    
                    pred, _ = model(imgs, cont, cat, lengths)
                    
                    pred_real = pred.cpu().numpy() * np.array([105.0, 68.0])
                    target_real = target.cpu().numpy() * np.array([105.0, 68.0])
                    val_dists.extend(np.sqrt(np.sum((pred_real - target_real)**2, axis=1)))
            
            mean_dist = np.mean(val_dists)
            scheduler.step(mean_dist)
            print(f"Epoch {epoch+1}: Train Loss {train_loss:.4f}, Val Dist {mean_dist:.4f}")
            
            if mean_dist < best_dist:
                best_dist = mean_dist
                best_state = model.state_dict()
                # Save with v7 suffix
                torch.save(best_state, f"models/multimodal_v8_team_h96_{fold+1}.pth")
                joblib.dump(preprocessor, f"models/preprocessor_v8_team_h96_{fold+1}.pkl")
                print(f"  -> Saved Best Model (Dist: {best_dist:.4f})")
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= patience_limit:
                    print("Early Stopping")
                    break
        
        print(f"Fold {fold+1} Finished. Best Valid Dist: {best_dist:.4f}")
        fold_scores.append(best_dist)
        
    print(f"Average Score: {np.mean(fold_scores):.4f}")

In [8]:
# [v7 Execution]
train_multimodal_v8_team(train_df, n_splits=10, epochs=100, batch_size=32, lr=0.001)

[Fold 1] Seed fixed to 42

=== Fold 1/10 ===
Model Dimensions: input=10, types=27, results=21, teams=13
Pre-rendering 13847 images (Cache Enabled)...

Caching Images: 100%|██████████| 13847/13847 [00:01<00:00, 13144.91it/s]

Pre-rendering 1581 images (Cache Enabled)...

Caching Images: 100%|██████████| 1581/1581 [00:00<00:00, 13372.69it/s]

Epoch 1: Train Loss 62.2199, Val Dist 20.9712
  -> Saved Best Model (Dist: 20.9712)
Epoch 2: Train Loss 49.2329, Val Dist 17.5269
  -> Saved Best Model (Dist: 17.5269)
Epoch 3: Train Loss 46.3847, Val Dist 18.1095
Epoch 4: Train Loss 44.8850, Val Dist 16.1248
  -> Saved Best Model (Dist: 16.1248)
Epoch 5: Train Loss 43.9164, Val Dist 15.2574
  -> Saved Best Model (Dist: 15.2574)
Epoch 6: Train Loss 43.2210, Val Dist 14.8752
  -> Saved Best Model (Dist: 14.8752)
Epoch 7: Train Loss 42.5923, Val Dist 14.7858
  -> Saved Best Model (Dist: 14.7858)
Epoch 8: Train Loss 42.1838, Val Dist 14.7978
Epoch 9: Train Loss 42.0644, Val Dist 14.9110
Epoch 10: Train Loss 41.3893, Val Dist 14.9113
Epoch 11: Train Loss 41.1888, Val Dist 14.3177
  -> Saved Best Model (Dist: 14.3177)
Epoch 12: Train Loss 40.8521, Val Dist 14.3704
Epoch 13: Train Loss 40.6391, Val Dist 14.7111
Epoch 14: Train Loss 40.4529, Val Dist 14.8804
Epoch 15: Train Loss 40.2241, Val Dist 14.5072
Epoch 16: Train Loss 39.7415, Val Dist 14.0149
  -> Saved Best Model (Dist: 14.0149)
Epoch 17: Train Loss 39.4444, Val Dist 14.1605
Epoch 18: Train Loss 39.4267, Val Dist 13.9735
  -> Saved Best Model (Dist: 13.9735)
Epoch 19: Train Loss 39.2947, Val Dist 14.0326
Epoch 20: Train Loss 39.1318, Val Dist 14.2898
Epoch 21: Train Loss 39.0750, Val Dist 13.9882
Epoch 22: Train Loss 39.0465, Val Dist 14.1003
Epoch 23: Train Loss 38.6719, Val Dist 13.8806
  -> Saved Best Model (Dist: 13.8806)
Epoch 24: Train Loss 38.5212, Val Dist 13.8902
Epoch 25: Train Loss 38.5503, Val Dist 14.0668
Epoch 26: Train Loss 38.5484, Val Dist 13.9212
Epoch 27: Train Loss 38.4696, Val Dist 13.9694
Epoch 28: Train Loss 38.2537, Val Dist 13.7566
  -> Saved Best Model (Dist: 13.7566)
Epoch 29: Train Loss 38.1692, Val Dist 13.8939
Epoch 30: Train Loss 38.1804, Val Dist 13.8838
Epoch 31: Train Loss 38.1739, Val Dist 13.8540
Epoch 32: Train Loss 38.0986, Val Dist 13.8084
Epoch 33: Train Loss 38.0340, Val Dist 13.7423
  -> Saved Best Model (Dist: 13.7423)
Epoch 34: Train Loss 37.9711, Val Dist 13.8157
Epoch 35: Train Loss 37.8764, Val Dist 13.8454
Epoch 36: Train Loss 37.9256, Val Dist 13.7688
Epoch 37: Train Loss 37.9283, Val Dist 13.8248
Epoch 38: Train Loss 37.8933, Val Dist 13.7534
Epoch 39: Train Loss 37.8893, Val Dist 13.7930
Epoch 40: Train Loss 37.8419, Val Dist 13.7585
Epoch 41: Train Loss 37.8449, Val Dist 13.7692
Epoch 42: Train Loss 37.8185, Val Dist 13.7470
Epoch 43: Train Loss 37.8043, Val Dist 13.7908
Epoch 44: Train Loss 37.8741, Val Dist 13.7331
  -> Saved Best Model (Dist: 13.7331)
Epoch 45: Train Loss 37.8371, Val Dist 13.7493
Epoch 46: Train Loss 37.8145, Val Dist 13.7305
  -> Saved Best Model (Dist: 13.7305)
Epoch 47: Train Loss 37.7878, Val Dist 13.7451
Epoch 48: Train Loss 37.7839, Val Dist 13.8015
Epoch 49: Train Loss 37.7892, Val Dist 13.7515
Epoch 50: Train Loss 37.7451, Val Dist 13.8195
Epoch 51: Train Loss 37.7931, Val Dist 13.7649
Epoch 52: Train Loss 37.7561, Val Dist 13.7711
Epoch 53: Train Loss 37.7942, Val Dist 13.7490
Epoch 54: Train Loss 37.8526, Val Dist 13.8022
Epoch 55: Train Loss 37.6991, Val Dist 13.8170
Epoch 56: Train Loss 37.7627, Val Dist 13.7456
Epoch 57: Train Loss 37.7749, Val Dist 13.7847
Epoch 58: Train Loss 37.7365, Val Dist 13.7300
  -> Saved Best Model (Dist: 13.7300)
Epoch 59: Train Loss 37.7423, Val Dist 13.7275
  -> Saved Best Model (Dist: 13.7275)
Epoch 60: Train Loss 37.7736, Val Dist 13.7521
Epoch 61: Train Loss 37.7145, Val Dist 13.7573
Epoch 62: Train Loss 37.6965, Val Dist 13.7641
Epoch 63: Train Loss 37.7455, Val Dist 13.8239
Epoch 64: Train Loss 37.7397, Val Dist 13.7782
Epoch 65: Train Loss 37.7921, Val Dist 13.7640
Epoch 66: Train Loss 37.7510, Val Dist 13.7547
Epoch 67: Train Loss 37.7745, Val Dist 13.7728
Epoch 68: Train Loss 37.7739, Val Dist 13.7634
Epoch 69: Train Loss 37.7629, Val Dist 13.7506
Epoch 70: Train Loss 37.7757, Val Dist 13.7394
Epoch 71: Train Loss 37.8411, Val Dist 13.7941
Epoch 72: Train Loss 37.7594, Val Dist 13.7605
Epoch 73: Train Loss 37.7714, Val Dist 13.7363
Epoch 74: Train Loss 37.6863, Val Dist 13.7362
Early Stopping
Fold 1 Finished. Best Valid Dist: 13.7275
[Fold 2] Seed fixed to 43

=== Fold 2/10 ===
Pre-rendering 13934 images (Cache Enabled)...

Caching Images: 100%|██████████| 13934/13934 [00:01<00:00, 12714.88it/s]

Pre-rendering 1494 images (Cache Enabled)...

Caching Images: 100%|██████████| 1494/1494 [00:00<00:00, 10601.77it/s]

Epoch 1: Train Loss 62.8551, Val Dist 19.7405
  -> Saved Best Model (Dist: 19.7405)
Epoch 2: Train Loss 48.6608, Val Dist 18.7839
  -> Saved Best Model (Dist: 18.7839)
Epoch 3: Train Loss 46.1657, Val Dist 17.8291
  -> Saved Best Model (Dist: 17.8291)
Epoch 4: Train Loss 44.5220, Val Dist 16.5858
  -> Saved Best Model (Dist: 16.5858)
Epoch 5: Train Loss 43.7260, Val Dist 15.3672
  -> Saved Best Model (Dist: 15.3672)
Epoch 6: Train Loss 42.9176, Val Dist 15.2042
  -> Saved Best Model (Dist: 15.2042)
Epoch 7: Train Loss 42.4746, Val Dist 14.8005
  -> Saved Best Model (Dist: 14.8005)
Epoch 8: Train Loss 42.0874, Val Dist 15.4928
Epoch 9: Train Loss 41.6709, Val Dist 14.7617
  -> Saved Best Model (Dist: 14.7617)
Epoch 10: Train Loss 41.4826, Val Dist 15.7396
Epoch 11: Train Loss 41.2440, Val Dist 14.6624
  -> Saved Best Model (Dist: 14.6624)
Epoch 12: Train Loss 40.9707, Val Dist 14.5045
  -> Saved Best Model (Dist: 14.5045)
Epoch 13: Train Loss 40.7877, Val Dist 14.5156
Epoch 14: Train Loss 40.6570, Val Dist 14.9159
Epoch 15: Train Loss 40.3723, Val Dist 14.4980
  -> Saved Best Model (Dist: 14.4980)
Epoch 16: Train Loss 40.3315, Val Dist 14.6714
Epoch 17: Train Loss 39.9946, Val Dist 14.4055
  -> Saved Best Model (Dist: 14.4055)
Epoch 18: Train Loss 40.1094, Val Dist 14.6807
Epoch 19: Train Loss 39.7735, Val Dist 14.3329
  -> Saved Best Model (Dist: 14.3329)
Epoch 20: Train Loss 39.6539, Val Dist 14.2692
  -> Saved Best Model (Dist: 14.2692)
Epoch 21: Train Loss 39.6115, Val Dist 15.0552
Epoch 22: Train Loss 39.5311, Val Dist 14.1696
  -> Saved Best Model (Dist: 14.1696)
Epoch 23: Train Loss 39.3674, Val Dist 14.4026
Epoch 24: Train Loss 39.2615, Val Dist 13.9959
  -> Saved Best Model (Dist: 13.9959)
Epoch 25: Train Loss 39.0835, Val Dist 14.2253
Epoch 26: Train Loss 39.0591, Val Dist 14.1221
Epoch 27: Train Loss 38.9603, Val Dist 14.1530
Epoch 28: Train Loss 38.8569, Val Dist 13.9225
  -> Saved Best Model (Dist: 13.9225)
Epoch 29: Train Loss 38.8622, Val Dist 13.9852
Epoch 30: Train Loss 38.7100, Val Dist 13.8901
  -> Saved Best Model (Dist: 13.8901)
Epoch 31: Train Loss 38.6109, Val Dist 13.8381
  -> Saved Best Model (Dist: 13.8381)
Epoch 32: Train Loss 38.6283, Val Dist 14.1127
Epoch 33: Train Loss 38.3753, Val Dist 14.0231
Epoch 34: Train Loss 38.4011, Val Dist 13.8830
Epoch 35: Train Loss 38.3721, Val Dist 14.0353
Epoch 36: Train Loss 37.7837, Val Dist 13.9183
Epoch 37: Train Loss 37.5521, Val Dist 13.9100
Epoch 38: Train Loss 37.6602, Val Dist 13.8136
  -> Saved Best Model (Dist: 13.8136)
Epoch 39: Train Loss 37.4696, Val Dist 13.7290
  -> Saved Best Model (Dist: 13.7290)
Epoch 40: Train Loss 37.3876, Val Dist 13.8180
Epoch 41: Train Loss 37.2791, Val Dist 13.6479
  -> Saved Best Model (Dist: 13.6479)
Epoch 42: Train Loss 37.2022, Val Dist 13.9150
Epoch 43: Train Loss 37.2178, Val Dist 14.0251
Epoch 44: Train Loss 37.1772, Val Dist 13.9510
Epoch 45: Train Loss 37.0328, Val Dist 13.7624
Epoch 46: Train Loss 36.7779, Val Dist 13.8293
Epoch 47: Train Loss 36.7813, Val Dist 13.9791
Epoch 48: Train Loss 36.6441, Val Dist 13.8104
Epoch 49: Train Loss 36.5807, Val Dist 13.8850
Epoch 50: Train Loss 36.4660, Val Dist 13.8462
Epoch 51: Train Loss 36.3724, Val Dist 13.8263
Epoch 52: Train Loss 36.3459, Val Dist 13.8805
Epoch 53: Train Loss 36.3076, Val Dist 13.7993
Epoch 54: Train Loss 36.3174, Val Dist 13.7911
Epoch 55: Train Loss 36.2128, Val Dist 13.8118
Epoch 56: Train Loss 36.1593, Val Dist 13.7341
Early Stopping
Fold 2 Finished. Best Valid Dist: 13.6479
[Fold 3] Seed fixed to 44

=== Fold 3/10 ===
Pre-rendering 13865 images (Cache Enabled)...

Caching Images: 100%|██████████| 13865/13865 [00:00<00:00, 14259.75it/s]

Pre-rendering 1563 images (Cache Enabled)...

Caching Images: 100%|██████████| 1563/1563 [00:00<00:00, 13677.82it/s]

Epoch 1: Train Loss 61.6503, Val Dist 19.3050
  -> Saved Best Model (Dist: 19.3050)
Epoch 2: Train Loss 48.8938, Val Dist 17.7679
  -> Saved Best Model (Dist: 17.7679)
Epoch 3: Train Loss 46.6658, Val Dist 17.0870
  -> Saved Best Model (Dist: 17.0870)
Epoch 4: Train Loss 45.1782, Val Dist 16.7835
  -> Saved Best Model (Dist: 16.7835)
Epoch 5: Train Loss 43.8633, Val Dist 15.3791
  -> Saved Best Model (Dist: 15.3791)
Epoch 6: Train Loss 43.2845, Val Dist 15.1559
  -> Saved Best Model (Dist: 15.1559)
Epoch 7: Train Loss 42.7658, Val Dist 14.6605
  -> Saved Best Model (Dist: 14.6605)
Epoch 8: Train Loss 42.2090, Val Dist 14.7333
Epoch 9: Train Loss 41.9135, Val Dist 14.4921
  -> Saved Best Model (Dist: 14.4921)
Epoch 10: Train Loss 41.6641, Val Dist 14.6064
Epoch 11: Train Loss 41.1639, Val Dist 14.4596
  -> Saved Best Model (Dist: 14.4596)
Epoch 12: Train Loss 40.9113, Val Dist 15.3041
Epoch 13: Train Loss 40.8829, Val Dist 13.9649
  -> Saved Best Model (Dist: 13.9649)
Epoch 14: Train Loss 40.6737, Val Dist 14.5685
Epoch 15: Train Loss 40.3829, Val Dist 14.0999
Epoch 16: Train Loss 40.2752, Val Dist 13.8963
  -> Saved Best Model (Dist: 13.8963)
Epoch 17: Train Loss 40.0048, Val Dist 14.2221
Epoch 18: Train Loss 39.9459, Val Dist 13.9540
Epoch 19: Train Loss 39.8146, Val Dist 14.1632
Epoch 20: Train Loss 39.7606, Val Dist 13.9735
Epoch 21: Train Loss 39.0616, Val Dist 13.7773
  -> Saved Best Model (Dist: 13.7773)
Epoch 22: Train Loss 38.8862, Val Dist 13.7039
  -> Saved Best Model (Dist: 13.7039)
Epoch 23: Train Loss 38.8987, Val Dist 13.6693
  -> Saved Best Model (Dist: 13.6693)
Epoch 24: Train Loss 38.8073, Val Dist 13.6140
  -> Saved Best Model (Dist: 13.6140)
Epoch 25: Train Loss 38.7076, Val Dist 13.6361
Epoch 26: Train Loss 38.5872, Val Dist 13.4307
  -> Saved Best Model (Dist: 13.4307)
Epoch 27: Train Loss 38.5651, Val Dist 13.8587
Epoch 28: Train Loss 38.4215, Val Dist 13.6806
Epoch 29: Train Loss 38.4645, Val Dist 13.6061
Epoch 30: Train Loss 38.3341, Val Dist 13.5219
Epoch 31: Train Loss 38.0632, Val Dist 13.5754
Epoch 32: Train Loss 37.8749, Val Dist 13.4840
Epoch 33: Train Loss 37.9272, Val Dist 13.4184
  -> Saved Best Model (Dist: 13.4184)
Epoch 34: Train Loss 37.8208, Val Dist 13.4994
Epoch 35: Train Loss 37.8415, Val Dist 13.5114
Epoch 36: Train Loss 37.7752, Val Dist 13.5471
Epoch 37: Train Loss 37.7472, Val Dist 13.4156
  -> Saved Best Model (Dist: 13.4156)
Epoch 38: Train Loss 37.7181, Val Dist 13.5244
Epoch 39: Train Loss 37.5710, Val Dist 13.6463
Epoch 40: Train Loss 37.6005, Val Dist 13.5404
Epoch 41: Train Loss 37.5966, Val Dist 13.6247
Epoch 42: Train Loss 37.3969, Val Dist 13.4643
Epoch 43: Train Loss 37.4379, Val Dist 13.5574
Epoch 44: Train Loss 37.4364, Val Dist 13.4779
Epoch 45: Train Loss 37.3742, Val Dist 13.5272
Epoch 46: Train Loss 37.2595, Val Dist 13.4609
Epoch 47: Train Loss 37.2281, Val Dist 13.4812
Epoch 48: Train Loss 37.1511, Val Dist 13.5066
Epoch 49: Train Loss 37.1596, Val Dist 13.5715
Epoch 50: Train Loss 37.1208, Val Dist 13.5242
Epoch 51: Train Loss 37.0621, Val Dist 13.5214
Epoch 52: Train Loss 37.1467, Val Dist 13.4554
Early Stopping
Fold 3 Finished. Best Valid Dist: 13.4156
[Fold 4] Seed fixed to 45

=== Fold 4/10 ===
Pre-rendering 13857 images (Cache Enabled)...

Caching Images: 100%|██████████| 13857/13857 [00:01<00:00, 13387.73it/s]

Pre-rendering 1571 images (Cache Enabled)...

Caching Images: 100%|██████████| 1571/1571 [00:00<00:00, 12762.47it/s]

Epoch 1: Train Loss 60.6024, Val Dist 21.4931
  -> Saved Best Model (Dist: 21.4931)
Epoch 2: Train Loss 48.3491, Val Dist 18.9225
  -> Saved Best Model (Dist: 18.9225)
Epoch 3: Train Loss 46.0606, Val Dist 17.5675
  -> Saved Best Model (Dist: 17.5675)
Epoch 4: Train Loss 44.8947, Val Dist 16.1392
  -> Saved Best Model (Dist: 16.1392)
Epoch 5: Train Loss 43.7968, Val Dist 15.3748
  -> Saved Best Model (Dist: 15.3748)
Epoch 6: Train Loss 43.1725, Val Dist 15.0323
  -> Saved Best Model (Dist: 15.0323)
Epoch 7: Train Loss 42.6640, Val Dist 15.7615
Epoch 8: Train Loss 42.1667, Val Dist 15.4237
Epoch 9: Train Loss 41.7106, Val Dist 15.3005
Epoch 10: Train Loss 41.4391, Val Dist 14.8425
  -> Saved Best Model (Dist: 14.8425)
Epoch 11: Train Loss 41.2459, Val Dist 14.7445
  -> Saved Best Model (Dist: 14.7445)
Epoch 12: Train Loss 40.9283, Val Dist 14.3526
  -> Saved Best Model (Dist: 14.3526)
Epoch 13: Train Loss 40.6288, Val Dist 14.7909
Epoch 14: Train Loss 40.4901, Val Dist 14.6372
Epoch 15: Train Loss 40.3491, Val Dist 15.2487
Epoch 16: Train Loss 40.2629, Val Dist 14.2563
  -> Saved Best Model (Dist: 14.2563)
Epoch 17: Train Loss 40.0874, Val Dist 14.2263
  -> Saved Best Model (Dist: 14.2263)
Epoch 18: Train Loss 39.7565, Val Dist 14.4612
Epoch 19: Train Loss 39.7338, Val Dist 14.4612
Epoch 20: Train Loss 39.6676, Val Dist 14.1872
  -> Saved Best Model (Dist: 14.1872)
Epoch 21: Train Loss 39.4884, Val Dist 14.4418
Epoch 22: Train Loss 39.2916, Val Dist 14.3595
Epoch 23: Train Loss 39.2310, Val Dist 14.3307
Epoch 24: Train Loss 39.0991, Val Dist 14.4644
Epoch 25: Train Loss 38.5980, Val Dist 13.9857
  -> Saved Best Model (Dist: 13.9857)
Epoch 26: Train Loss 38.4685, Val Dist 14.0721
Epoch 27: Train Loss 38.3673, Val Dist 13.9184
  -> Saved Best Model (Dist: 13.9184)
Epoch 28: Train Loss 38.3072, Val Dist 14.1435
Epoch 29: Train Loss 38.1734, Val Dist 14.1079
Epoch 30: Train Loss 38.1304, Val Dist 14.0105
Epoch 31: Train Loss 38.1184, Val Dist 14.0638
Epoch 32: Train Loss 37.7425, Val Dist 13.9281
Epoch 33: Train Loss 37.6669, Val Dist 14.0117
Epoch 34: Train Loss 37.6310, Val Dist 14.1098
Epoch 35: Train Loss 37.5883, Val Dist 13.8930
  -> Saved Best Model (Dist: 13.8930)
Epoch 36: Train Loss 37.5407, Val Dist 14.0619
Epoch 37: Train Loss 37.5574, Val Dist 13.8655
  -> Saved Best Model (Dist: 13.8655)
Epoch 38: Train Loss 37.5073, Val Dist 14.1155
Epoch 39: Train Loss 37.3552, Val Dist 13.8425
  -> Saved Best Model (Dist: 13.8425)
Epoch 40: Train Loss 37.3644, Val Dist 13.8644
Epoch 41: Train Loss 37.3294, Val Dist 14.0248
Epoch 42: Train Loss 37.3821, Val Dist 13.8951
Epoch 43: Train Loss 37.3190, Val Dist 13.9989
Epoch 44: Train Loss 37.1266, Val Dist 13.9690
Epoch 45: Train Loss 37.0291, Val Dist 13.8920
Epoch 46: Train Loss 37.0130, Val Dist 13.9181
Epoch 47: Train Loss 36.9623, Val Dist 13.8492
Epoch 48: Train Loss 36.9086, Val Dist 13.8452
Epoch 49: Train Loss 36.9334, Val Dist 13.9012
Epoch 50: Train Loss 36.8530, Val Dist 13.8768
Epoch 51: Train Loss 36.7926, Val Dist 13.8874
Epoch 52: Train Loss 36.7305, Val Dist 13.8602
Epoch 53: Train Loss 36.7494, Val Dist 13.8922
Epoch 54: Train Loss 36.8085, Val Dist 13.8706
Early Stopping
Fold 4 Finished. Best Valid Dist: 13.8425
[Fold 5] Seed fixed to 46

=== Fold 5/10 ===
Pre-rendering 13965 images (Cache Enabled)...

Caching Images: 100%|██████████| 13965/13965 [00:00<00:00, 14493.83it/s]

Pre-rendering 1463 images (Cache Enabled)...

Caching Images: 100%|██████████| 1463/1463 [00:00<00:00, 11386.57it/s]

Epoch 1: Train Loss 61.5996, Val Dist 20.0712
  -> Saved Best Model (Dist: 20.0712)
Epoch 2: Train Loss 48.6903, Val Dist 19.3751
  -> Saved Best Model (Dist: 19.3751)
Epoch 3: Train Loss 46.2027, Val Dist 16.2838
  -> Saved Best Model (Dist: 16.2838)
Epoch 4: Train Loss 44.7598, Val Dist 16.1134
  -> Saved Best Model (Dist: 16.1134)
Epoch 5: Train Loss 43.6652, Val Dist 15.9195
  -> Saved Best Model (Dist: 15.9195)
Epoch 6: Train Loss 43.1167, Val Dist 14.9325
  -> Saved Best Model (Dist: 14.9325)
Epoch 7: Train Loss 42.5386, Val Dist 15.3167
Epoch 8: Train Loss 42.2271, Val Dist 15.0177
Epoch 9: Train Loss 41.7664, Val Dist 15.1977
Epoch 10: Train Loss 41.5091, Val Dist 14.7606
  -> Saved Best Model (Dist: 14.7606)
Epoch 11: Train Loss 41.0379, Val Dist 14.4713
  -> Saved Best Model (Dist: 14.4713)
Epoch 12: Train Loss 41.0238, Val Dist 14.6210
Epoch 13: Train Loss 40.7842, Val Dist 15.2095
Epoch 14: Train Loss 40.6201, Val Dist 14.6204
Epoch 15: Train Loss 40.3480, Val Dist 14.3302
  -> Saved Best Model (Dist: 14.3302)
Epoch 16: Train Loss 40.2692, Val Dist 14.2546
  -> Saved Best Model (Dist: 14.2546)
Epoch 17: Train Loss 40.0688, Val Dist 14.4375
Epoch 18: Train Loss 39.8504, Val Dist 14.2555
Epoch 19: Train Loss 39.7588, Val Dist 14.2814
Epoch 20: Train Loss 39.6599, Val Dist 14.1869
  -> Saved Best Model (Dist: 14.1869)
Epoch 21: Train Loss 39.6134, Val Dist 14.3681
Epoch 22: Train Loss 39.4300, Val Dist 14.0918
  -> Saved Best Model (Dist: 14.0918)
Epoch 23: Train Loss 39.2812, Val Dist 14.1553
Epoch 24: Train Loss 39.1574, Val Dist 14.0604
  -> Saved Best Model (Dist: 14.0604)
Epoch 25: Train Loss 39.1006, Val Dist 13.9307
  -> Saved Best Model (Dist: 13.9307)
Epoch 26: Train Loss 38.9230, Val Dist 13.9080
  -> Saved Best Model (Dist: 13.9080)
Epoch 27: Train Loss 38.8272, Val Dist 14.0842
Epoch 28: Train Loss 38.8283, Val Dist 14.1329
Epoch 29: Train Loss 38.6395, Val Dist 13.9948
Epoch 30: Train Loss 38.5611, Val Dist 14.0973
Epoch 31: Train Loss 38.0577, Val Dist 13.6710
  -> Saved Best Model (Dist: 13.6710)
Epoch 32: Train Loss 37.8684, Val Dist 13.7421
Epoch 33: Train Loss 37.8261, Val Dist 14.1660
Epoch 34: Train Loss 37.7346, Val Dist 13.7747
Epoch 35: Train Loss 37.6204, Val Dist 13.6485
  -> Saved Best Model (Dist: 13.6485)
Epoch 36: Train Loss 37.6547, Val Dist 13.7022
Epoch 37: Train Loss 37.5435, Val Dist 13.6492
Epoch 38: Train Loss 37.5097, Val Dist 13.6495
Epoch 39: Train Loss 37.4739, Val Dist 13.7982
Epoch 40: Train Loss 37.1195, Val Dist 13.5642
  -> Saved Best Model (Dist: 13.5642)
Epoch 41: Train Loss 37.0011, Val Dist 13.6366
Epoch 42: Train Loss 36.9761, Val Dist 13.7254
Epoch 43: Train Loss 36.9341, Val Dist 13.6010
Epoch 44: Train Loss 36.8924, Val Dist 13.5965
Epoch 45: Train Loss 36.6998, Val Dist 13.6763
Epoch 46: Train Loss 36.6811, Val Dist 13.5379
  -> Saved Best Model (Dist: 13.5379)
Epoch 47: Train Loss 36.6783, Val Dist 13.6336
Epoch 48: Train Loss 36.6398, Val Dist 13.5467
Epoch 49: Train Loss 36.5918, Val Dist 13.5115
  -> Saved Best Model (Dist: 13.5115)
Epoch 50: Train Loss 36.6066, Val Dist 13.6086
Epoch 51: Train Loss 36.4789, Val Dist 13.6148
Epoch 52: Train Loss 36.4544, Val Dist 13.6293
Epoch 53: Train Loss 36.4972, Val Dist 13.6195
Epoch 54: Train Loss 36.3418, Val Dist 13.5454
Epoch 55: Train Loss 36.4203, Val Dist 13.5945
Epoch 56: Train Loss 36.3244, Val Dist 13.5751
Epoch 57: Train Loss 36.2632, Val Dist 13.5676
Epoch 58: Train Loss 36.2558, Val Dist 13.6148
Epoch 59: Train Loss 36.2918, Val Dist 13.5730
Epoch 60: Train Loss 36.2886, Val Dist 13.6046
Epoch 61: Train Loss 36.2802, Val Dist 13.5880
Epoch 62: Train Loss 36.2637, Val Dist 13.6277
Epoch 63: Train Loss 36.2141, Val Dist 13.6023
Epoch 64: Train Loss 36.2988, Val Dist 13.6908
Early Stopping
Fold 5 Finished. Best Valid Dist: 13.5115
[Fold 6] Seed fixed to 47

=== Fold 6/10 ===
Pre-rendering 13870 images (Cache Enabled)...

Caching Images: 100%|██████████| 13870/13870 [00:00<00:00, 14507.48it/s]

Pre-rendering 1558 images (Cache Enabled)...

Caching Images: 100%|██████████| 1558/1558 [00:00<00:00, 12925.03it/s]

Epoch 1: Train Loss 61.2485, Val Dist 20.1107
  -> Saved Best Model (Dist: 20.1107)
Epoch 2: Train Loss 48.3979, Val Dist 17.7383
  -> Saved Best Model (Dist: 17.7383)
Epoch 3: Train Loss 45.9664, Val Dist 17.9918
Epoch 4: Train Loss 44.5583, Val Dist 15.6686
  -> Saved Best Model (Dist: 15.6686)
Epoch 5: Train Loss 43.5140, Val Dist 15.8585
Epoch 6: Train Loss 42.8688, Val Dist 14.7679
  -> Saved Best Model (Dist: 14.7679)
Epoch 7: Train Loss 42.3797, Val Dist 15.0817
Epoch 8: Train Loss 42.0874, Val Dist 14.8252
Epoch 9: Train Loss 41.6362, Val Dist 15.7187
Epoch 10: Train Loss 41.3004, Val Dist 14.3659
  -> Saved Best Model (Dist: 14.3659)
Epoch 11: Train Loss 41.1001, Val Dist 14.6360
Epoch 12: Train Loss 40.9089, Val Dist 14.8096
Epoch 13: Train Loss 40.6382, Val Dist 14.4452
Epoch 14: Train Loss 40.5035, Val Dist 14.4035
Epoch 15: Train Loss 39.9317, Val Dist 14.1582
  -> Saved Best Model (Dist: 14.1582)
Epoch 16: Train Loss 39.7090, Val Dist 13.9609
  -> Saved Best Model (Dist: 13.9609)
Epoch 17: Train Loss 39.6114, Val Dist 14.0181
Epoch 18: Train Loss 39.4932, Val Dist 14.0075
Epoch 19: Train Loss 39.4562, Val Dist 14.0666
Epoch 20: Train Loss 39.3216, Val Dist 14.1104
Epoch 21: Train Loss 39.0512, Val Dist 13.9013
  -> Saved Best Model (Dist: 13.9013)
Epoch 22: Train Loss 38.8659, Val Dist 13.7265
  -> Saved Best Model (Dist: 13.7265)
Epoch 23: Train Loss 38.8214, Val Dist 13.8455
Epoch 24: Train Loss 38.8315, Val Dist 13.8444
Epoch 25: Train Loss 38.7823, Val Dist 13.7089
  -> Saved Best Model (Dist: 13.7089)
Epoch 26: Train Loss 38.6929, Val Dist 13.8921
Epoch 27: Train Loss 38.6578, Val Dist 13.7795
Epoch 28: Train Loss 38.5948, Val Dist 13.6384
  -> Saved Best Model (Dist: 13.6384)
Epoch 29: Train Loss 38.5169, Val Dist 13.7949
Epoch 30: Train Loss 38.5473, Val Dist 13.6661
Epoch 31: Train Loss 38.4160, Val Dist 13.7700
Epoch 32: Train Loss 38.5008, Val Dist 13.7079
Epoch 33: Train Loss 38.2462, Val Dist 13.5477
  -> Saved Best Model (Dist: 13.5477)
Epoch 34: Train Loss 38.1757, Val Dist 13.5831
Epoch 35: Train Loss 38.1635, Val Dist 13.5739
Epoch 36: Train Loss 38.0947, Val Dist 13.5219
  -> Saved Best Model (Dist: 13.5219)
Epoch 37: Train Loss 38.0641, Val Dist 13.6752
Epoch 38: Train Loss 38.0559, Val Dist 13.5489
Epoch 39: Train Loss 38.0180, Val Dist 13.5365
Epoch 40: Train Loss 38.0461, Val Dist 13.7071
Epoch 41: Train Loss 37.9421, Val Dist 13.5910
Epoch 42: Train Loss 37.9131, Val Dist 13.5300
Epoch 43: Train Loss 37.8669, Val Dist 13.5519
Epoch 44: Train Loss 37.8586, Val Dist 13.6256
Epoch 45: Train Loss 37.8810, Val Dist 13.5489
Epoch 46: Train Loss 37.8264, Val Dist 13.5261
Epoch 47: Train Loss 37.7659, Val Dist 13.4877
  -> Saved Best Model (Dist: 13.4877)
Epoch 48: Train Loss 37.7750, Val Dist 13.5827
Epoch 49: Train Loss 37.7529, Val Dist 13.5331
Epoch 50: Train Loss 37.7657, Val Dist 13.5427
Epoch 51: Train Loss 37.8380, Val Dist 13.5083
Epoch 52: Train Loss 37.7668, Val Dist 13.4941
Epoch 53: Train Loss 37.7056, Val Dist 13.5294
Epoch 54: Train Loss 37.6826, Val Dist 13.5316
Epoch 55: Train Loss 37.7497, Val Dist 13.4883
Epoch 56: Train Loss 37.7206, Val Dist 13.4846
  -> Saved Best Model (Dist: 13.4846)
Epoch 57: Train Loss 37.7327, Val Dist 13.5216
Epoch 58: Train Loss 37.6876, Val Dist 13.4908
Epoch 59: Train Loss 37.7574, Val Dist 13.5442
Epoch 60: Train Loss 37.7616, Val Dist 13.5074
Epoch 61: Train Loss 37.7542, Val Dist 13.4800
  -> Saved Best Model (Dist: 13.4800)
Epoch 62: Train Loss 37.6859, Val Dist 13.5134
Epoch 63: Train Loss 37.7021, Val Dist 13.5124
Epoch 64: Train Loss 37.7217, Val Dist 13.5912
Epoch 65: Train Loss 37.7253, Val Dist 13.5093
Epoch 66: Train Loss 37.6622, Val Dist 13.4966
Epoch 67: Train Loss 37.7271, Val Dist 13.5268
Epoch 68: Train Loss 37.6703, Val Dist 13.5037
Epoch 69: Train Loss 37.6163, Val Dist 13.5253
Epoch 70: Train Loss 37.7381, Val Dist 13.5843
Epoch 71: Train Loss 37.7129, Val Dist 13.4795
  -> Saved Best Model (Dist: 13.4795)
Epoch 72: Train Loss 37.7076, Val Dist 13.4899
Epoch 73: Train Loss 37.6731, Val Dist 13.4856
Epoch 74: Train Loss 37.6895, Val Dist 13.5042
Epoch 75: Train Loss 37.7611, Val Dist 13.5461
Epoch 76: Train Loss 37.7017, Val Dist 13.5109
Epoch 77: Train Loss 37.6978, Val Dist 13.4825
Epoch 78: Train Loss 37.6997, Val Dist 13.4896
Epoch 79: Train Loss 37.6302, Val Dist 13.4954
Epoch 80: Train Loss 37.6499, Val Dist 13.5017
Epoch 81: Train Loss 37.6574, Val Dist 13.5128
Epoch 82: Train Loss 37.6311, Val Dist 13.4953
Epoch 83: Train Loss 37.6667, Val Dist 13.4932
Epoch 84: Train Loss 37.6743, Val Dist 13.4935
Epoch 85: Train Loss 37.7147, Val Dist 13.5664
Epoch 86: Train Loss 37.6605, Val Dist 13.5112
Early Stopping
Fold 6 Finished. Best Valid Dist: 13.4795
[Fold 7] Seed fixed to 48

=== Fold 7/10 ===
Pre-rendering 13918 images (Cache Enabled)...

Caching Images: 100%|██████████| 13918/13918 [00:01<00:00, 13200.42it/s]

Pre-rendering 1510 images (Cache Enabled)...

Caching Images: 100%|██████████| 1510/1510 [00:00<00:00, 12672.32it/s]

Epoch 1: Train Loss 61.8560, Val Dist 20.5336
  -> Saved Best Model (Dist: 20.5336)
Epoch 2: Train Loss 48.4677, Val Dist 17.5416
  -> Saved Best Model (Dist: 17.5416)
Epoch 3: Train Loss 46.1771, Val Dist 16.6169
  -> Saved Best Model (Dist: 16.6169)
Epoch 4: Train Loss 44.8246, Val Dist 16.3207
  -> Saved Best Model (Dist: 16.3207)
Epoch 5: Train Loss 43.9439, Val Dist 16.0090
  -> Saved Best Model (Dist: 16.0090)
Epoch 6: Train Loss 43.1171, Val Dist 15.3176
  -> Saved Best Model (Dist: 15.3176)
Epoch 7: Train Loss 42.7086, Val Dist 15.1060
  -> Saved Best Model (Dist: 15.1060)
Epoch 8: Train Loss 42.1997, Val Dist 15.4407
Epoch 9: Train Loss 41.8080, Val Dist 14.5502
  -> Saved Best Model (Dist: 14.5502)
Epoch 10: Train Loss 41.5938, Val Dist 15.0666
Epoch 11: Train Loss 41.0875, Val Dist 14.7045
Epoch 12: Train Loss 41.1459, Val Dist 14.6538
Epoch 13: Train Loss 40.8673, Val Dist 14.5058
  -> Saved Best Model (Dist: 14.5058)
Epoch 14: Train Loss 40.6893, Val Dist 14.0333
  -> Saved Best Model (Dist: 14.0333)
Epoch 15: Train Loss 40.3638, Val Dist 14.6207
Epoch 16: Train Loss 40.2943, Val Dist 14.5381
Epoch 17: Train Loss 40.0111, Val Dist 14.0168
  -> Saved Best Model (Dist: 14.0168)
Epoch 18: Train Loss 39.9926, Val Dist 14.5267
Epoch 19: Train Loss 39.8072, Val Dist 14.8764
Epoch 20: Train Loss 39.7111, Val Dist 14.3090
Epoch 21: Train Loss 39.5426, Val Dist 13.8935
  -> Saved Best Model (Dist: 13.8935)
Epoch 22: Train Loss 39.4539, Val Dist 13.9992
Epoch 23: Train Loss 39.3324, Val Dist 14.3440
Epoch 24: Train Loss 39.2506, Val Dist 14.4147
Epoch 25: Train Loss 39.1706, Val Dist 13.8860
  -> Saved Best Model (Dist: 13.8860)
Epoch 26: Train Loss 39.0488, Val Dist 14.2453
Epoch 27: Train Loss 38.9312, Val Dist 14.0017
Epoch 28: Train Loss 38.8874, Val Dist 14.3200
Epoch 29: Train Loss 38.7151, Val Dist 14.0328
Epoch 30: Train Loss 38.3234, Val Dist 13.6478
  -> Saved Best Model (Dist: 13.6478)
Epoch 31: Train Loss 38.1161, Val Dist 13.7710
Epoch 32: Train Loss 38.0347, Val Dist 13.6583
Epoch 33: Train Loss 37.9305, Val Dist 13.7219
Epoch 34: Train Loss 37.8704, Val Dist 13.5819
  -> Saved Best Model (Dist: 13.5819)
Epoch 35: Train Loss 37.8209, Val Dist 13.9203
Epoch 36: Train Loss 37.8196, Val Dist 13.8701
Epoch 37: Train Loss 37.7448, Val Dist 13.8068
Epoch 38: Train Loss 37.6598, Val Dist 13.8092
Epoch 39: Train Loss 37.3858, Val Dist 13.6934
Epoch 40: Train Loss 37.2665, Val Dist 13.6246
Epoch 41: Train Loss 37.2482, Val Dist 13.6996
Epoch 42: Train Loss 37.1994, Val Dist 13.8323
Epoch 43: Train Loss 37.0656, Val Dist 13.7433
Epoch 44: Train Loss 36.9328, Val Dist 13.6703
Epoch 45: Train Loss 36.8824, Val Dist 13.5616
  -> Saved Best Model (Dist: 13.5616)
Epoch 46: Train Loss 36.8827, Val Dist 13.6491
Epoch 47: Train Loss 36.9150, Val Dist 13.7247
Epoch 48: Train Loss 36.8479, Val Dist 13.7359
Epoch 49: Train Loss 36.8125, Val Dist 13.7222
Epoch 50: Train Loss 36.7663, Val Dist 13.7165
Epoch 51: Train Loss 36.7259, Val Dist 13.7132
Epoch 52: Train Loss 36.7153, Val Dist 13.8306
Epoch 53: Train Loss 36.6670, Val Dist 13.6182
Epoch 54: Train Loss 36.6775, Val Dist 13.7204
Epoch 55: Train Loss 36.5955, Val Dist 13.7352
Epoch 56: Train Loss 36.6648, Val Dist 13.7479
Epoch 57: Train Loss 36.6528, Val Dist 13.8311
Epoch 58: Train Loss 36.6854, Val Dist 13.6899
Epoch 59: Train Loss 36.6747, Val Dist 13.6751
Epoch 60: Train Loss 36.5990, Val Dist 13.6726
Early Stopping
Fold 7 Finished. Best Valid Dist: 13.5616
[Fold 8] Seed fixed to 49

=== Fold 8/10 ===
Pre-rendering 13910 images (Cache Enabled)...

Caching Images: 100%|██████████| 13910/13910 [00:01<00:00, 13210.78it/s]

Pre-rendering 1518 images (Cache Enabled)...

Caching Images: 100%|██████████| 1518/1518 [00:00<00:00, 13033.68it/s]

Epoch 1: Train Loss 62.9919, Val Dist 18.3516
  -> Saved Best Model (Dist: 18.3516)
Epoch 2: Train Loss 49.1055, Val Dist 17.0022
  -> Saved Best Model (Dist: 17.0022)
Epoch 3: Train Loss 46.2453, Val Dist 15.9493
  -> Saved Best Model (Dist: 15.9493)
Epoch 4: Train Loss 44.8339, Val Dist 15.8245
  -> Saved Best Model (Dist: 15.8245)
Epoch 5: Train Loss 43.9846, Val Dist 15.5057
  -> Saved Best Model (Dist: 15.5057)
Epoch 6: Train Loss 43.2287, Val Dist 15.1084
  -> Saved Best Model (Dist: 15.1084)
Epoch 7: Train Loss 42.6766, Val Dist 15.3435
Epoch 8: Train Loss 42.2104, Val Dist 14.9002
  -> Saved Best Model (Dist: 14.9002)
Epoch 9: Train Loss 41.9265, Val Dist 14.6263
  -> Saved Best Model (Dist: 14.6263)
Epoch 10: Train Loss 41.5986, Val Dist 14.7182
Epoch 11: Train Loss 41.3246, Val Dist 14.2933
  -> Saved Best Model (Dist: 14.2933)
Epoch 12: Train Loss 40.9987, Val Dist 15.4509
Epoch 13: Train Loss 40.9098, Val Dist 14.5313
Epoch 14: Train Loss 40.7223, Val Dist 14.4307
Epoch 15: Train Loss 40.4894, Val Dist 14.2858
  -> Saved Best Model (Dist: 14.2858)
Epoch 16: Train Loss 40.3369, Val Dist 14.1969
  -> Saved Best Model (Dist: 14.1969)
Epoch 17: Train Loss 40.1253, Val Dist 14.1199
  -> Saved Best Model (Dist: 14.1199)
Epoch 18: Train Loss 39.9689, Val Dist 14.2608
Epoch 19: Train Loss 39.8717, Val Dist 14.2631
Epoch 20: Train Loss 39.7389, Val Dist 13.9389
  -> Saved Best Model (Dist: 13.9389)
Epoch 21: Train Loss 39.5657, Val Dist 13.7228
  -> Saved Best Model (Dist: 13.7228)
Epoch 22: Train Loss 39.5079, Val Dist 13.9673
Epoch 23: Train Loss 39.3431, Val Dist 14.0490
Epoch 24: Train Loss 39.2187, Val Dist 14.3369
Epoch 25: Train Loss 39.1652, Val Dist 13.9996
Epoch 26: Train Loss 38.6142, Val Dist 13.8145
Epoch 27: Train Loss 38.4694, Val Dist 13.6452
  -> Saved Best Model (Dist: 13.6452)
Epoch 28: Train Loss 38.3561, Val Dist 13.6462
Epoch 29: Train Loss 38.3328, Val Dist 13.6401
  -> Saved Best Model (Dist: 13.6401)
Epoch 30: Train Loss 38.2530, Val Dist 13.7064
Epoch 31: Train Loss 38.2161, Val Dist 13.9669
Epoch 32: Train Loss 38.1498, Val Dist 13.6995
Epoch 33: Train Loss 38.1493, Val Dist 13.8446
Epoch 34: Train Loss 37.8088, Val Dist 13.5112
  -> Saved Best Model (Dist: 13.5112)
Epoch 35: Train Loss 37.6394, Val Dist 13.5485
Epoch 36: Train Loss 37.5774, Val Dist 13.5874
Epoch 37: Train Loss 37.5654, Val Dist 13.6402
Epoch 38: Train Loss 37.6108, Val Dist 13.5836
Epoch 39: Train Loss 37.4154, Val Dist 13.5518
Epoch 40: Train Loss 37.2860, Val Dist 13.5883
Epoch 41: Train Loss 37.3408, Val Dist 13.5075
  -> Saved Best Model (Dist: 13.5075)
Epoch 42: Train Loss 37.3411, Val Dist 13.4743
  -> Saved Best Model (Dist: 13.4743)
Epoch 43: Train Loss 37.2769, Val Dist 13.4879
Epoch 44: Train Loss 37.3171, Val Dist 13.4758
Epoch 45: Train Loss 37.2412, Val Dist 13.4942
Epoch 46: Train Loss 37.1694, Val Dist 13.4965
Epoch 47: Train Loss 37.1442, Val Dist 13.4661
  -> Saved Best Model (Dist: 13.4661)
Epoch 48: Train Loss 37.0893, Val Dist 13.4608
  -> Saved Best Model (Dist: 13.4608)
Epoch 49: Train Loss 37.0982, Val Dist 13.5436
Epoch 50: Train Loss 37.0822, Val Dist 13.4673
Epoch 51: Train Loss 37.1126, Val Dist 13.4659
Epoch 52: Train Loss 37.0438, Val Dist 13.4882
Epoch 53: Train Loss 36.9871, Val Dist 13.5185
Epoch 54: Train Loss 37.0303, Val Dist 13.4718
Epoch 55: Train Loss 36.9787, Val Dist 13.4705
Epoch 56: Train Loss 37.0277, Val Dist 13.4519
  -> Saved Best Model (Dist: 13.4519)
Epoch 57: Train Loss 36.8644, Val Dist 13.4717
Epoch 58: Train Loss 37.0387, Val Dist 13.4841
Epoch 59: Train Loss 36.9666, Val Dist 13.4853
Epoch 60: Train Loss 36.9526, Val Dist 13.5011
Epoch 61: Train Loss 36.8974, Val Dist 13.4985
Epoch 62: Train Loss 36.9097, Val Dist 13.4962
Epoch 63: Train Loss 36.8665, Val Dist 13.4752
Epoch 64: Train Loss 36.9346, Val Dist 13.5093
Epoch 65: Train Loss 36.8750, Val Dist 13.5110
Epoch 66: Train Loss 36.9265, Val Dist 13.4892
Epoch 67: Train Loss 36.8596, Val Dist 13.5158
Epoch 68: Train Loss 36.9137, Val Dist 13.5124
Epoch 69: Train Loss 36.9072, Val Dist 13.4913
Epoch 70: Train Loss 36.8797, Val Dist 13.4919
Epoch 71: Train Loss 36.8752, Val Dist 13.4992
Early Stopping
Fold 8 Finished. Best Valid Dist: 13.4519
[Fold 9] Seed fixed to 50

=== Fold 9/10 ===
Pre-rendering 13828 images (Cache Enabled)...

Caching Images: 100%|██████████| 13828/13828 [00:01<00:00, 13065.33it/s]

Pre-rendering 1600 images (Cache Enabled)...

Caching Images: 100%|██████████| 1600/1600 [00:00<00:00, 13120.32it/s]

Epoch 1: Train Loss 62.3786, Val Dist 20.0246
  -> Saved Best Model (Dist: 20.0246)
Epoch 2: Train Loss 48.5787, Val Dist 18.2747
  -> Saved Best Model (Dist: 18.2747)
Epoch 3: Train Loss 45.9529, Val Dist 17.4680
  -> Saved Best Model (Dist: 17.4680)
Epoch 4: Train Loss 44.7546, Val Dist 16.4166
  -> Saved Best Model (Dist: 16.4166)
Epoch 5: Train Loss 43.8978, Val Dist 16.1957
  -> Saved Best Model (Dist: 16.1957)
Epoch 6: Train Loss 43.1706, Val Dist 15.9481
  -> Saved Best Model (Dist: 15.9481)
Epoch 7: Train Loss 42.5366, Val Dist 15.2530
  -> Saved Best Model (Dist: 15.2530)
Epoch 8: Train Loss 42.1998, Val Dist 15.3202
Epoch 9: Train Loss 41.8605, Val Dist 15.4219
Epoch 10: Train Loss 41.6160, Val Dist 15.4769
Epoch 11: Train Loss 41.2538, Val Dist 14.7449
  -> Saved Best Model (Dist: 14.7449)
Epoch 12: Train Loss 41.0054, Val Dist 14.8000
Epoch 13: Train Loss 40.9064, Val Dist 14.6936
  -> Saved Best Model (Dist: 14.6936)
Epoch 14: Train Loss 40.5695, Val Dist 14.5863
  -> Saved Best Model (Dist: 14.5863)
Epoch 15: Train Loss 40.3218, Val Dist 14.6322
Epoch 16: Train Loss 40.1463, Val Dist 14.8803
Epoch 17: Train Loss 39.9907, Val Dist 15.0931
Epoch 18: Train Loss 39.9118, Val Dist 14.9302
Epoch 19: Train Loss 39.3579, Val Dist 14.3359
  -> Saved Best Model (Dist: 14.3359)
Epoch 20: Train Loss 39.1904, Val Dist 14.4786
Epoch 21: Train Loss 39.1350, Val Dist 14.5823
Epoch 22: Train Loss 39.0258, Val Dist 14.2702
  -> Saved Best Model (Dist: 14.2702)
Epoch 23: Train Loss 38.9630, Val Dist 14.2668
  -> Saved Best Model (Dist: 14.2668)
Epoch 24: Train Loss 38.9164, Val Dist 14.3623
Epoch 25: Train Loss 38.7555, Val Dist 14.2913
Epoch 26: Train Loss 38.7919, Val Dist 14.2216
  -> Saved Best Model (Dist: 14.2216)
Epoch 27: Train Loss 38.6684, Val Dist 14.3825
Epoch 28: Train Loss 38.6107, Val Dist 14.3431
Epoch 29: Train Loss 38.5438, Val Dist 14.3119
Epoch 30: Train Loss 38.5180, Val Dist 14.3192
Epoch 31: Train Loss 38.2570, Val Dist 14.1112
  -> Saved Best Model (Dist: 14.1112)
Epoch 32: Train Loss 38.1453, Val Dist 14.1092
  -> Saved Best Model (Dist: 14.1092)
Epoch 33: Train Loss 38.0528, Val Dist 14.1084
  -> Saved Best Model (Dist: 14.1084)
Epoch 34: Train Loss 38.0374, Val Dist 14.2357
Epoch 35: Train Loss 37.9552, Val Dist 14.1623
Epoch 36: Train Loss 37.9335, Val Dist 14.1074
  -> Saved Best Model (Dist: 14.1074)
Epoch 37: Train Loss 37.8935, Val Dist 14.1611
Epoch 38: Train Loss 37.9063, Val Dist 14.0871
  -> Saved Best Model (Dist: 14.0871)
Epoch 39: Train Loss 37.8643, Val Dist 14.1853
Epoch 40: Train Loss 37.8466, Val Dist 14.2083
Epoch 41: Train Loss 37.7414, Val Dist 14.0841
  -> Saved Best Model (Dist: 14.0841)
Epoch 42: Train Loss 37.6449, Val Dist 14.1327
Epoch 43: Train Loss 37.6849, Val Dist 14.9217
Epoch 44: Train Loss 37.5978, Val Dist 14.1535
Epoch 45: Train Loss 37.6106, Val Dist 14.3196
Epoch 46: Train Loss 37.4332, Val Dist 14.2090
Epoch 47: Train Loss 37.4425, Val Dist 14.1039
Epoch 48: Train Loss 37.3474, Val Dist 14.1661
Epoch 49: Train Loss 37.3310, Val Dist 14.0480
  -> Saved Best Model (Dist: 14.0480)
Epoch 50: Train Loss 37.2529, Val Dist 14.1519
Epoch 51: Train Loss 37.3163, Val Dist 14.0671
Epoch 52: Train Loss 37.2834, Val Dist 14.1039
Epoch 53: Train Loss 37.2844, Val Dist 14.1342
Epoch 54: Train Loss 37.1723, Val Dist 14.1334
Epoch 55: Train Loss 37.2118, Val Dist 14.0775
Epoch 56: Train Loss 37.1730, Val Dist 14.0995
Epoch 57: Train Loss 37.1473, Val Dist 14.0966
Epoch 58: Train Loss 37.0714, Val Dist 14.1280
Epoch 59: Train Loss 37.0256, Val Dist 14.0956
Epoch 60: Train Loss 37.0443, Val Dist 14.1544
Epoch 61: Train Loss 36.9964, Val Dist 14.0974
Epoch 62: Train Loss 36.9798, Val Dist 14.0898
Epoch 63: Train Loss 37.0274, Val Dist 14.1049
Epoch 64: Train Loss 36.9880, Val Dist 14.0965
Early Stopping
Fold 9 Finished. Best Valid Dist: 14.0480
[Fold 10] Seed fixed to 51

=== Fold 10/10 ===
Pre-rendering 13858 images (Cache Enabled)...

Caching Images: 100%|██████████| 13858/13858 [00:01<00:00, 12165.49it/s]

Pre-rendering 1570 images (Cache Enabled)...

Caching Images: 100%|██████████| 1570/1570 [00:00<00:00, 11533.41it/s]

Epoch 1: Train Loss 63.8255, Val Dist 20.0143
  -> Saved Best Model (Dist: 20.0143)
Epoch 2: Train Loss 48.9091, Val Dist 20.4999
Epoch 3: Train Loss 46.7099, Val Dist 16.5725
  -> Saved Best Model (Dist: 16.5725)
Epoch 4: Train Loss 44.9789, Val Dist 16.3499
  -> Saved Best Model (Dist: 16.3499)
Epoch 5: Train Loss 43.9715, Val Dist 15.5410
  -> Saved Best Model (Dist: 15.5410)
Epoch 6: Train Loss 43.1160, Val Dist 15.6383
Epoch 7: Train Loss 42.6044, Val Dist 15.5528
Epoch 8: Train Loss 42.2912, Val Dist 15.6191
Epoch 9: Train Loss 41.8790, Val Dist 14.9697
  -> Saved Best Model (Dist: 14.9697)
Epoch 10: Train Loss 41.5893, Val Dist 15.8647
Epoch 11: Train Loss 41.1334, Val Dist 14.4626
  -> Saved Best Model (Dist: 14.4626)
Epoch 12: Train Loss 40.9848, Val Dist 14.3685
  -> Saved Best Model (Dist: 14.3685)
Epoch 13: Train Loss 40.7242, Val Dist 14.7722
Epoch 14: Train Loss 40.4332, Val Dist 14.5370
Epoch 15: Train Loss 40.3339, Val Dist 14.4247
Epoch 16: Train Loss 40.1003, Val Dist 14.6282
Epoch 17: Train Loss 39.5404, Val Dist 14.2352
  -> Saved Best Model (Dist: 14.2352)
Epoch 18: Train Loss 39.3049, Val Dist 14.1668
  -> Saved Best Model (Dist: 14.1668)
Epoch 19: Train Loss 39.2778, Val Dist 14.0390
  -> Saved Best Model (Dist: 14.0390)
Epoch 20: Train Loss 39.1651, Val Dist 14.1831
Epoch 21: Train Loss 39.0664, Val Dist 13.9277
  -> Saved Best Model (Dist: 13.9277)
Epoch 22: Train Loss 38.9589, Val Dist 14.0243
Epoch 23: Train Loss 38.8842, Val Dist 14.0320
Epoch 24: Train Loss 38.8081, Val Dist 14.1482
Epoch 25: Train Loss 38.7615, Val Dist 14.2325
Epoch 26: Train Loss 38.4318, Val Dist 13.9387
Epoch 27: Train Loss 38.3567, Val Dist 13.9787
Epoch 28: Train Loss 38.2339, Val Dist 13.9833
Epoch 29: Train Loss 38.1784, Val Dist 14.1305
Epoch 30: Train Loss 38.0992, Val Dist 13.9886
Epoch 31: Train Loss 37.9782, Val Dist 13.9146
  -> Saved Best Model (Dist: 13.9146)
Epoch 32: Train Loss 37.9684, Val Dist 13.8210
  -> Saved Best Model (Dist: 13.8210)
Epoch 33: Train Loss 37.9009, Val Dist 13.8207
  -> Saved Best Model (Dist: 13.8207)
Epoch 34: Train Loss 37.9481, Val Dist 13.8567
Epoch 35: Train Loss 37.8949, Val Dist 13.8539
Epoch 36: Train Loss 37.7794, Val Dist 13.8490
Epoch 37: Train Loss 37.8218, Val Dist 13.8196
  -> Saved Best Model (Dist: 13.8196)
Epoch 38: Train Loss 37.6643, Val Dist 13.8053
  -> Saved Best Model (Dist: 13.8053)
Epoch 39: Train Loss 37.7596, Val Dist 13.8100
Epoch 40: Train Loss 37.6685, Val Dist 13.8077
Epoch 41: Train Loss 37.6576, Val Dist 13.7676
  -> Saved Best Model (Dist: 13.7676)
Epoch 42: Train Loss 37.6271, Val Dist 13.7987
Epoch 43: Train Loss 37.6177, Val Dist 13.8828
Epoch 44: Train Loss 37.5978, Val Dist 13.8430
Epoch 45: Train Loss 37.5605, Val Dist 13.7802
Epoch 46: Train Loss 37.5731, Val Dist 13.8182
Epoch 47: Train Loss 37.5258, Val Dist 13.8353
Epoch 48: Train Loss 37.5199, Val Dist 13.8319
Epoch 49: Train Loss 37.4879, Val Dist 13.8048
Epoch 50: Train Loss 37.4613, Val Dist 13.7873
Epoch 51: Train Loss 37.4836, Val Dist 13.7992
Epoch 52: Train Loss 37.4575, Val Dist 13.7858
Epoch 53: Train Loss 37.4732, Val Dist 13.8192
Epoch 54: Train Loss 37.3912, Val Dist 13.8166
Epoch 55: Train Loss 37.5083, Val Dist 13.8644
Epoch 56: Train Loss 37.4253, Val Dist 13.7994
Early Stopping
Fold 10 Finished. Best Valid Dist: 13.7676
Average Score: 13.6454

## 5. 추론 (Inference)

In [9]:
import os
import joblib
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import cv2
from tqdm import tqdm
from src.models_multimodal_v8_team import MultiModalNetV8Team

os.makedirs("submission_multimodal", exist_ok=True)

# =========================
# Test Dataset
# =========================
class TestMultiModalDataset(Dataset):
    def __init__(self, submission_df, preprocessor, img_size=(68, 105)):
        self.submission_df = submission_df
        self.preprocessor = preprocessor
        self.H, self.W = img_size

    def __len__(self):
        return len(self.submission_df)

    def _generate_image(self, cont_data):
        img_np = np.zeros((2, self.H, self.W), dtype=np.float32)
        if len(cont_data) == 0:
            return torch.tensor(img_np, dtype=torch.float32)

        seq_len = cont_data.shape[0]
        xs = cont_data[:, 0]
        ys = cont_data[:, 1]

        x_idxs = (xs * (self.W - 1)).round().astype(int).clip(0, self.W - 1)
        y_idxs = (ys * (self.H - 1)).round().astype(int).clip(0, self.H - 1)

        for t in range(seq_len):
            px, py = x_idxs[t], y_idxs[t]
            img_np[0, py, px] = 1.0
            decay_val = (t + 1) / seq_len
            if t > 0:
                prev_px, prev_py = x_idxs[t-1], y_idxs[t-1]
                cv2.line(img_np[1], (prev_px, prev_py), (px, py), color=decay_val, thickness=1)
            else:
                img_np[1, py, px] = decay_val

        return torch.tensor(img_np, dtype=torch.float32)

    def __getitem__(self, idx):
        row = self.submission_df.iloc[idx]
        raw_path = row['path']
        path = raw_path[2:] if raw_path.startswith("./") else raw_path

        df = pd.read_csv(path)
        episodes = self.preprocessor.transform(df, is_train=False)

        if len(episodes) == 0:
            input_dim = self.preprocessor.get_input_dim()
            cont = torch.zeros((1, input_dim), dtype=torch.float32)
            # Use Unknown indices (3 features: type, result, team)
            unk_type = self.preprocessor.type_encoder.transform(["Unknown"])[0]
            unk_result = self.preprocessor.result_encoder.transform(["Unknown"])[0]
            unk_team = self.preprocessor.team_encoder.transform(["Unknown"])[0]
            cat = torch.tensor([[unk_type, unk_result, unk_team]], dtype=torch.long)
            img = torch.zeros((2, self.H, self.W), dtype=torch.float32)
            return img, cont, cat

        ep = episodes[0]
        cont = torch.tensor(ep['cont'], dtype=torch.float32)
        cat = torch.tensor(ep['cat'], dtype=torch.long)
        img = self._generate_image(ep['cont'])

        return img, cont, cat

def test_mm_collate_fn(batch):
    imgs, conts, cats = zip(*batch)
    imgs_batched = torch.stack(imgs, dim=0)
    lengths = torch.tensor([len(c) for c in conts], dtype=torch.long)
    conts_padded = pad_sequence(conts, batch_first=True)
    cats_padded = pad_sequence(cats, batch_first=True)
    return imgs_batched, conts_padded, cats_padded, lengths

# =========================
# Load Submission Meta
# =========================
submission = pd.read_csv("sample_submission.csv")
test_meta = pd.read_csv("test.csv")
submission = submission.merge(test_meta, on="game_episode", how="left")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")

# =========================
# 10-Fold Inference with CORRECTED TTA
# =========================
NUM_FOLDS = 10
all_fold_preds = []

for fold in range(1, NUM_FOLDS + 1):
    print(f"\n=== Inference Fold {fold} with Corrected TTA ===")

    # 1. Load preprocessor
    preprocessor = joblib.load(f"models/preprocessor_v8_team_h96_{fold}.pkl")

    # 2. Dataset / Loader
    test_dataset = TestMultiModalDataset(submission, preprocessor)
    test_loader = DataLoader(
        test_dataset,
        batch_size=128,
        shuffle=False,
        collate_fn=test_mm_collate_fn
    )

    # 3. Load model
    input_dim_cont = preprocessor.get_input_dim()
    num_types, num_results, num_teams = preprocessor.get_num_classes()
    print(f"Model Dimensions: input={input_dim_cont}, types={num_types}, results={num_results}, teams={num_teams}")

    model = MultiModalNetV8Team(input_dim_cont, num_types, num_results, num_teams).to(DEVICE)
    model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))
    model.eval()

    fold_preds = []

    # 4. Inference with CORRECTED TTA
    with torch.no_grad():
        for imgs, cont, cat, lengths in tqdm(test_loader, desc=f"Fold {fold}"):
            imgs, cont, cat, lengths = (
                imgs.to(DEVICE),
                cont.to(DEVICE),
                cat.to(DEVICE),
                lengths.to(DEVICE),
            )

            # -------------------------
            # (1) 원본 예측
            # -------------------------
            pred1, _ = model(imgs, cont, cat, lengths)

            # -------------------------
            # (2) Y-Flip TTA 예측 (CORRECTED!)
            # -------------------------
            imgs_f = torch.flip(imgs, dims=[2])  # Y-axis flip

            # ✅ CORRECTED: Raw → Flip → Scale
            scaler = preprocessor.scaler
            mean = torch.tensor(scaler.mean_, device=cont.device, dtype=cont.dtype)
            std = torch.tensor(scaler.scale_, device=cont.device, dtype=cont.dtype)

            # Step 1: z-score → raw(norm)
            cont_raw = cont * std + mean

            # Step 2: Y-Flip in raw space
            cont_raw[:, :, 1] = 1.0 - cont_raw[:, :, 1]  # start_y_norm
            cont_raw[:, :, 3] = 1.0 - cont_raw[:, :, 3]  # end_y_prev_norm
            cont_raw[:, :, 5] = -cont_raw[:, :, 5]       # dy_prev_norm

            # Step 3: raw → z-score
            cont_f = (cont_raw - mean) / std

            pred2, _ = model(imgs_f, cont_f, cat, lengths)

            # 예측값 다시 flip
            pred2[:, 1] = 1.0 - pred2[:, 1]

            # -------------------------
            # (3) 평균
            # -------------------------
            pred = 0.5 * (pred1 + pred2)

            pred_np = pred.cpu().numpy()
            pred_np[:, 0] *= 105.0
            pred_np[:, 1] *= 68.0
            fold_preds.append(pred_np)

    fold_preds = np.vstack(fold_preds)
    all_fold_preds.append(fold_preds)

# =========================
# Ensemble (Mean)
# =========================
final_preds = np.mean(all_fold_preds, axis=0)

submission["end_x"] = final_preds[:, 0].clip(0, 105)
submission["end_y"] = final_preds[:, 1].clip(0, 68)

submission[["game_episode", "end_x", "end_y"]].to_csv(
    "submission_multimodal/multimodal_v8_team_h96_tta_corrected.csv", index=False
)

print("\n✅ Saved: submission_multimodal/multimodal_v8_team_h96_tta_corrected.csv")
print("📊 TTA Fix Applied: Raw → Flip → Scale")

C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

Device: cuda

=== Inference Fold 1 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 1: 100%|██████████| 19/19 [01:20<00:00,  4.22s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 2 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 2: 100%|██████████| 19/19 [00:53<00:00,  2.83s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 3 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 3: 100%|██████████| 19/19 [00:51<00:00,  2.72s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 4 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 4: 100%|██████████| 19/19 [00:51<00:00,  2.71s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 5 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 5: 100%|██████████| 19/19 [00:53<00:00,  2.80s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 6 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 6: 100%|██████████| 19/19 [00:52<00:00,  2.74s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 7 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 7: 100%|██████████| 19/19 [00:53<00:00,  2.83s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 8 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 8: 100%|██████████| 19/19 [00:51<00:00,  2.73s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 9 with Corrected TTA ===
Model Dimensions: input=10, types=26, results=20, teams=13

Fold 9: 100%|██████████| 19/19 [00:52<00:00,  2.76s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_102520\1005457692.py:121: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v8_team_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 10 with Corrected TTA ===
Model Dimensions: input=10, types=27, results=21, teams=13

Fold 10: 100%|██████████| 19/19 [00:51<00:00,  2.69s/it]

✅ Saved: submission_multimodal/multimodal_v8_team_h96_tta_corrected.csv
📊 TTA Fix Applied: Raw → Flip → Scale

In [12]:
import pandas as pd
import os

os.makedirs("submission_ensemble", exist_ok=True)

h96 = pd.read_csv("submission_multimodal/multimodal_v7_h96_tta_corrected.csv")
polar = pd.read_csv("submission_polar_h96_optimized.csv")
team_h96 = pd.read_csv("submission_multimodal/multimodal_v8_team_h96_tta_corrected.csv")

# map (순서 유지)
polar_map = polar.set_index("game_episode")[["end_x","end_y"]]
team_map = team_h96.set_index("game_episode")[["end_x","end_y"]]

px = h96["game_episode"].map(polar_map["end_x"])
py = h96["game_episode"].map(polar_map["end_y"])
tx = h96["game_episode"].map(team_map["end_x"])
ty = h96["game_episode"].map(team_map["end_y"])

# weights
w_team = 0.05  # 0.10도 한 번만 실험
w_h96 = 0.6 * (1 - w_team)
w_polar = 0.4 * (1 - w_team)

out = h96.copy()
out["end_x"] = w_h96*h96["end_x"] + w_polar*px + w_team*tx
out["end_y"] = w_h96*h96["end_y"] + w_polar*py + w_team*ty

out["end_x"] = out["end_x"].clip(0, 105.0)
out["end_y"] = out["end_y"].clip(0, 68.0)

path = "submission_ensemble/ens_h96_polar_teamh96_05.csv"
out.to_csv(path, index=False)
print("saved:", path)

display(out.head())

saved: submission_ensemble/ens_h96_polar_teamh96_05.csv

  game_episode      end_x      end_y
0     153363_1  65.353189  11.358270
1     153363_2  27.275434  50.600202
2     153363_6  30.289655  62.947516
3     153363_7  52.675758   6.015957
4     153363_8  81.028175   8.725982

In [13]:
import pandas as pd
import os

os.makedirs("submission_ensemble", exist_ok=True)

h96 = pd.read_csv("submission_multimodal/multimodal_v7_h96_tta_corrected.csv")
polar = pd.read_csv("submission_polar_h96_optimized.csv")
team_h96 = pd.read_csv("submission_multimodal/multimodal_v8_team_h96_tta_corrected.csv")

# map (순서 유지)
polar_map = polar.set_index("game_episode")[["end_x","end_y"]]
team_map = team_h96.set_index("game_episode")[["end_x","end_y"]]

px = h96["game_episode"].map(polar_map["end_x"])
py = h96["game_episode"].map(polar_map["end_y"])
tx = h96["game_episode"].map(team_map["end_x"])
ty = h96["game_episode"].map(team_map["end_y"])

# weights
w_team = 0.1  # 0.10도 한 번만 실험
w_h96 = 0.6 * (1 - w_team)
w_polar = 0.4 * (1 - w_team)

out = h96.copy()
out["end_x"] = w_h96*h96["end_x"] + w_polar*px + w_team*tx
out["end_y"] = w_h96*h96["end_y"] + w_polar*py + w_team*ty

out["end_x"] = out["end_x"].clip(0, 105.0)
out["end_y"] = out["end_y"].clip(0, 68.0)

path = "submission_ensemble/ens_h96_polar_teamh96_10.csv"
out.to_csv(path, index=False)
print("saved:", path)

display(out.head())

saved: submission_ensemble/ens_h96_polar_teamh96_10.csv

  game_episode      end_x      end_y
0     153363_1  65.277999  11.306762
1     153363_2  27.239527  50.755751
2     153363_6  30.347696  63.039867
3     153363_7  52.773866   5.919607
4     153363_8  81.017477   8.717041

In [15]:
result_v7_foldseed_h96_tta_corrected = pd.read_csv("submission_multimodal/multimodal_v7_h96_tta_corrected.csv")
display(result_v7_foldseed_h96_tta_corrected.head())

result_v8_team_h96_tta_corrected = pd.read_csv("submission_multimodal/multimodal_v8_team_h96_tta_corrected.csv")
display(result_v8_team_h96_tta_corrected.head())

result_v7_h96_polar = pd.read_csv("submission_polar_h96_optimized.csv")
display(result_v7_h96_polar.head())

result_v7_h96_polar = pd.read_csv("submission_ensemble/ens_h9660_polar40.csv")
display(result_v7_h96_polar.head())

result_ens_h96_polar_team05 = pd.read_csv("submission_ensemble/ens_h96_polar_teamh96_05.csv")
display(result_ens_h96_polar_team05.head())

result_ens_h96_polar_team10 = pd.read_csv("submission_ensemble/ens_h96_polar_teamh96_10.csv")
display(result_ens_h96_polar_team10.head())

  game_episode      end_x      end_y
0     153363_1  63.744760  10.535255
1     153363_2  25.247570  50.701256
2     153363_6  26.461975  63.656200
3     153363_7  53.256310   4.663423
4     153363_8  81.452260   8.473086

  game_episode      end_x      end_y
0     153363_1  63.924590  10.379606
1     153363_2  26.593204  53.555634
2     153363_6  31.392430  64.702194
3     153363_7  54.539806   4.185305
4     153363_8  80.824910   8.556105

  game_episode      end_x      end_y
0     153363_1  67.953806  12.721565
1     153363_2  30.406996  50.059748
2     153363_6  35.886074  61.653611
3     153363_7  51.559660   8.285633
4     153363_8  80.418792   9.127678

  game_episode      end_x      end_y
0     153363_1  65.428378  11.409779
1     153363_2  27.311340  50.444653
2     153363_6  30.231615  62.855164
3     153363_7  52.577650   6.112307
4     153363_8  81.038873   8.734923

  game_episode      end_x      end_y
0     153363_1  65.353189  11.358270
1     153363_2  27.275434  50.600202
2     153363_6  30.289655  62.947516
3     153363_7  52.675758   6.015957
4     153363_8  81.028175   8.725982

  game_episode      end_x      end_y
0     153363_1  65.277999  11.306762
1     153363_2  27.239527  50.755751
2     153363_6  30.347696  63.039867
3     153363_7  52.773866   5.919607
4     153363_8  81.017477   8.717041

In [22]:
result_v7_foldseed_h96_tta_corrected = pd.read_csv("submission_multimodal/multimodal_v7_h96_tta_corrected.csv")
display(result_v7_foldseed_h96_tta_corrected.head(10))

result_Final_env_v2_3 = pd.read_csv("submission_multimodal/Final_env_v2_4.csv")
display(result_Final_env_v2_3.head(10))

result_v7_h96_polar = pd.read_csv("submission_polar_h96_optimized.csv")
display(result_v7_h96_polar.head(10))

result_v7_h96_polar = pd.read_csv("submission_ensemble/ens_h9660_polar40.csv")
display(result_v7_h96_polar.head(10))

  game_episode      end_x      end_y
0     153363_1  63.744760  10.535255
1     153363_2  25.247570  50.701256
2     153363_6  26.461975  63.656200
3     153363_7  53.256310   4.663423
4     153363_8  81.452260   8.473086
5     153363_9  73.318080  66.097336
6    153363_10  65.394610   6.111311
7    153363_12  70.400880   5.978782
8    153363_13  31.906475  64.938890
9    153363_15  70.288500   9.383939

  game_episode      end_x      end_y
0     153363_1  63.371765  12.353533
1     153363_2  25.322931  44.783375
2     153363_6  32.662900  63.261932
3     153363_7  55.991160   5.556868
4     153363_8  80.957960   8.612200
5     153363_9  72.582650  66.721050
6    153363_10  65.979020   7.507459
7    153363_12  70.334206   6.224345
8    153363_13  32.420254  65.724540
9    153363_15  70.136340  11.219527

  game_episode      end_x      end_y
0     153363_1  67.953806  12.721565
1     153363_2  30.406996  50.059748
2     153363_6  35.886074  61.653611
3     153363_7  51.559660   8.285633
4     153363_8  80.418792   9.127678
5     153363_9  76.223418  66.012002
6    153363_10  64.185196   7.951764
7    153363_12  76.645691   8.798978
8    153363_13  32.859031  63.211951
9    153363_15  74.895893  13.939054

  game_episode      end_x      end_y
0     153363_1  65.428378  11.409779
1     153363_2  27.311340  50.444653
2     153363_6  30.231615  62.855164
3     153363_7  52.577650   6.112307
4     153363_8  81.038873   8.734923
5     153363_9  74.480215  66.063202
6    153363_10  64.910844   6.847492
7    153363_12  72.898804   7.106860
8    153363_13  32.287497  64.248114
9    153363_15  72.131457  11.205985

In [7]:
import os
import pandas as pd

# =========================
# output folder
# =========================
os.makedirs("submission_ensemble", exist_ok=True)

# =========================
# load
# =========================
h96 = pd.read_csv("submission_multimodal/multimodal_v7_h96_tta_corrected.csv")
polar = pd.read_csv("submission_polar_h96_optimized.csv")
env = pd.read_csv("submission_multimodal/Final_env_v2_4_last.csv")

# =========================
# mapping (순서 유지)
# =========================
polar_map = polar.set_index("game_episode")[["end_x", "end_y"]]
env_map = env.set_index("game_episode")[["end_x", "end_y"]]

px = h96["game_episode"].map(polar_map["end_x"])
py = h96["game_episode"].map(polar_map["end_y"])
ex = h96["game_episode"].map(env_map["end_x"])
ey = h96["game_episode"].map(env_map["end_y"])

FIELD_X, FIELD_Y = 105.0, 68.0

# =========================
# ensemble helper
# =========================
def make_submission(name, w_h96, w_polar, w_env):
    out = h96.copy()
    out["end_x"] = w_h96 * h96["end_x"] + w_polar * px + w_env * ex
    out["end_y"] = w_h96 * h96["end_y"] + w_polar * py + w_env * ey

    out["end_x"] = out["end_x"].clip(0, FIELD_X)
    out["end_y"] = out["end_y"].clip(0, FIELD_Y)

    path = f"submission_ensemble/{name}.csv"
    out.to_csv(path, index=False)
    print(f"saved: {path} | weights = (h96={w_h96}, polar={w_polar}, env={w_env})")

# =========================
# generate submissions
# =========================
# make_submission("ens_h96_60_polar_30_env_10", 0.6, 0.3, 0.1)
# make_submission("ens_h96_60_polar_20_env_20", 0.6, 0.2, 0.2)
# make_submission("ens_h96_60_polar_10_env_30", 0.6, 0.1, 0.3)
# make_submission("ens_h96_40_polar_30_env_30", 0.4, 0.3, 0.3)
# make_submission("ens_h96_70_polar_20_env_10", 0.7, 0.2, 0.1)
# make_submission("ensemble_last", 0.35, 0.3, 0.35)
make_submission("ensemble_final", 0.5, 0.0, 0.5)


# 참고용 (올인)
# make_submission("ens_h96_60_env_40", 0.6, 0.0, 0.4)

saved: submission_ensemble/ensemble_final.csv | weights = (h96=0.5, polar=0.0, env=0.5)

In [8]:
import pandas as pd

files = [
    "ens_h96_60_polar_30_env_10.csv",
    "ensemble_last.csv",
    "ensemble_final.csv",
    "ens_h96_70_polar_20_env_10.csv",
    "ens_h96_60_polar_20_env_20.csv",
    "ens_h96_60_polar_10_env_30.csv",
    "ens_h96_40_polar_30_env_30.csv",
    
    "ens_h96_60_env_40.csv",
]

for f in files:
    print(f"\n=== {f} ===")
    display(pd.read_csv(f"submission_ensemble/{f}").head(10))

=== ens_h96_60_polar_30_env_10.csv ===

  game_episode      end_x      end_y
0     153363_1  64.970174  11.372976
1     153363_2  26.802934  49.917016
2     153363_6  29.909297  63.015996
3     153363_7  53.020800   5.839430
4     153363_8  81.092790   8.683375
5     153363_9  74.116138  66.134107
6    153363_10  65.090227   6.803061
7    153363_12  72.267656   6.849397
8    153363_13  32.243620  64.499373
9    153363_15  71.655502  10.934032

=== ensemble_last.csv ===

  game_episode      end_x      end_y
0     153363_1  64.449568  11.824238
1     153363_2  26.232012  49.900132
2     153363_6  31.087546  62.984044
3     153363_7  54.808754   6.294260
4     153363_8  80.698590   8.555894
5     153363_9  73.995906  66.458638
6    153363_10  66.273285   7.458243
7    153363_12  72.119154   6.584272
8    153363_13  32.897923  64.489807
9    153363_15  71.962726  11.100782

=== ensemble_final.csv ===

  game_episode      end_x      end_y
0     153363_1  62.947752  11.439669
1     153363_2  24.442733  49.831724
2     153363_6  29.031035  63.554230
3     153363_7  56.201223   5.440814
4     153363_8  80.818503   8.310844
5     153363_9  73.041258  66.650053
6    153363_10  67.168180   7.246734
7    153363_12  70.179210   5.635112
8    153363_13  32.914591  65.037460
9    153363_15  70.705655   9.884379

=== ens_h96_70_polar_20_env_10.csv ===

  game_episode      end_x      end_y
0     153363_1  64.549270  11.154345
1     153363_2  26.286991  49.981166
2     153363_6  28.966887  63.216255
3     153363_7  53.190465   5.477209
4     153363_8  81.196136   8.617916
5     153363_9  73.825605  66.142641
6    153363_10  65.211168   6.619016
7    153363_12  71.643175   6.567377
8    153363_13  32.148364  64.672067
9    153363_15  71.194763  10.478521

=== ens_h96_60_polar_20_env_20.csv ===

  game_episode      end_x      end_y
0     153363_1  64.511970  11.336173
1     153363_2  26.294527  49.389378
2     153363_6  29.586980  63.176829
3     153363_7  53.463950   5.566554
4     153363_8  81.146706   8.631827
5     153363_9  73.752062  66.205012
6    153363_10  65.269609   6.758631
7    153363_12  71.636507   6.591934
8    153363_13  32.199742  64.750632
9    153363_15  71.179547  10.662080

=== ens_h96_60_polar_10_env_30.csv ===

  game_episode      end_x      end_y
0     153363_1  64.053766  11.299369
1     153363_2  25.786121  48.861741
2     153363_6  29.264662  63.337661
3     153363_7  53.907100   5.293677
4     153363_8  81.200623   8.580279
5     153363_9  73.387985  66.275917
6    153363_10  65.448992   6.714200
7    153363_12  71.005359   6.334470
8    153363_13  32.155864  65.001891
9    153363_15  70.703591  10.390127

=== ens_h96_40_polar_30_env_30.csv ===

  game_episode      end_x      end_y
0     153363_1  64.895575  11.736631
1     153363_2  26.818006  48.733439
2     153363_6  31.149482  62.937143
3     153363_7  53.567770   6.018119
4     153363_8  80.993930   8.711198
5     153363_9  73.969052  66.258850
6    153363_10  65.207109   7.082291
7    153363_12  72.254321   6.898510
8    153363_13  32.346376  64.656503
9    153363_15  71.625070  11.301150

=== ens_h96_60_env_40.csv ===

  game_episode      end_x      end_y
0     153363_1  63.595562  11.262566
1     153363_2  25.277714  48.334104
2     153363_6  28.942345  63.498493
3     153363_7  54.350250   5.020801
4     153363_8  81.254540   8.528732
5     153363_9  73.023908  66.346822
6    153363_10  65.628374   6.669770
7    153363_12  70.374210   6.077007
8    153363_13  32.111987  65.253150
9    153363_15  70.227636  10.118174