# Multi-modal Model V7 - Polar Coordinate Regression (H96)

이 노트북은 기존 H96 모델의 좌표 직접 회귀 방식을 **Polar Coordinate (거리 + 방향) 분해** 방식으로 변경합니다.

## 주요 변경 사항

1.  **Polar Coordinate Target**:
    - 기존: `(end_x, end_y)` 직접 예측
    - 변경: `(distance, sin_theta, cos_theta)` 예측 후 좌표 복원
2.  **Model Output**:
    - Distance Head: Softplus 활성화 (거리는 양수)
    - Direction Head: Tanh 활성화 (sin/cos는 [-1, 1])
3.  **Loss Function**:
    - Distance: Huber Loss (robust to outliers)
    - Direction: Cosine Similarity Loss
4.  **No Data Leakage**:
    - Polar 라벨은 train에서만 생성
    - Test에서는 start 좌표만 사용

## 왜 성능이 개선될 수 있는가?

- **물리적 해석**: 패스는 본질적으로 "얼마나 멀리, 어느 방향"으로 표현하는 것이 자연스러움
- **각도 불연속 제거**: (sin θ, cos θ) 사용으로 -π/π 경계 문제 해결
- **독립적 Loss**: 거리와 방향에 각각 최적화된 loss 적용

In [1]:
import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence, pad_sequence
from sklearn.model_selection import GroupKFold
import cv2  # OpenCV Import
from tqdm import tqdm
import joblib

# [Polar] Use Polar Preprocessor
from src.preprocessing_polar import FootballPreprocessorPolar

# Fold-specific Seeds for Diversity
FOLD_SEEDS = {
    1: 42,
    2: 43,
    3: 44,
    4: 45,
    5: 46,
    6: 47,
    7: 48,
    8: 49,
    9: 50,
    10: 51,
}

# Set Seed
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {DEVICE}")

Device: cuda

## 1. 데이터 로드 및 전처리 (Preprocessing V2.5)

## 2. 이미지 생성 및 증강 (Random Y-Flip)

In [2]:
# Load Raw Training Data
train_df = pd.read_csv("train.csv")
print(f"Loaded {len(train_df)} rows")

Loaded 356721 rows

## 3. 모델 아키텍처 (GRU 적용)

In [3]:
# [FIXED] Dataset Class Definition
class MultiModalDataset(Dataset):
    def __init__(self, episodes, img_size=(68, 105), augment=False, cache_images=True):
        self.episodes = episodes
        self.H, self.W = img_size
        self.augment = augment
        self.cache_images = cache_images
        self.img_cache = None
        
        if self.cache_images:
            print(f"Pre-rendering {len(episodes)} images (Cache Enabled)...")
            self.img_cache = [self._generate_image(ep['cont']) for ep in tqdm(episodes, desc="Caching Images")]

    def __len__(self):
        return len(self.episodes)

    def _generate_image(self, cont_data):
        img_np = np.zeros((2, self.H, self.W), dtype=np.float32)
        if len(cont_data) == 0:
             return torch.tensor(img_np, dtype=torch.float32)

        seq_len = cont_data.shape[0]
        xs = cont_data[:, 0]
        ys = cont_data[:, 1]
        
        x_idxs = (xs * (self.W - 1)).round().astype(int).clip(0, self.W - 1)
        y_idxs = (ys * (self.H - 1)).round().astype(int).clip(0, self.H - 1)
        
        for t in range(seq_len):
            px, py = x_idxs[t], y_idxs[t]
            img_np[0, py, px] = 1.0
            decay_val = (t + 1) / seq_len
            if t > 0:
                prev_px, prev_py = x_idxs[t-1], y_idxs[t-1]
                cv2.line(img_np[1], (prev_px, prev_py), (px, py), color=decay_val, thickness=1)
            else:
                img_np[1, py, px] = decay_val
        return torch.tensor(img_np, dtype=torch.float32)

    def __getitem__(self, idx):
        data = self.episodes[idx]
        
        cont = data['cont'].copy()
        target = data['target'].copy()
        target_polar = data['target_polar'].copy() # [d_norm, sin, cos]
        
        if self.augment and random.random() < 0.5:
            cont[:, 1] = 1.0 - cont[:, 1] # start_y
            cont[:, 3] = 1.0 - cont[:, 3] # end_y_prev
            cont[:, 5] = -cont[:, 5]      # dy_prev 
            target[1] = 1.0 - target[1]
            target_polar[1] = -target_polar[1] # sin -> -sin
            
            if self.cache_images:
                base_img = self.img_cache[idx]
                img = torch.flip(base_img, [1])
            else:
                img = self._generate_image(cont)
        else:
            if self.cache_images:
                img = self.img_cache[idx]
            else:
                img = self._generate_image(cont)
        
        cont_tensor = torch.tensor(cont, dtype=torch.float32)
        cat_tensor = torch.tensor(data['cat'], dtype=torch.long)
        target_tensor = torch.tensor(target, dtype=torch.float32)
        target_polar_tensor = torch.tensor(target_polar, dtype=torch.float32)
        
        seq_len = cont.shape[0]
        aux_target = np.zeros((seq_len, 2), dtype=np.float32)
        if seq_len > 1:
            aux_target[:-1] = cont[1:, 0:2]
        aux_target[-1] = target 
        aux_target_tensor = torch.tensor(aux_target, dtype=torch.float32)
        
        # Return index for safe inference
        return img, cont_tensor, cat_tensor, target_tensor, aux_target_tensor, target_polar_tensor, idx

In [4]:
def multimodal_collate_fn(batch):
    # [FIXED] Handle index return
    imgs, conts, cats, targets, aux_targets, polar_targets, indices = zip(*batch)
    imgs_batched = torch.stack(imgs, dim=0)
    lengths = torch.tensor([len(c) for c in conts], dtype=torch.long)
    conts_padded = pad_sequence(conts, batch_first=True)
    cats_padded = pad_sequence(cats, batch_first=True)
    targets = torch.stack(targets, dim=0)
    aux_targets_padded = pad_sequence(aux_targets, batch_first=True)
    polar_targets_batched = torch.stack(polar_targets, dim=0)
    indices = torch.tensor(indices, dtype=torch.long)
    return imgs_batched, conts_padded, cats_padded, lengths, targets, aux_targets_padded, polar_targets_batched, indices

In [5]:
class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super(SpatialAttention, self).__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x_cat = torch.cat([avg_out, max_out], dim=1)
        x_out = self.conv(x_cat)
        return self.sigmoid(x_out)

class ImprovedCNN(nn.Module):
    def __init__(self):
        super(ImprovedCNN, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(2, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128), nn.ReLU(),
        )
        self.sa = SpatialAttention()
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(128, 128)
        
    def forward(self, x):
        x = self.features(x)
        sa_map = self.sa(x)
        x = x * sa_map
        x = self.pool(x).flatten(1)
        x = F.relu(self.fc(x))
        return x

class LSTMAttention(nn.Module):
    def __init__(self, hidden_dim):
        super(LSTMAttention, self).__init__()
        self.attention = nn.Linear(hidden_dim, 1)
    def forward(self, rnn_output):
        attn_weights = torch.softmax(self.attention(rnn_output), dim=1)
        return torch.sum(attn_weights * rnn_output, dim=1)

class PolarMultiModalNet(nn.Module):
    """
    Polar Coordinate Regression Model
    Output: (distance, sin_theta, cos_theta)
    """
    def __init__(self, input_dim_cont, num_types, num_results, gru_hidden=96):
        super(PolarMultiModalNet, self).__init__()
        self.cnn = ImprovedCNN()
        self.type_emb = nn.Embedding(num_types, 8)
        self.result_emb = nn.Embedding(num_results, 8)
        
        total_input_dim = input_dim_cont + 8 + 8
        self.gru_hidden = gru_hidden
        
        # Split GRU (Anti-Leakage)
        self.gru_fwd = nn.GRU(
            input_size=total_input_dim,
            hidden_size=gru_hidden,
            num_layers=2,
            batch_first=True,
            bidirectional=False,
            dropout=0.1
        )
        
        self.gru_bwd = nn.GRU(
            input_size=total_input_dim,
            hidden_size=gru_hidden,
            num_layers=2,
            batch_first=True,
            bidirectional=False,
            dropout=0.1
        )
        
        self.gru_attn = LSTMAttention(gru_hidden * 2)
        self.gru_fc = nn.Linear(gru_hidden * 2, 128)
        
        # [Polar] Distance Head
        self.distance_head = nn.Sequential(
            nn.BatchNorm1d(256), nn.Dropout(0.3),
            nn.Linear(256, 128), nn.ReLU(),
            nn.Linear(128, 64), nn.ReLU(),
            nn.Linear(64, 1),
            nn.Softplus()  # Distance is always positive
        )
        
        # [Polar] Direction Head (sin, cos)
        self.direction_head = nn.Sequential(
            nn.BatchNorm1d(256), nn.Dropout(0.3),
            nn.Linear(256, 128), nn.ReLU(),
            nn.Linear(128, 64), nn.ReLU(),
            nn.Linear(64, 2),
            nn.Tanh()  # sin, cos are in [-1, 1]
        )
        
        # Auxiliary head (for deep supervision, uses forward GRU only)
        self.aux_fc = nn.Linear(gru_hidden, 2)

    def forward(self, img, cont, cat, lengths):
        # 1. Feature Extraction
        img_feat = self.cnn(img)
        emb_type = self.type_emb(cat[:, :, 0])
        emb_result = self.result_emb(cat[:, :, 1])
        x_seq = torch.cat([cont, emb_type, emb_result], dim=2)
        
        # 2. Forward GRU
        packed_fwd = pack_padded_sequence(x_seq, lengths.cpu(), batch_first=True, enforce_sorted=False)
        out_fwd_packed, _ = self.gru_fwd(packed_fwd)
        out_fwd, _ = pad_packed_sequence(out_fwd_packed, batch_first=True)
        
        # 3. Backward GRU (Manual Flip)
        x_seq_bwd = x_seq.clone()
        for i, length in enumerate(lengths):
            x_seq_bwd[i, :length] = x_seq[i, :length].flip(0)
            
        packed_bwd = pack_padded_sequence(x_seq_bwd, lengths.cpu(), batch_first=True, enforce_sorted=False)
        out_bwd_packed, _ = self.gru_bwd(packed_bwd)
        out_bwd, _ = pad_packed_sequence(out_bwd_packed, batch_first=True)
        
        # Reverse output back to original order
        for i, length in enumerate(lengths):
            out_bwd[i, :length] = out_bwd[i, :length].flip(0)
            
        # 4. Concatenate: [Forward, Backward]
        gru_out_combined = torch.cat([out_fwd, out_bwd], dim=2)  # [B, L, H*2]
        
        # 5. Main Output (Polar)
        gru_ctx = self.gru_attn(gru_out_combined)
        seq_feat = F.relu(self.gru_fc(gru_ctx))
        concat_feat = torch.cat([img_feat, seq_feat], dim=1)  # [B, 256]
        
        # Predict polar coordinates
        distance = self.distance_head(concat_feat).squeeze(-1)  # [B]
        direction = self.direction_head(concat_feat)  # [B, 2]
        sin_theta = direction[:, 0]
        cos_theta = direction[:, 1]
        
        # 6. Aux Output (Deep Supervision, Cartesian)
        aux_out = self.aux_fc(out_fwd)  # [B, L, 2]
        
        return distance, sin_theta, cos_theta, aux_out

# [Polar] Loss Functions
class PolarLoss(nn.Module):
    def __init__(self, w_distance=1.0, w_direction=2.0, huber_delta=1.0):
        super(PolarLoss, self).__init__()
        self.w_distance = w_distance
        self.w_direction = w_direction
        self.huber = nn.HuberLoss(delta=huber_delta)
    
    def forward(self, pred_d, pred_sin, pred_cos, target_polar):
        """
        Args:
            pred_d: (B,) predicted distance
            pred_sin: (B,) predicted sin(theta)
            pred_cos: (B,) predicted cos(theta)
            target_polar: (B, 3) [d, sin_theta, cos_theta]
        """
        target_d = target_polar[:, 0]
        target_sin = target_polar[:, 1]
        target_cos = target_polar[:, 2]
        
        # Distance Loss (Huber)
        loss_distance = self.huber(pred_d, target_d)
        
        # Direction Loss (Cosine Similarity)
        # 중요: 예측 벡터를 단위 벡터로 정규화해야 각도 오차만 정확히 계산됨
        pred_vec_norm = torch.sqrt(pred_sin**2 + pred_cos**2 + 1e-8)
        pred_sin = pred_sin / pred_vec_norm
        pred_cos = pred_cos / pred_vec_norm
        
        # cos(θ_pred - θ_true) = cos_pred*cos_true + sin_pred*sin_true
        cos_diff = pred_cos * target_cos + pred_sin * target_sin
        loss_direction = 1 - cos_diff.mean()  # 1 - cos(θ) → 0 when aligned
        
        # Total Loss
        total_loss = self.w_distance * loss_distance + self.w_direction * loss_direction
        
        return total_loss
        
class MaskedSeqEuclideanLoss(nn.Module):
    def __init__(self):
        super(MaskedSeqEuclideanLoss, self).__init__()
        
    def forward(self, pred, target, lengths):
        mask = torch.arange(pred.size(1), device=pred.device)[None, :] < lengths[:, None]
        mask = mask.unsqueeze(-1)  # [B, L, 1]
        
        pred_real = pred * torch.tensor([105.0, 68.0], device=pred.device)
        target_real = target * torch.tensor([105.0, 68.0], device=target.device)
        
        diff = pred_real - target_real
        dist = torch.sqrt(torch.sum(diff**2, dim=2) + 1e-6)  # [B, L]
        
        # Masking
        dist = dist * mask.squeeze(-1)
        
        return dist.sum() / mask.sum()

## 4. 학습

In [6]:
# [Polar] Training Function (Fixed with Distance-Aware Loss & Score Logging)
def train_multimodal_polar(train_df, n_splits=10, epochs=100, batch_size=64, lr=0.001):
    import sys
    sys.path.append('src')
    from polar_utils import normalize_vec, polar_to_cartesian
    from src.polar_loss import PolarLoss  # [New] Improved Loss
    
    gkf = GroupKFold(n_splits=n_splits)
    groups = train_df['game_id'] 
    
    fold_scores = []
    input_dim_cont = None
    num_types = None
    num_results = None
    
    for fold, (train_idx, val_idx) in enumerate(gkf.split(train_df, groups=groups)):
        fold_seed = FOLD_SEEDS.get(fold + 1, 42)
        seed_everything(fold_seed)
        print(f"\n=== Fold {fold+1}/{n_splits} ===")
        
        train_sub_df = train_df.iloc[train_idx].copy()
        val_sub_df = train_df.iloc[val_idx].copy()
        
        preprocessor = FootballPreprocessorPolar()
        preprocessor.fit(train_sub_df)

        if input_dim_cont is None:
            input_dim_cont = preprocessor.get_input_dim()
            num_types, num_results = preprocessor.get_num_classes()
            print(f"Model Dimensions: input={input_dim_cont}, types={num_types}, results={num_results}")
        
        train_episodes = preprocessor.transform(train_sub_df, is_train=True)
        val_episodes = preprocessor.transform(val_sub_df, is_train=True)
        
        train_dataset = MultiModalDataset(train_episodes, augment=True, cache_images=True)
        val_dataset = MultiModalDataset(val_episodes, augment=False, cache_images=True)
        
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=multimodal_collate_fn, drop_last=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, collate_fn=multimodal_collate_fn)
        
        model = PolarMultiModalNet(input_dim_cont, num_types, num_results, gru_hidden=96).to(DEVICE)
        
        # [New] Distance-Aware Weighted Loss
        criterion_main = PolarLoss(
            w_distance=2.0,   # Emphasis on Distance
            w_direction=1.0,  # Lower emphasis on Direction
            w_euclidean=1.0,  # [New] Direct Euclidean Optimization
            huber_delta=1.0
        )
        criterion_aux = MaskedSeqEuclideanLoss() 
        
        optimizer = optim.Adam(model.parameters(), lr=lr) 
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)
        
        best_dist = float('inf')
        patience_counter = 0
        patience_limit = 15
        
        for epoch in range(epochs):
            model.train()
            train_loss = 0
            
            # Decay Aux Weight
            if epoch < 5:
                aux_weight = 0.5
            elif epoch < 20:
                aux_weight = 0.2
            else:
                aux_weight = 0.05

            for batch in train_loader:
                imgs, cont, cat, lengths, target, aux_target, polar_target, _ = batch
                imgs = imgs.to(DEVICE)
                cont = cont.to(DEVICE)
                cat = cat.to(DEVICE)
                lengths = lengths.to(DEVICE)
                aux_target = aux_target.to(DEVICE)
                polar_target = polar_target.to(DEVICE)
                
                optimizer.zero_grad()
                pred_d, pred_sin, pred_cos, aux_pred = model(imgs, cont, cat, lengths)
                
                loss_m = criterion_main(pred_d, pred_sin, pred_cos, polar_target)
                loss_a = criterion_aux(aux_pred, aux_target, lengths)
                
                loss = loss_m + aux_weight * loss_a
                loss.backward()
                optimizer.step()
                train_loss += loss.item()
            
            train_loss /= len(train_loader)
            
            # Validation
            model.eval()
            val_dists = []
            with torch.no_grad():
                for batch_idx, batch in enumerate(val_loader):
                    imgs, cont, cat, lengths, target, aux_target, _, _ = batch  # Ignore indices
                    imgs = imgs.to(DEVICE)
                    cont = cont.to(DEVICE)
                    cat = cat.to(DEVICE)
                    lengths = lengths.to(DEVICE)
                    
                    pred_d_norm, pred_sin, pred_cos, _ = model(imgs, cont, cat, lengths)
                    
                    pred_d_norm = pred_d_norm.cpu().numpy()
                    pred_sin = pred_sin.cpu().numpy()
                    pred_cos = pred_cos.cpu().numpy()
                    
                    batch_start = batch_idx * batch_size
                    
                    for i in range(len(pred_d_norm)):
                        if batch_start + i >= len(val_dataset.episodes):
                            break
                        
                        ep = val_dataset.episodes[batch_start + i]
                        
                        pred_end_x, pred_end_y = polar_to_cartesian(
                            pred_d_norm[i], pred_sin[i], pred_cos[i],
                            ep['start_x'], ep['start_y'],
                            d_scale=ep['d_scale'],
                            normalize_direction=True,
                            clip_field=True
                        )
                        
                        true_end = ep['target_raw']
                        dist = np.sqrt((pred_end_x - true_end[0])**2 + (pred_end_y - true_end[1])**2)
                        val_dists.append(dist)
            
            mean_dist = np.mean(val_dists)
            scheduler.step(mean_dist)
            print(f"Epoch {epoch+1}: Train Loss {train_loss:.4f}, Val Dist {mean_dist:.4f}")
            
            if mean_dist < best_dist:
                best_dist = mean_dist
                torch.save(model.state_dict(), f"models/multimodal_polar_h96_{fold+1}.pth")
                joblib.dump(preprocessor, f"models/preprocessor_polar_h96_{fold+1}.pkl")
                print(f"  -> Saved Best Model (Dist: {best_dist:.4f})")
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= patience_limit:
                    print("Early Stopping")
                    break
        
        print(f"Fold {fold+1} Finished. Best Valid Dist: {best_dist:.4f}")
        fold_scores.append(best_dist)
    
    # [New] Improved Score Logging
    print("\n" + "="*40)
    print(f"{'FINAL FOLD SCORES':^40}")
    print("="*40)
    for i, score in enumerate(fold_scores):
        print(f"Fold {i+1:02d}: {score:.4f}")
    print("-" * 40)
    print(f"AVERAGE: {np.mean(fold_scores):.4f}")
    print("="*40 + "\n")
    
    return fold_scores

In [7]:
# [Polar] Train Model
train_multimodal_polar(train_df, n_splits=10, epochs=100, batch_size=64, lr=0.001)

=== Fold 1/10 ===
Model Dimensions: input=10, types=27, results=21
Pre-rendering 13847 images (Cache Enabled)...

Caching Images: 100%|██████████| 13847/13847 [00:01<00:00, 13233.59it/s]

Pre-rendering 1581 images (Cache Enabled)...

Caching Images: 100%|██████████| 1581/1581 [00:00<00:00, 13599.08it/s]

Epoch 1: Train Loss 36.3981, Val Dist 17.4347
  -> Saved Best Model (Dist: 17.4347)
Epoch 2: Train Loss 29.7128, Val Dist 16.7180
  -> Saved Best Model (Dist: 16.7180)
Epoch 3: Train Loss 28.4062, Val Dist 17.0221
Epoch 4: Train Loss 27.7392, Val Dist 16.0545
  -> Saved Best Model (Dist: 16.0545)
Epoch 5: Train Loss 27.2825, Val Dist 16.2889
Epoch 6: Train Loss 11.1261, Val Dist 16.1451
Epoch 7: Train Loss 11.0407, Val Dist 15.8128
  -> Saved Best Model (Dist: 15.8128)
Epoch 8: Train Loss 10.9798, Val Dist 15.8104
  -> Saved Best Model (Dist: 15.8104)
Epoch 9: Train Loss 10.9234, Val Dist 15.5449
  -> Saved Best Model (Dist: 15.5449)
Epoch 10: Train Loss 10.8670, Val Dist 15.3598
  -> Saved Best Model (Dist: 15.3598)
Epoch 11: Train Loss 10.8352, Val Dist 15.1820
  -> Saved Best Model (Dist: 15.1820)
Epoch 12: Train Loss 10.7839, Val Dist 15.1330
  -> Saved Best Model (Dist: 15.1330)
Epoch 13: Train Loss 10.7253, Val Dist 15.1149
  -> Saved Best Model (Dist: 15.1149)
Epoch 14: Train Loss 10.6874, Val Dist 15.1804
Epoch 15: Train Loss 10.6529, Val Dist 14.8766
  -> Saved Best Model (Dist: 14.8766)
Epoch 16: Train Loss 10.6195, Val Dist 14.7185
  -> Saved Best Model (Dist: 14.7185)
Epoch 17: Train Loss 10.6022, Val Dist 14.7816
Epoch 18: Train Loss 10.5502, Val Dist 14.8100
Epoch 19: Train Loss 10.5460, Val Dist 15.0313
Epoch 20: Train Loss 10.5146, Val Dist 14.7104
  -> Saved Best Model (Dist: 14.7104)
Epoch 21: Train Loss 2.9799, Val Dist 15.2945
Epoch 22: Train Loss 2.9873, Val Dist 15.4107
Epoch 23: Train Loss 2.9855, Val Dist 14.5061
  -> Saved Best Model (Dist: 14.5061)
Epoch 24: Train Loss 2.9693, Val Dist 14.8207
Epoch 25: Train Loss 2.9582, Val Dist 14.6610
Epoch 26: Train Loss 2.9604, Val Dist 14.8416
Epoch 27: Train Loss 2.9554, Val Dist 14.3488
  -> Saved Best Model (Dist: 14.3488)
Epoch 28: Train Loss 2.9521, Val Dist 15.3313
Epoch 29: Train Loss 2.9660, Val Dist 14.5034
Epoch 30: Train Loss 2.9606, Val Dist 14.3343
  -> Saved Best Model (Dist: 14.3343)
Epoch 31: Train Loss 2.9487, Val Dist 14.3613
Epoch 32: Train Loss 2.9408, Val Dist 14.5123
Epoch 33: Train Loss 2.9345, Val Dist 14.3641
Epoch 34: Train Loss 2.9581, Val Dist 14.8016
Epoch 35: Train Loss 2.9271, Val Dist 14.2681
  -> Saved Best Model (Dist: 14.2681)
Epoch 36: Train Loss 2.9164, Val Dist 14.1119
  -> Saved Best Model (Dist: 14.1119)
Epoch 37: Train Loss 2.9065, Val Dist 14.0012
  -> Saved Best Model (Dist: 14.0012)
Epoch 38: Train Loss 2.9099, Val Dist 13.9814
  -> Saved Best Model (Dist: 13.9814)
Epoch 39: Train Loss 2.9010, Val Dist 13.9656
  -> Saved Best Model (Dist: 13.9656)
Epoch 40: Train Loss 2.9017, Val Dist 13.9765
Epoch 41: Train Loss 2.8955, Val Dist 13.9040
  -> Saved Best Model (Dist: 13.9040)
Epoch 42: Train Loss 2.8926, Val Dist 13.9385
Epoch 43: Train Loss 2.8956, Val Dist 15.0901
Epoch 44: Train Loss 2.9329, Val Dist 14.1528
Epoch 45: Train Loss 2.9009, Val Dist 13.9148
Epoch 46: Train Loss 2.8839, Val Dist 13.8620
  -> Saved Best Model (Dist: 13.8620)
Epoch 47: Train Loss 2.8821, Val Dist 13.8589
  -> Saved Best Model (Dist: 13.8589)
Epoch 48: Train Loss 2.8764, Val Dist 13.8408
  -> Saved Best Model (Dist: 13.8408)
Epoch 49: Train Loss 2.8751, Val Dist 13.9013
Epoch 50: Train Loss 2.8738, Val Dist 13.8836
Epoch 51: Train Loss 2.8701, Val Dist 13.9196
Epoch 52: Train Loss 2.8693, Val Dist 13.8598
Epoch 53: Train Loss 2.8656, Val Dist 13.8449
Epoch 54: Train Loss 2.8637, Val Dist 13.8235
  -> Saved Best Model (Dist: 13.8235)
Epoch 55: Train Loss 2.8622, Val Dist 13.7805
  -> Saved Best Model (Dist: 13.7805)
Epoch 56: Train Loss 2.8620, Val Dist 13.8071
Epoch 57: Train Loss 2.8611, Val Dist 13.7823
Epoch 58: Train Loss 2.8578, Val Dist 13.7764
  -> Saved Best Model (Dist: 13.7764)
Epoch 59: Train Loss 2.8557, Val Dist 13.8188
Epoch 60: Train Loss 2.8583, Val Dist 13.8062
Epoch 61: Train Loss 2.8560, Val Dist 13.7635
  -> Saved Best Model (Dist: 13.7635)
Epoch 62: Train Loss 2.8548, Val Dist 13.7642
Epoch 63: Train Loss 2.8546, Val Dist 13.7236
  -> Saved Best Model (Dist: 13.7236)
Epoch 64: Train Loss 2.8527, Val Dist 13.7486
Epoch 65: Train Loss 2.8560, Val Dist 13.8314
Epoch 66: Train Loss 2.8548, Val Dist 13.7248
Epoch 67: Train Loss 2.8548, Val Dist 13.7348
Epoch 68: Train Loss 2.8473, Val Dist 13.7959
Epoch 69: Train Loss 2.8483, Val Dist 13.7255
Epoch 70: Train Loss 2.8459, Val Dist 13.7750
Epoch 71: Train Loss 2.8479, Val Dist 13.7066
  -> Saved Best Model (Dist: 13.7066)
Epoch 72: Train Loss 2.8476, Val Dist 13.7226
Epoch 73: Train Loss 2.8459, Val Dist 13.7385
Epoch 74: Train Loss 2.8437, Val Dist 13.7260
Epoch 75: Train Loss 2.8459, Val Dist 13.7238
Epoch 76: Train Loss 2.8428, Val Dist 13.7545
Epoch 77: Train Loss 2.8419, Val Dist 13.7090
Epoch 78: Train Loss 2.8439, Val Dist 13.6992
  -> Saved Best Model (Dist: 13.6992)
Epoch 79: Train Loss 2.8429, Val Dist 13.7882
Epoch 80: Train Loss 2.8434, Val Dist 13.7112
Epoch 81: Train Loss 2.8418, Val Dist 13.7025
Epoch 82: Train Loss 2.8419, Val Dist 13.7244
Epoch 83: Train Loss 2.8407, Val Dist 13.7332
Epoch 84: Train Loss 2.8422, Val Dist 13.7008
Epoch 85: Train Loss 2.8431, Val Dist 13.6725
  -> Saved Best Model (Dist: 13.6725)
Epoch 86: Train Loss 2.8418, Val Dist 13.7080
Epoch 87: Train Loss 2.8428, Val Dist 13.6538
  -> Saved Best Model (Dist: 13.6538)
Epoch 88: Train Loss 2.8411, Val Dist 13.7274
Epoch 89: Train Loss 2.8445, Val Dist 13.7176
Epoch 90: Train Loss 2.8414, Val Dist 13.6957
Epoch 91: Train Loss 2.8394, Val Dist 13.7136
Epoch 92: Train Loss 2.8393, Val Dist 13.7363
Epoch 93: Train Loss 2.8403, Val Dist 13.6958
Epoch 94: Train Loss 2.8379, Val Dist 13.7086
Epoch 95: Train Loss 2.8402, Val Dist 13.7494
Epoch 96: Train Loss 2.8410, Val Dist 13.6855
Epoch 97: Train Loss 2.8420, Val Dist 13.6727
Epoch 98: Train Loss 2.8390, Val Dist 13.7274
Epoch 99: Train Loss 2.8414, Val Dist 13.6633
Epoch 100: Train Loss 2.8394, Val Dist 13.7088
Fold 1 Finished. Best Valid Dist: 13.6538

=== Fold 2/10 ===
Pre-rendering 13934 images (Cache Enabled)...

Caching Images: 100%|██████████| 13934/13934 [00:00<00:00, 14128.43it/s]

Pre-rendering 1494 images (Cache Enabled)...

Caching Images: 100%|██████████| 1494/1494 [00:00<00:00, 13649.16it/s]

Epoch 1: Train Loss 36.5576, Val Dist 18.8603
  -> Saved Best Model (Dist: 18.8603)
Epoch 2: Train Loss 29.5326, Val Dist 17.1159
  -> Saved Best Model (Dist: 17.1159)
Epoch 3: Train Loss 28.3009, Val Dist 17.0969
  -> Saved Best Model (Dist: 17.0969)
Epoch 4: Train Loss 27.7548, Val Dist 16.9890
  -> Saved Best Model (Dist: 16.9890)
Epoch 5: Train Loss 27.3341, Val Dist 16.9323
  -> Saved Best Model (Dist: 16.9323)
Epoch 6: Train Loss 11.1775, Val Dist 16.9036
  -> Saved Best Model (Dist: 16.9036)
Epoch 7: Train Loss 11.1095, Val Dist 16.6726
  -> Saved Best Model (Dist: 16.6726)
Epoch 8: Train Loss 11.0620, Val Dist 16.3752
  -> Saved Best Model (Dist: 16.3752)
Epoch 9: Train Loss 11.0216, Val Dist 16.6120
Epoch 10: Train Loss 10.9617, Val Dist 16.3985
Epoch 11: Train Loss 10.9192, Val Dist 16.0208
  -> Saved Best Model (Dist: 16.0208)
Epoch 12: Train Loss 10.8610, Val Dist 16.0737
Epoch 13: Train Loss 10.8190, Val Dist 15.7909
  -> Saved Best Model (Dist: 15.7909)
Epoch 14: Train Loss 10.7675, Val Dist 15.5439
  -> Saved Best Model (Dist: 15.5439)
Epoch 15: Train Loss 10.7342, Val Dist 15.3187
  -> Saved Best Model (Dist: 15.3187)
Epoch 16: Train Loss 10.6859, Val Dist 15.9199
Epoch 17: Train Loss 10.6450, Val Dist 15.1526
  -> Saved Best Model (Dist: 15.1526)
Epoch 18: Train Loss 10.6302, Val Dist 15.1621
Epoch 19: Train Loss 10.5822, Val Dist 15.4160
Epoch 20: Train Loss 10.5515, Val Dist 14.7352
  -> Saved Best Model (Dist: 14.7352)
Epoch 21: Train Loss 3.0036, Val Dist 14.9270
Epoch 22: Train Loss 3.0093, Val Dist 14.9643
Epoch 23: Train Loss 2.9974, Val Dist 14.9012
Epoch 24: Train Loss 2.9897, Val Dist 14.5124
  -> Saved Best Model (Dist: 14.5124)
Epoch 25: Train Loss 2.9852, Val Dist 14.7044
Epoch 26: Train Loss 3.0045, Val Dist 15.1233
Epoch 27: Train Loss 2.9929, Val Dist 14.6999
Epoch 28: Train Loss 2.9823, Val Dist 14.5629
Epoch 29: Train Loss 2.9655, Val Dist 14.2147
  -> Saved Best Model (Dist: 14.2147)
Epoch 30: Train Loss 2.9550, Val Dist 14.2066
  -> Saved Best Model (Dist: 14.2066)
Epoch 31: Train Loss 2.9522, Val Dist 14.2776
Epoch 32: Train Loss 2.9463, Val Dist 14.1851
  -> Saved Best Model (Dist: 14.1851)
Epoch 33: Train Loss 2.9447, Val Dist 13.9849
  -> Saved Best Model (Dist: 13.9849)
Epoch 34: Train Loss 2.9365, Val Dist 14.0541
Epoch 35: Train Loss 2.9428, Val Dist 14.0528
Epoch 36: Train Loss 2.9299, Val Dist 14.0250
Epoch 37: Train Loss 2.9351, Val Dist 14.3120
Epoch 38: Train Loss 2.9336, Val Dist 14.1827
Epoch 39: Train Loss 2.9189, Val Dist 14.0316
Epoch 40: Train Loss 2.9152, Val Dist 13.9344
  -> Saved Best Model (Dist: 13.9344)
Epoch 41: Train Loss 2.9076, Val Dist 13.8006
  -> Saved Best Model (Dist: 13.8006)
Epoch 42: Train Loss 2.9069, Val Dist 13.9321
Epoch 43: Train Loss 2.9062, Val Dist 13.8410
Epoch 44: Train Loss 2.9012, Val Dist 13.7618
  -> Saved Best Model (Dist: 13.7618)
Epoch 45: Train Loss 2.9054, Val Dist 13.7186
  -> Saved Best Model (Dist: 13.7186)
Epoch 46: Train Loss 2.9006, Val Dist 13.7730
Epoch 47: Train Loss 2.9029, Val Dist 13.6977
  -> Saved Best Model (Dist: 13.6977)
Epoch 48: Train Loss 2.8981, Val Dist 13.7606
Epoch 49: Train Loss 2.8992, Val Dist 13.6962
  -> Saved Best Model (Dist: 13.6962)
Epoch 50: Train Loss 2.8933, Val Dist 13.7647
Epoch 51: Train Loss 2.8938, Val Dist 13.6460
  -> Saved Best Model (Dist: 13.6460)
Epoch 52: Train Loss 2.8979, Val Dist 13.6162
  -> Saved Best Model (Dist: 13.6162)
Epoch 53: Train Loss 2.8883, Val Dist 13.6905
Epoch 54: Train Loss 2.8945, Val Dist 13.8795
Epoch 55: Train Loss 2.8910, Val Dist 13.7564
Epoch 56: Train Loss 2.8861, Val Dist 13.6989
Epoch 57: Train Loss 2.8828, Val Dist 13.6118
  -> Saved Best Model (Dist: 13.6118)
Epoch 58: Train Loss 2.8812, Val Dist 13.6187
Epoch 59: Train Loss 2.8757, Val Dist 13.5861
  -> Saved Best Model (Dist: 13.5861)
Epoch 60: Train Loss 2.8761, Val Dist 13.7380
Epoch 61: Train Loss 2.8719, Val Dist 13.6774
Epoch 62: Train Loss 2.8747, Val Dist 13.7080
Epoch 63: Train Loss 2.8725, Val Dist 13.7087
Epoch 64: Train Loss 2.8707, Val Dist 13.6402
Epoch 65: Train Loss 2.8709, Val Dist 13.5981
Epoch 66: Train Loss 2.8688, Val Dist 13.6380
Epoch 67: Train Loss 2.8706, Val Dist 13.6468
Epoch 68: Train Loss 2.8674, Val Dist 13.5798
  -> Saved Best Model (Dist: 13.5798)
Epoch 69: Train Loss 2.8681, Val Dist 13.6096
Epoch 70: Train Loss 2.8638, Val Dist 13.5484
  -> Saved Best Model (Dist: 13.5484)
Epoch 71: Train Loss 2.8650, Val Dist 13.5855
Epoch 72: Train Loss 2.8653, Val Dist 13.6023
Epoch 73: Train Loss 2.8645, Val Dist 13.5926
Epoch 74: Train Loss 2.8637, Val Dist 13.5555
Epoch 75: Train Loss 2.8623, Val Dist 13.6052
Epoch 76: Train Loss 2.8615, Val Dist 13.5885
Epoch 77: Train Loss 2.8693, Val Dist 13.5746
Epoch 78: Train Loss 2.8637, Val Dist 13.5706
Epoch 79: Train Loss 2.8631, Val Dist 13.5354
  -> Saved Best Model (Dist: 13.5354)
Epoch 80: Train Loss 2.8613, Val Dist 13.5934
Epoch 81: Train Loss 2.8632, Val Dist 13.6132
Epoch 82: Train Loss 2.8628, Val Dist 13.6037
Epoch 83: Train Loss 2.8614, Val Dist 13.5301
  -> Saved Best Model (Dist: 13.5301)
Epoch 84: Train Loss 2.8645, Val Dist 13.5643
Epoch 85: Train Loss 2.8636, Val Dist 13.5411
Epoch 86: Train Loss 2.8633, Val Dist 13.5390
Epoch 87: Train Loss 2.8638, Val Dist 13.5579
Epoch 88: Train Loss 2.8619, Val Dist 13.6096
Epoch 89: Train Loss 2.8631, Val Dist 13.5934
Epoch 90: Train Loss 2.8619, Val Dist 13.5832
Epoch 91: Train Loss 2.8617, Val Dist 13.5437
Epoch 92: Train Loss 2.8656, Val Dist 13.6068
Epoch 93: Train Loss 2.8610, Val Dist 13.5581
Epoch 94: Train Loss 2.8630, Val Dist 13.6026
Epoch 95: Train Loss 2.8644, Val Dist 13.5838
Epoch 96: Train Loss 2.8612, Val Dist 13.5855
Epoch 97: Train Loss 2.8622, Val Dist 13.5871
Epoch 98: Train Loss 2.8579, Val Dist 13.5930
Early Stopping
Fold 2 Finished. Best Valid Dist: 13.5301

=== Fold 3/10 ===
Pre-rendering 13865 images (Cache Enabled)...

Caching Images: 100%|██████████| 13865/13865 [00:00<00:00, 14489.02it/s]

Pre-rendering 1563 images (Cache Enabled)...

Caching Images: 100%|██████████| 1563/1563 [00:00<00:00, 13406.28it/s]

Epoch 1: Train Loss 36.5078, Val Dist 17.4943
  -> Saved Best Model (Dist: 17.4943)
Epoch 2: Train Loss 29.5806, Val Dist 16.6128
  -> Saved Best Model (Dist: 16.6128)
Epoch 3: Train Loss 28.4025, Val Dist 16.7795
Epoch 4: Train Loss 27.8567, Val Dist 16.6358
Epoch 5: Train Loss 27.3997, Val Dist 16.8243
Epoch 6: Train Loss 11.1818, Val Dist 16.8940
Epoch 7: Train Loss 11.1151, Val Dist 16.3931
  -> Saved Best Model (Dist: 16.3931)
Epoch 8: Train Loss 11.0782, Val Dist 16.3273
  -> Saved Best Model (Dist: 16.3273)
Epoch 9: Train Loss 11.0469, Val Dist 16.4461
Epoch 10: Train Loss 11.0183, Val Dist 16.2352
  -> Saved Best Model (Dist: 16.2352)
Epoch 11: Train Loss 10.9795, Val Dist 16.3112
Epoch 12: Train Loss 10.9467, Val Dist 16.1866
  -> Saved Best Model (Dist: 16.1866)
Epoch 13: Train Loss 10.9172, Val Dist 15.8427
  -> Saved Best Model (Dist: 15.8427)
Epoch 14: Train Loss 10.8768, Val Dist 15.6263
  -> Saved Best Model (Dist: 15.6263)
Epoch 15: Train Loss 10.8773, Val Dist 16.0560
Epoch 16: Train Loss 10.8392, Val Dist 15.6916
Epoch 17: Train Loss 10.8011, Val Dist 15.7227
Epoch 18: Train Loss 10.7755, Val Dist 15.6589
Epoch 19: Train Loss 10.7302, Val Dist 15.2838
  -> Saved Best Model (Dist: 15.2838)
Epoch 20: Train Loss 10.7159, Val Dist 15.1822
  -> Saved Best Model (Dist: 15.1822)
Epoch 21: Train Loss 3.0767, Val Dist 15.1155
  -> Saved Best Model (Dist: 15.1155)
Epoch 22: Train Loss 3.0677, Val Dist 15.1042
  -> Saved Best Model (Dist: 15.1042)
Epoch 23: Train Loss 3.0639, Val Dist 15.0739
  -> Saved Best Model (Dist: 15.0739)
Epoch 24: Train Loss 3.0605, Val Dist 15.0234
  -> Saved Best Model (Dist: 15.0234)
Epoch 25: Train Loss 3.0616, Val Dist 14.9088
  -> Saved Best Model (Dist: 14.9088)
Epoch 26: Train Loss 3.0623, Val Dist 14.9366
Epoch 27: Train Loss 3.0539, Val Dist 14.8779
  -> Saved Best Model (Dist: 14.8779)
Epoch 28: Train Loss 3.0510, Val Dist 14.8982
Epoch 29: Train Loss 3.0521, Val Dist 14.8342
  -> Saved Best Model (Dist: 14.8342)
Epoch 30: Train Loss 3.0471, Val Dist 14.7095
  -> Saved Best Model (Dist: 14.7095)
Epoch 31: Train Loss 3.0416, Val Dist 14.9682
Epoch 32: Train Loss 3.0333, Val Dist 14.7395
Epoch 33: Train Loss 3.0371, Val Dist 14.7954
Epoch 34: Train Loss 3.0332, Val Dist 14.5421
  -> Saved Best Model (Dist: 14.5421)
Epoch 35: Train Loss 3.0288, Val Dist 14.7120
Epoch 36: Train Loss 3.0275, Val Dist 14.5882
Epoch 37: Train Loss 3.0202, Val Dist 14.5981
Epoch 38: Train Loss 3.0221, Val Dist 14.4724
  -> Saved Best Model (Dist: 14.4724)
Epoch 39: Train Loss 3.0157, Val Dist 14.4530
  -> Saved Best Model (Dist: 14.4530)
Epoch 40: Train Loss 3.0084, Val Dist 14.3205
  -> Saved Best Model (Dist: 14.3205)
Epoch 41: Train Loss 3.0076, Val Dist 14.1459
  -> Saved Best Model (Dist: 14.1459)
Epoch 42: Train Loss 3.0020, Val Dist 14.4074
Epoch 43: Train Loss 2.9949, Val Dist 14.3772
Epoch 44: Train Loss 2.9987, Val Dist 14.1150
  -> Saved Best Model (Dist: 14.1150)
Epoch 45: Train Loss 2.9954, Val Dist 14.2302
Epoch 46: Train Loss 2.9881, Val Dist 14.1478
Epoch 47: Train Loss 2.9891, Val Dist 14.0734
  -> Saved Best Model (Dist: 14.0734)
Epoch 48: Train Loss 2.9850, Val Dist 14.3565
Epoch 49: Train Loss 2.9821, Val Dist 13.9912
  -> Saved Best Model (Dist: 13.9912)
Epoch 50: Train Loss 2.9782, Val Dist 14.0158
Epoch 51: Train Loss 2.9739, Val Dist 14.0793
Epoch 52: Train Loss 2.9728, Val Dist 13.8865
  -> Saved Best Model (Dist: 13.8865)
Epoch 53: Train Loss 2.9670, Val Dist 13.9686
Epoch 54: Train Loss 2.9643, Val Dist 14.1545
Epoch 55: Train Loss 2.9631, Val Dist 13.8662
  -> Saved Best Model (Dist: 13.8662)
Epoch 56: Train Loss 2.9604, Val Dist 13.9218
Epoch 57: Train Loss 2.9562, Val Dist 13.8687
Epoch 58: Train Loss 2.9510, Val Dist 13.9103
Epoch 59: Train Loss 2.9558, Val Dist 13.8142
  -> Saved Best Model (Dist: 13.8142)
Epoch 60: Train Loss 2.9501, Val Dist 13.8871
Epoch 61: Train Loss 2.9583, Val Dist 13.9452
Epoch 62: Train Loss 2.9541, Val Dist 13.9072
Epoch 63: Train Loss 2.9482, Val Dist 13.8261
Epoch 64: Train Loss 2.9416, Val Dist 13.7622
  -> Saved Best Model (Dist: 13.7622)
Epoch 65: Train Loss 2.9317, Val Dist 13.7951
Epoch 66: Train Loss 2.9308, Val Dist 13.7051
  -> Saved Best Model (Dist: 13.7051)
Epoch 67: Train Loss 2.9304, Val Dist 13.7095
Epoch 68: Train Loss 2.9272, Val Dist 13.7478
Epoch 69: Train Loss 2.9275, Val Dist 13.7980
Epoch 70: Train Loss 2.9243, Val Dist 13.6621
  -> Saved Best Model (Dist: 13.6621)
Epoch 71: Train Loss 2.9287, Val Dist 13.6809
Epoch 72: Train Loss 2.9264, Val Dist 13.7441
Epoch 73: Train Loss 2.9265, Val Dist 13.8091
Epoch 74: Train Loss 2.9210, Val Dist 13.7299
Epoch 75: Train Loss 2.9150, Val Dist 13.6329
  -> Saved Best Model (Dist: 13.6329)
Epoch 76: Train Loss 2.9169, Val Dist 13.6758
Epoch 77: Train Loss 2.9134, Val Dist 13.7212
Epoch 78: Train Loss 2.9167, Val Dist 13.6384
Epoch 79: Train Loss 2.9156, Val Dist 13.6605
Epoch 80: Train Loss 2.9111, Val Dist 13.6868
Epoch 81: Train Loss 2.9114, Val Dist 13.6649
Epoch 82: Train Loss 2.9124, Val Dist 13.6619
Epoch 83: Train Loss 2.9112, Val Dist 13.6140
  -> Saved Best Model (Dist: 13.6140)
Epoch 84: Train Loss 2.9110, Val Dist 13.6715
Epoch 85: Train Loss 2.9080, Val Dist 13.6191
Epoch 86: Train Loss 2.9083, Val Dist 13.6789
Epoch 87: Train Loss 2.9061, Val Dist 13.6115
  -> Saved Best Model (Dist: 13.6115)
Epoch 88: Train Loss 2.9096, Val Dist 13.6151
Epoch 89: Train Loss 2.9072, Val Dist 13.6246
Epoch 90: Train Loss 2.9072, Val Dist 13.6050
  -> Saved Best Model (Dist: 13.6050)
Epoch 91: Train Loss 2.9067, Val Dist 13.6174
Epoch 92: Train Loss 2.9045, Val Dist 13.6761
Epoch 93: Train Loss 2.9072, Val Dist 13.6646
Epoch 94: Train Loss 2.9039, Val Dist 13.6472
Epoch 95: Train Loss 2.9045, Val Dist 13.6102
Epoch 96: Train Loss 2.9034, Val Dist 13.6085
Epoch 97: Train Loss 2.9025, Val Dist 13.6159
Epoch 98: Train Loss 2.9030, Val Dist 13.5851
  -> Saved Best Model (Dist: 13.5851)
Epoch 99: Train Loss 2.9030, Val Dist 13.6118
Epoch 100: Train Loss 2.9007, Val Dist 13.6282
Fold 3 Finished. Best Valid Dist: 13.5851

=== Fold 4/10 ===
Pre-rendering 13857 images (Cache Enabled)...

Caching Images: 100%|██████████| 13857/13857 [00:00<00:00, 14238.69it/s]

Pre-rendering 1571 images (Cache Enabled)...

Caching Images: 100%|██████████| 1571/1571 [00:00<00:00, 13435.36it/s]

Epoch 1: Train Loss 35.6315, Val Dist 17.8019
  -> Saved Best Model (Dist: 17.8019)
Epoch 2: Train Loss 29.4683, Val Dist 17.8056
Epoch 3: Train Loss 28.4021, Val Dist 17.0516
  -> Saved Best Model (Dist: 17.0516)
Epoch 4: Train Loss 27.8227, Val Dist 17.0306
  -> Saved Best Model (Dist: 17.0306)
Epoch 5: Train Loss 27.3688, Val Dist 16.2954
  -> Saved Best Model (Dist: 16.2954)
Epoch 6: Train Loss 11.1657, Val Dist 16.0498
  -> Saved Best Model (Dist: 16.0498)
Epoch 7: Train Loss 11.0868, Val Dist 15.8729
  -> Saved Best Model (Dist: 15.8729)
Epoch 8: Train Loss 11.0254, Val Dist 16.6214
Epoch 9: Train Loss 10.9667, Val Dist 15.6810
  -> Saved Best Model (Dist: 15.6810)
Epoch 10: Train Loss 10.9289, Val Dist 15.3708
  -> Saved Best Model (Dist: 15.3708)
Epoch 11: Train Loss 10.8708, Val Dist 15.5903
Epoch 12: Train Loss 10.8229, Val Dist 15.1597
  -> Saved Best Model (Dist: 15.1597)
Epoch 13: Train Loss 10.7721, Val Dist 15.3638
Epoch 14: Train Loss 10.7270, Val Dist 15.0748
  -> Saved Best Model (Dist: 15.0748)
Epoch 15: Train Loss 10.6936, Val Dist 14.7616
  -> Saved Best Model (Dist: 14.7616)
Epoch 16: Train Loss 10.6502, Val Dist 14.8890
Epoch 17: Train Loss 10.6232, Val Dist 14.7948
Epoch 18: Train Loss 10.5780, Val Dist 14.6269
  -> Saved Best Model (Dist: 14.6269)
Epoch 19: Train Loss 10.5540, Val Dist 14.7491
Epoch 20: Train Loss 10.5349, Val Dist 14.7869
Epoch 21: Train Loss 2.9988, Val Dist 14.6420
Epoch 22: Train Loss 2.9851, Val Dist 14.5535
  -> Saved Best Model (Dist: 14.5535)
Epoch 23: Train Loss 2.9825, Val Dist 14.4681
  -> Saved Best Model (Dist: 14.4681)
Epoch 24: Train Loss 2.9766, Val Dist 15.1990
Epoch 25: Train Loss 2.9803, Val Dist 14.8077
Epoch 26: Train Loss 2.9812, Val Dist 14.5255
Epoch 27: Train Loss 2.9662, Val Dist 14.4910
Epoch 28: Train Loss 2.9516, Val Dist 14.2741
  -> Saved Best Model (Dist: 14.2741)
Epoch 29: Train Loss 2.9435, Val Dist 14.1357
  -> Saved Best Model (Dist: 14.1357)
Epoch 30: Train Loss 2.9435, Val Dist 14.5835
Epoch 31: Train Loss 2.9505, Val Dist 14.1549
Epoch 32: Train Loss 2.9455, Val Dist 14.1476
Epoch 33: Train Loss 2.9389, Val Dist 14.1342
  -> Saved Best Model (Dist: 14.1342)
Epoch 34: Train Loss 2.9303, Val Dist 14.0095
  -> Saved Best Model (Dist: 14.0095)
Epoch 35: Train Loss 2.9308, Val Dist 14.0710
Epoch 36: Train Loss 2.9246, Val Dist 14.1335
Epoch 37: Train Loss 2.9239, Val Dist 14.0510
Epoch 38: Train Loss 2.9219, Val Dist 14.0534
Epoch 39: Train Loss 2.9093, Val Dist 13.9284
  -> Saved Best Model (Dist: 13.9284)
Epoch 40: Train Loss 2.9169, Val Dist 14.0152
Epoch 41: Train Loss 2.9053, Val Dist 13.8650
  -> Saved Best Model (Dist: 13.8650)
Epoch 42: Train Loss 2.9050, Val Dist 13.9836
Epoch 43: Train Loss 2.9029, Val Dist 13.8384
  -> Saved Best Model (Dist: 13.8384)
Epoch 44: Train Loss 2.9007, Val Dist 13.8609
Epoch 45: Train Loss 2.8982, Val Dist 13.8977
Epoch 46: Train Loss 2.9002, Val Dist 13.8439
Epoch 47: Train Loss 2.8969, Val Dist 13.9280
Epoch 48: Train Loss 2.8889, Val Dist 13.7971
  -> Saved Best Model (Dist: 13.7971)
Epoch 49: Train Loss 2.8859, Val Dist 13.8415
Epoch 50: Train Loss 2.8856, Val Dist 13.8050
Epoch 51: Train Loss 2.8845, Val Dist 13.9296
Epoch 52: Train Loss 2.8853, Val Dist 13.8349
Epoch 53: Train Loss 2.8846, Val Dist 13.8341
Epoch 54: Train Loss 2.8796, Val Dist 13.7929
  -> Saved Best Model (Dist: 13.7929)
Epoch 55: Train Loss 2.8803, Val Dist 13.8637
Epoch 56: Train Loss 2.8801, Val Dist 13.8268
Epoch 57: Train Loss 2.8797, Val Dist 13.8168
Epoch 58: Train Loss 2.8770, Val Dist 13.8470
Epoch 59: Train Loss 2.8757, Val Dist 13.7847
  -> Saved Best Model (Dist: 13.7847)
Epoch 60: Train Loss 2.8769, Val Dist 13.8330
Epoch 61: Train Loss 2.8747, Val Dist 13.8268
Epoch 62: Train Loss 2.8751, Val Dist 13.8195
Epoch 63: Train Loss 2.8772, Val Dist 13.8035
Epoch 64: Train Loss 2.8730, Val Dist 13.7959
Epoch 65: Train Loss 2.8764, Val Dist 13.7737
  -> Saved Best Model (Dist: 13.7737)
Epoch 66: Train Loss 2.8742, Val Dist 13.7850
Epoch 67: Train Loss 2.8737, Val Dist 13.7844
Epoch 68: Train Loss 2.8724, Val Dist 13.7961
Epoch 69: Train Loss 2.8735, Val Dist 13.7888
Epoch 70: Train Loss 2.8733, Val Dist 13.7946
Epoch 71: Train Loss 2.8762, Val Dist 13.7926
Epoch 72: Train Loss 2.8735, Val Dist 13.7638
  -> Saved Best Model (Dist: 13.7638)
Epoch 73: Train Loss 2.8720, Val Dist 13.8043
Epoch 74: Train Loss 2.8739, Val Dist 13.7768
Epoch 75: Train Loss 2.8722, Val Dist 13.7876
Epoch 76: Train Loss 2.8708, Val Dist 13.8055
Epoch 77: Train Loss 2.8715, Val Dist 13.7920
Epoch 78: Train Loss 2.8742, Val Dist 13.8016
Epoch 79: Train Loss 2.8697, Val Dist 13.7934
Epoch 80: Train Loss 2.8720, Val Dist 13.7963
Epoch 81: Train Loss 2.8730, Val Dist 13.8245
Epoch 82: Train Loss 2.8733, Val Dist 13.7735
Epoch 83: Train Loss 2.8719, Val Dist 13.8050
Epoch 84: Train Loss 2.8741, Val Dist 13.8122
Epoch 85: Train Loss 2.8728, Val Dist 13.7894
Epoch 86: Train Loss 2.8708, Val Dist 13.7754
Epoch 87: Train Loss 2.8744, Val Dist 13.7961
Early Stopping
Fold 4 Finished. Best Valid Dist: 13.7638

=== Fold 5/10 ===
Pre-rendering 13965 images (Cache Enabled)...

Caching Images: 100%|██████████| 13965/13965 [00:00<00:00, 14608.50it/s]

Pre-rendering 1463 images (Cache Enabled)...

Caching Images: 100%|██████████| 1463/1463 [00:00<00:00, 13884.12it/s]

Epoch 1: Train Loss 35.4454, Val Dist 17.6003
  -> Saved Best Model (Dist: 17.6003)
Epoch 2: Train Loss 29.2539, Val Dist 16.8740
  -> Saved Best Model (Dist: 16.8740)
Epoch 3: Train Loss 28.1986, Val Dist 17.2027
Epoch 4: Train Loss 27.5750, Val Dist 16.6468
  -> Saved Best Model (Dist: 16.6468)
Epoch 5: Train Loss 27.1146, Val Dist 16.1336
  -> Saved Best Model (Dist: 16.1336)
Epoch 6: Train Loss 11.0454, Val Dist 15.8526
  -> Saved Best Model (Dist: 15.8526)
Epoch 7: Train Loss 10.9908, Val Dist 16.0517
Epoch 8: Train Loss 10.9443, Val Dist 15.8973
Epoch 9: Train Loss 10.8974, Val Dist 15.5904
  -> Saved Best Model (Dist: 15.5904)
Epoch 10: Train Loss 10.8626, Val Dist 14.9793
  -> Saved Best Model (Dist: 14.9793)
Epoch 11: Train Loss 10.8234, Val Dist 15.4892
Epoch 12: Train Loss 10.7775, Val Dist 14.7144
  -> Saved Best Model (Dist: 14.7144)
Epoch 13: Train Loss 10.9613, Val Dist 14.7534
Epoch 14: Train Loss 10.7859, Val Dist 15.5246
Epoch 15: Train Loss 10.7171, Val Dist 14.6857
  -> Saved Best Model (Dist: 14.6857)
Epoch 16: Train Loss 10.6787, Val Dist 14.6781
  -> Saved Best Model (Dist: 14.6781)
Epoch 17: Train Loss 10.6366, Val Dist 15.5895
Epoch 18: Train Loss 10.6130, Val Dist 14.7524
Epoch 19: Train Loss 10.5749, Val Dist 14.3976
  -> Saved Best Model (Dist: 14.3976)
Epoch 20: Train Loss 10.5406, Val Dist 14.8818
Epoch 21: Train Loss 3.0156, Val Dist 14.5026
Epoch 22: Train Loss 3.0016, Val Dist 14.4333
Epoch 23: Train Loss 3.0005, Val Dist 14.3666
  -> Saved Best Model (Dist: 14.3666)
Epoch 24: Train Loss 2.9963, Val Dist 14.7240
Epoch 25: Train Loss 2.9982, Val Dist 14.2737
  -> Saved Best Model (Dist: 14.2737)
Epoch 26: Train Loss 2.9906, Val Dist 14.6570
Epoch 27: Train Loss 2.9883, Val Dist 14.2804
Epoch 28: Train Loss 2.9888, Val Dist 14.2629
  -> Saved Best Model (Dist: 14.2629)
Epoch 29: Train Loss 2.9838, Val Dist 14.6398
Epoch 30: Train Loss 2.9805, Val Dist 14.3063
Epoch 31: Train Loss 2.9773, Val Dist 14.2363
  -> Saved Best Model (Dist: 14.2363)
Epoch 32: Train Loss 2.9780, Val Dist 14.2107
  -> Saved Best Model (Dist: 14.2107)
Epoch 33: Train Loss 2.9775, Val Dist 14.3366
Epoch 34: Train Loss 2.9690, Val Dist 14.3406
Epoch 35: Train Loss 2.9619, Val Dist 14.3245
Epoch 36: Train Loss 2.9625, Val Dist 14.2789
Epoch 37: Train Loss 2.9466, Val Dist 14.1569
  -> Saved Best Model (Dist: 14.1569)
Epoch 38: Train Loss 2.9413, Val Dist 14.1641
Epoch 39: Train Loss 2.9421, Val Dist 14.2513
Epoch 40: Train Loss 2.9368, Val Dist 13.9902
  -> Saved Best Model (Dist: 13.9902)
Epoch 41: Train Loss 2.9350, Val Dist 14.1105
Epoch 42: Train Loss 2.9312, Val Dist 13.9755
  -> Saved Best Model (Dist: 13.9755)
Epoch 43: Train Loss 2.9300, Val Dist 14.0067
Epoch 44: Train Loss 2.9275, Val Dist 13.9491
  -> Saved Best Model (Dist: 13.9491)
Epoch 45: Train Loss 2.9256, Val Dist 13.8684
  -> Saved Best Model (Dist: 13.8684)
Epoch 46: Train Loss 2.9241, Val Dist 13.9929
Epoch 47: Train Loss 2.9213, Val Dist 14.1198
Epoch 48: Train Loss 2.9178, Val Dist 13.9912
Epoch 49: Train Loss 2.9106, Val Dist 13.9893
Epoch 50: Train Loss 2.8819, Val Dist 13.7694
  -> Saved Best Model (Dist: 13.7694)
Epoch 51: Train Loss 2.8711, Val Dist 13.8875
Epoch 52: Train Loss 2.8674, Val Dist 13.9181
Epoch 53: Train Loss 2.8639, Val Dist 13.9099
Epoch 54: Train Loss 2.8687, Val Dist 13.8301
Epoch 55: Train Loss 2.8546, Val Dist 13.7717
Epoch 56: Train Loss 2.8513, Val Dist 13.7438
  -> Saved Best Model (Dist: 13.7438)
Epoch 57: Train Loss 2.8526, Val Dist 13.7373
  -> Saved Best Model (Dist: 13.7373)
Epoch 58: Train Loss 2.8482, Val Dist 13.6874
  -> Saved Best Model (Dist: 13.6874)
Epoch 59: Train Loss 2.8494, Val Dist 13.6503
  -> Saved Best Model (Dist: 13.6503)
Epoch 60: Train Loss 2.8478, Val Dist 13.6862
Epoch 61: Train Loss 2.8444, Val Dist 13.6391
  -> Saved Best Model (Dist: 13.6391)
Epoch 62: Train Loss 2.8454, Val Dist 13.6829
Epoch 63: Train Loss 2.8415, Val Dist 13.6018
  -> Saved Best Model (Dist: 13.6018)
Epoch 64: Train Loss 2.8431, Val Dist 13.6304
Epoch 65: Train Loss 2.8440, Val Dist 13.6536
Epoch 66: Train Loss 2.8383, Val Dist 13.6283
Epoch 67: Train Loss 2.8404, Val Dist 13.6259
Epoch 68: Train Loss 2.8389, Val Dist 13.6068
Epoch 69: Train Loss 2.8352, Val Dist 13.6245
Epoch 70: Train Loss 2.8320, Val Dist 13.6059
Epoch 71: Train Loss 2.8356, Val Dist 13.5853
  -> Saved Best Model (Dist: 13.5853)
Epoch 72: Train Loss 2.8326, Val Dist 13.6182
Epoch 73: Train Loss 2.8348, Val Dist 13.6650
Epoch 74: Train Loss 2.8307, Val Dist 13.6338
Epoch 75: Train Loss 2.8335, Val Dist 13.6148
Epoch 76: Train Loss 2.8332, Val Dist 13.5807
  -> Saved Best Model (Dist: 13.5807)
Epoch 77: Train Loss 2.8293, Val Dist 13.6013
Epoch 78: Train Loss 2.8267, Val Dist 13.5780
  -> Saved Best Model (Dist: 13.5780)
Epoch 79: Train Loss 2.8282, Val Dist 13.5681
  -> Saved Best Model (Dist: 13.5681)
Epoch 80: Train Loss 2.8303, Val Dist 13.5917
Epoch 81: Train Loss 2.8273, Val Dist 13.5740
Epoch 82: Train Loss 2.8280, Val Dist 13.5922
Epoch 83: Train Loss 2.8268, Val Dist 13.6194
Epoch 84: Train Loss 2.8268, Val Dist 13.5959
Epoch 85: Train Loss 2.8281, Val Dist 13.5797
Epoch 86: Train Loss 2.8283, Val Dist 13.5702
Epoch 87: Train Loss 2.8251, Val Dist 13.5736
Epoch 88: Train Loss 2.8273, Val Dist 13.5917
Epoch 89: Train Loss 2.8231, Val Dist 13.5845
Epoch 90: Train Loss 2.8245, Val Dist 13.5782
Epoch 91: Train Loss 2.8256, Val Dist 13.6339
Epoch 92: Train Loss 2.8251, Val Dist 13.6013
Epoch 93: Train Loss 2.8247, Val Dist 13.5727
Epoch 94: Train Loss 2.8249, Val Dist 13.5744
Early Stopping
Fold 5 Finished. Best Valid Dist: 13.5681

=== Fold 6/10 ===
Pre-rendering 13870 images (Cache Enabled)...

Caching Images: 100%|██████████| 13870/13870 [00:01<00:00, 12941.32it/s]

Pre-rendering 1558 images (Cache Enabled)...

Caching Images: 100%|██████████| 1558/1558 [00:00<00:00, 13029.68it/s]

Epoch 1: Train Loss 35.8845, Val Dist 18.0024
  -> Saved Best Model (Dist: 18.0024)
Epoch 2: Train Loss 29.4396, Val Dist 17.1279
  -> Saved Best Model (Dist: 17.1279)
Epoch 3: Train Loss 28.3532, Val Dist 16.8009
  -> Saved Best Model (Dist: 16.8009)
Epoch 4: Train Loss 27.8006, Val Dist 16.3343
  -> Saved Best Model (Dist: 16.3343)
Epoch 5: Train Loss 27.3988, Val Dist 16.5707
Epoch 6: Train Loss 11.1615, Val Dist 16.8648
Epoch 7: Train Loss 11.0927, Val Dist 15.9840
  -> Saved Best Model (Dist: 15.9840)
Epoch 8: Train Loss 11.0052, Val Dist 16.1821
Epoch 9: Train Loss 10.9588, Val Dist 16.3688
Epoch 10: Train Loss 10.8995, Val Dist 15.4566
  -> Saved Best Model (Dist: 15.4566)
Epoch 11: Train Loss 10.8363, Val Dist 15.4918
Epoch 12: Train Loss 10.7926, Val Dist 15.2172
  -> Saved Best Model (Dist: 15.2172)
Epoch 13: Train Loss 10.7602, Val Dist 15.3055
Epoch 14: Train Loss 10.7209, Val Dist 15.1535
  -> Saved Best Model (Dist: 15.1535)
Epoch 15: Train Loss 10.6773, Val Dist 14.8913
  -> Saved Best Model (Dist: 14.8913)
Epoch 16: Train Loss 10.6511, Val Dist 14.8668
  -> Saved Best Model (Dist: 14.8668)
Epoch 17: Train Loss 10.6048, Val Dist 14.7477
  -> Saved Best Model (Dist: 14.7477)
Epoch 18: Train Loss 10.5875, Val Dist 14.6762
  -> Saved Best Model (Dist: 14.6762)
Epoch 19: Train Loss 10.5463, Val Dist 15.3510
Epoch 20: Train Loss 10.5294, Val Dist 15.1626
Epoch 21: Train Loss 2.9928, Val Dist 14.6558
  -> Saved Best Model (Dist: 14.6558)
Epoch 22: Train Loss 3.0143, Val Dist 14.7336
Epoch 23: Train Loss 2.9834, Val Dist 14.6399
  -> Saved Best Model (Dist: 14.6399)
Epoch 24: Train Loss 2.9741, Val Dist 14.8644
Epoch 25: Train Loss 2.9675, Val Dist 14.5828
  -> Saved Best Model (Dist: 14.5828)
Epoch 26: Train Loss 2.9620, Val Dist 14.6499
Epoch 27: Train Loss 2.9706, Val Dist 14.7515
Epoch 28: Train Loss 2.9746, Val Dist 14.4497
  -> Saved Best Model (Dist: 14.4497)
Epoch 29: Train Loss 2.9798, Val Dist 15.1738
Epoch 30: Train Loss 2.9709, Val Dist 14.3093
  -> Saved Best Model (Dist: 14.3093)
Epoch 31: Train Loss 2.9631, Val Dist 14.2605
  -> Saved Best Model (Dist: 14.2605)
Epoch 32: Train Loss 2.9559, Val Dist 14.2973
Epoch 33: Train Loss 2.9508, Val Dist 14.2555
  -> Saved Best Model (Dist: 14.2555)
Epoch 34: Train Loss 2.9354, Val Dist 14.1356
  -> Saved Best Model (Dist: 14.1356)
Epoch 35: Train Loss 2.9315, Val Dist 14.0222
  -> Saved Best Model (Dist: 14.0222)
Epoch 36: Train Loss 2.9282, Val Dist 14.3232
Epoch 37: Train Loss 2.9263, Val Dist 14.0649
Epoch 38: Train Loss 2.9282, Val Dist 14.3196
Epoch 39: Train Loss 2.9147, Val Dist 14.1614
Epoch 40: Train Loss 2.9023, Val Dist 13.9505
  -> Saved Best Model (Dist: 13.9505)
Epoch 41: Train Loss 2.8940, Val Dist 14.0159
Epoch 42: Train Loss 2.8933, Val Dist 13.9997
Epoch 43: Train Loss 2.8921, Val Dist 14.0086
Epoch 44: Train Loss 2.8899, Val Dist 13.9709
Epoch 45: Train Loss 2.8773, Val Dist 13.8144
  -> Saved Best Model (Dist: 13.8144)
Epoch 46: Train Loss 2.8761, Val Dist 13.8965
Epoch 47: Train Loss 2.8814, Val Dist 13.8831
Epoch 48: Train Loss 2.8762, Val Dist 13.8477
Epoch 49: Train Loss 2.8734, Val Dist 13.9007
Epoch 50: Train Loss 2.8665, Val Dist 13.7824
  -> Saved Best Model (Dist: 13.7824)
Epoch 51: Train Loss 2.8621, Val Dist 13.8530
Epoch 52: Train Loss 2.8639, Val Dist 13.8258
Epoch 53: Train Loss 2.8625, Val Dist 13.7722
  -> Saved Best Model (Dist: 13.7722)
Epoch 54: Train Loss 2.8611, Val Dist 13.7985
Epoch 55: Train Loss 2.8573, Val Dist 13.8481
Epoch 56: Train Loss 2.8614, Val Dist 13.7375
  -> Saved Best Model (Dist: 13.7375)
Epoch 57: Train Loss 2.8582, Val Dist 13.7574
Epoch 58: Train Loss 2.8563, Val Dist 13.7890
Epoch 59: Train Loss 2.8584, Val Dist 13.7538
Epoch 60: Train Loss 2.8549, Val Dist 13.7990
Epoch 61: Train Loss 2.8552, Val Dist 13.8217
Epoch 62: Train Loss 2.8509, Val Dist 13.7576
Epoch 63: Train Loss 2.8507, Val Dist 13.8799
Epoch 64: Train Loss 2.8509, Val Dist 13.7374
  -> Saved Best Model (Dist: 13.7374)
Epoch 65: Train Loss 2.8514, Val Dist 13.7337
  -> Saved Best Model (Dist: 13.7337)
Epoch 66: Train Loss 2.8499, Val Dist 13.7328
  -> Saved Best Model (Dist: 13.7328)
Epoch 67: Train Loss 2.8488, Val Dist 13.7653
Epoch 68: Train Loss 2.8498, Val Dist 13.7591
Epoch 69: Train Loss 2.8511, Val Dist 13.7506
Epoch 70: Train Loss 2.8490, Val Dist 13.7985
Epoch 71: Train Loss 2.8489, Val Dist 13.7581
Epoch 72: Train Loss 2.8463, Val Dist 13.7415
Epoch 73: Train Loss 2.8483, Val Dist 13.7448
Epoch 74: Train Loss 2.8450, Val Dist 13.7480
Epoch 75: Train Loss 2.8454, Val Dist 13.7847
Epoch 76: Train Loss 2.8479, Val Dist 13.7834
Epoch 77: Train Loss 2.8475, Val Dist 13.7900
Epoch 78: Train Loss 2.8470, Val Dist 13.7342
Epoch 79: Train Loss 2.8459, Val Dist 13.7249
  -> Saved Best Model (Dist: 13.7249)
Epoch 80: Train Loss 2.8471, Val Dist 13.7303
Epoch 81: Train Loss 2.8468, Val Dist 13.7811
Epoch 82: Train Loss 2.8488, Val Dist 13.7642
Epoch 83: Train Loss 2.8480, Val Dist 13.7592
Epoch 84: Train Loss 2.8457, Val Dist 13.7595
Epoch 85: Train Loss 2.8482, Val Dist 13.7912
Epoch 86: Train Loss 2.8463, Val Dist 13.7848
Epoch 87: Train Loss 2.8463, Val Dist 13.7705
Epoch 88: Train Loss 2.8469, Val Dist 13.7706
Epoch 89: Train Loss 2.8462, Val Dist 13.8022
Epoch 90: Train Loss 2.8470, Val Dist 13.7795
Epoch 91: Train Loss 2.8451, Val Dist 13.7533
Epoch 92: Train Loss 2.8464, Val Dist 13.7593
Epoch 93: Train Loss 2.8472, Val Dist 13.7622
Epoch 94: Train Loss 2.8464, Val Dist 13.7785
Early Stopping
Fold 6 Finished. Best Valid Dist: 13.7249

=== Fold 7/10 ===
Pre-rendering 13918 images (Cache Enabled)...

Caching Images: 100%|██████████| 13918/13918 [00:01<00:00, 12918.57it/s]

Pre-rendering 1510 images (Cache Enabled)...

Caching Images: 100%|██████████| 1510/1510 [00:00<00:00, 7739.76it/s]

Epoch 1: Train Loss 35.7897, Val Dist 17.7311
  -> Saved Best Model (Dist: 17.7311)
Epoch 2: Train Loss 29.3270, Val Dist 17.2610
  -> Saved Best Model (Dist: 17.2610)
Epoch 3: Train Loss 28.3464, Val Dist 17.4022
Epoch 4: Train Loss 27.7928, Val Dist 16.4865
  -> Saved Best Model (Dist: 16.4865)
Epoch 5: Train Loss 27.3575, Val Dist 16.1883
  -> Saved Best Model (Dist: 16.1883)
Epoch 6: Train Loss 11.1737, Val Dist 16.5791
Epoch 7: Train Loss 11.0916, Val Dist 16.4107
Epoch 8: Train Loss 11.0265, Val Dist 16.3223
Epoch 9: Train Loss 10.9747, Val Dist 15.7768
  -> Saved Best Model (Dist: 15.7768)
Epoch 10: Train Loss 10.9041, Val Dist 15.2151
  -> Saved Best Model (Dist: 15.2151)
Epoch 11: Train Loss 10.8623, Val Dist 15.0587
  -> Saved Best Model (Dist: 15.0587)
Epoch 12: Train Loss 10.8150, Val Dist 14.9999
  -> Saved Best Model (Dist: 14.9999)
Epoch 13: Train Loss 10.7708, Val Dist 14.9731
  -> Saved Best Model (Dist: 14.9731)
Epoch 14: Train Loss 10.7274, Val Dist 14.8986
  -> Saved Best Model (Dist: 14.8986)
Epoch 15: Train Loss 10.6902, Val Dist 14.7036
  -> Saved Best Model (Dist: 14.7036)
Epoch 16: Train Loss 10.6650, Val Dist 15.2264
Epoch 17: Train Loss 10.6351, Val Dist 15.6827
Epoch 18: Train Loss 10.6058, Val Dist 14.5667
  -> Saved Best Model (Dist: 14.5667)
Epoch 19: Train Loss 10.5625, Val Dist 14.4276
  -> Saved Best Model (Dist: 14.4276)
Epoch 20: Train Loss 10.5451, Val Dist 14.3694
  -> Saved Best Model (Dist: 14.3694)
Epoch 21: Train Loss 3.0081, Val Dist 15.9921
Epoch 22: Train Loss 3.0049, Val Dist 14.6576
Epoch 23: Train Loss 2.9966, Val Dist 14.9071
Epoch 24: Train Loss 2.9981, Val Dist 14.9581
Epoch 25: Train Loss 2.9748, Val Dist 14.2811
  -> Saved Best Model (Dist: 14.2811)
Epoch 26: Train Loss 2.9607, Val Dist 14.3372
Epoch 27: Train Loss 2.9534, Val Dist 14.3518
Epoch 28: Train Loss 2.9543, Val Dist 14.2638
  -> Saved Best Model (Dist: 14.2638)
Epoch 29: Train Loss 2.9487, Val Dist 14.2002
  -> Saved Best Model (Dist: 14.2002)
Epoch 30: Train Loss 2.9580, Val Dist 14.7073
Epoch 31: Train Loss 2.9573, Val Dist 14.2773
Epoch 32: Train Loss 2.9473, Val Dist 14.0995
  -> Saved Best Model (Dist: 14.0995)
Epoch 33: Train Loss 2.9402, Val Dist 14.0348
  -> Saved Best Model (Dist: 14.0348)
Epoch 34: Train Loss 2.9360, Val Dist 14.0132
  -> Saved Best Model (Dist: 14.0132)
Epoch 35: Train Loss 2.9313, Val Dist 14.2245
Epoch 36: Train Loss 2.9367, Val Dist 13.9772
  -> Saved Best Model (Dist: 13.9772)
Epoch 37: Train Loss 2.9281, Val Dist 14.0267
Epoch 38: Train Loss 2.9238, Val Dist 13.9546
  -> Saved Best Model (Dist: 13.9546)
Epoch 39: Train Loss 2.9239, Val Dist 13.8894
  -> Saved Best Model (Dist: 13.8894)
Epoch 40: Train Loss 2.9182, Val Dist 14.2482
Epoch 41: Train Loss 2.9168, Val Dist 13.9405
Epoch 42: Train Loss 2.9114, Val Dist 14.1163
Epoch 43: Train Loss 2.9108, Val Dist 14.0388
Epoch 44: Train Loss 2.8981, Val Dist 13.7990
  -> Saved Best Model (Dist: 13.7990)
Epoch 45: Train Loss 2.8963, Val Dist 13.8180
Epoch 46: Train Loss 2.8927, Val Dist 13.7867
  -> Saved Best Model (Dist: 13.7867)
Epoch 47: Train Loss 2.8943, Val Dist 13.7870
Epoch 48: Train Loss 2.8906, Val Dist 13.8567
Epoch 49: Train Loss 2.8909, Val Dist 13.8576
Epoch 50: Train Loss 2.8860, Val Dist 13.8519
Epoch 51: Train Loss 2.8827, Val Dist 13.8226
Epoch 52: Train Loss 2.8818, Val Dist 13.7790
  -> Saved Best Model (Dist: 13.7790)
Epoch 53: Train Loss 2.8775, Val Dist 13.8306
Epoch 54: Train Loss 2.8828, Val Dist 13.7142
  -> Saved Best Model (Dist: 13.7142)
Epoch 55: Train Loss 2.8776, Val Dist 13.9190
Epoch 56: Train Loss 2.8822, Val Dist 13.8354
Epoch 57: Train Loss 2.8763, Val Dist 13.8238
Epoch 58: Train Loss 2.8759, Val Dist 13.7306
Epoch 59: Train Loss 2.8693, Val Dist 13.7579
Epoch 60: Train Loss 2.8725, Val Dist 13.7071
  -> Saved Best Model (Dist: 13.7071)
Epoch 61: Train Loss 2.8686, Val Dist 13.7118
Epoch 62: Train Loss 2.8699, Val Dist 13.7137
Epoch 63: Train Loss 2.8678, Val Dist 13.6789
  -> Saved Best Model (Dist: 13.6789)
Epoch 64: Train Loss 2.8686, Val Dist 13.7785
Epoch 65: Train Loss 2.8714, Val Dist 13.7073
Epoch 66: Train Loss 2.8688, Val Dist 13.7526
Epoch 67: Train Loss 2.8662, Val Dist 13.6660
  -> Saved Best Model (Dist: 13.6660)
Epoch 68: Train Loss 2.8673, Val Dist 13.7092
Epoch 69: Train Loss 2.8635, Val Dist 13.7698
Epoch 70: Train Loss 2.8697, Val Dist 13.8392
Epoch 71: Train Loss 2.8660, Val Dist 13.8270
Epoch 72: Train Loss 2.8612, Val Dist 13.7435
Epoch 73: Train Loss 2.8655, Val Dist 13.7673
Epoch 74: Train Loss 2.8636, Val Dist 13.7103
Epoch 75: Train Loss 2.8612, Val Dist 13.7147
Epoch 76: Train Loss 2.8617, Val Dist 13.7056
Epoch 77: Train Loss 2.8617, Val Dist 13.7158
Epoch 78: Train Loss 2.8606, Val Dist 13.7462
Epoch 79: Train Loss 2.8614, Val Dist 13.7419
Epoch 80: Train Loss 2.8602, Val Dist 13.7235
Epoch 81: Train Loss 2.8653, Val Dist 13.6792
Epoch 82: Train Loss 2.8612, Val Dist 13.7370
Early Stopping
Fold 7 Finished. Best Valid Dist: 13.6660

=== Fold 8/10 ===
Pre-rendering 13910 images (Cache Enabled)...

Caching Images: 100%|██████████| 13910/13910 [00:01<00:00, 13253.47it/s]

Pre-rendering 1518 images (Cache Enabled)...

Caching Images: 100%|██████████| 1518/1518 [00:00<00:00, 12197.70it/s]

Epoch 1: Train Loss 37.2009, Val Dist 17.7013
  -> Saved Best Model (Dist: 17.7013)
Epoch 2: Train Loss 29.8409, Val Dist 17.8101
Epoch 3: Train Loss 28.3681, Val Dist 16.8948
  -> Saved Best Model (Dist: 16.8948)
Epoch 4: Train Loss 27.7527, Val Dist 16.8235
  -> Saved Best Model (Dist: 16.8235)
Epoch 5: Train Loss 27.3282, Val Dist 16.5871
  -> Saved Best Model (Dist: 16.5871)
Epoch 6: Train Loss 11.1503, Val Dist 16.2641
  -> Saved Best Model (Dist: 16.2641)
Epoch 7: Train Loss 11.0761, Val Dist 16.7981
Epoch 8: Train Loss 11.0188, Val Dist 16.1256
  -> Saved Best Model (Dist: 16.1256)
Epoch 9: Train Loss 10.9532, Val Dist 16.1069
  -> Saved Best Model (Dist: 16.1069)
Epoch 10: Train Loss 10.8930, Val Dist 16.1270
Epoch 11: Train Loss 10.8491, Val Dist 15.2311
  -> Saved Best Model (Dist: 15.2311)
Epoch 12: Train Loss 10.8017, Val Dist 15.6095
Epoch 13: Train Loss 10.7623, Val Dist 15.2446
Epoch 14: Train Loss 10.7230, Val Dist 15.2321
Epoch 15: Train Loss 10.6785, Val Dist 14.8861
  -> Saved Best Model (Dist: 14.8861)
Epoch 16: Train Loss 10.6310, Val Dist 14.8792
  -> Saved Best Model (Dist: 14.8792)
Epoch 17: Train Loss 10.6234, Val Dist 15.0882
Epoch 18: Train Loss 10.5741, Val Dist 14.5699
  -> Saved Best Model (Dist: 14.5699)
Epoch 19: Train Loss 10.5537, Val Dist 14.8935
Epoch 20: Train Loss 10.5107, Val Dist 14.7349
Epoch 21: Train Loss 2.9921, Val Dist 14.5770
Epoch 22: Train Loss 2.9760, Val Dist 14.7408
Epoch 23: Train Loss 2.9647, Val Dist 14.1085
  -> Saved Best Model (Dist: 14.1085)
Epoch 24: Train Loss 2.9624, Val Dist 14.1378
Epoch 25: Train Loss 2.9587, Val Dist 14.1233
Epoch 26: Train Loss 2.9530, Val Dist 14.1745
Epoch 27: Train Loss 2.9549, Val Dist 14.0934
  -> Saved Best Model (Dist: 14.0934)
Epoch 28: Train Loss 2.9496, Val Dist 14.1890
Epoch 29: Train Loss 2.9449, Val Dist 14.2154
Epoch 30: Train Loss 2.9387, Val Dist 14.1823
Epoch 31: Train Loss 2.9400, Val Dist 14.0888
  -> Saved Best Model (Dist: 14.0888)
Epoch 32: Train Loss 2.9326, Val Dist 14.4985
Epoch 33: Train Loss 2.9432, Val Dist 14.2247
Epoch 34: Train Loss 2.9259, Val Dist 14.1368
Epoch 35: Train Loss 2.9275, Val Dist 13.9238
  -> Saved Best Model (Dist: 13.9238)
Epoch 36: Train Loss 2.9271, Val Dist 13.9547
Epoch 37: Train Loss 2.9229, Val Dist 13.9485
Epoch 38: Train Loss 2.9263, Val Dist 13.9425
Epoch 39: Train Loss 2.9166, Val Dist 14.0235
Epoch 40: Train Loss 2.9052, Val Dist 13.8222
  -> Saved Best Model (Dist: 13.8222)
Epoch 41: Train Loss 2.8987, Val Dist 13.8076
  -> Saved Best Model (Dist: 13.8076)
Epoch 42: Train Loss 2.8973, Val Dist 13.9539
Epoch 43: Train Loss 2.8991, Val Dist 13.8381
Epoch 44: Train Loss 2.8964, Val Dist 13.7955
  -> Saved Best Model (Dist: 13.7955)
Epoch 45: Train Loss 2.8941, Val Dist 13.8272
Epoch 46: Train Loss 2.8907, Val Dist 13.7748
  -> Saved Best Model (Dist: 13.7748)
Epoch 47: Train Loss 2.8885, Val Dist 13.7555
  -> Saved Best Model (Dist: 13.7555)
Epoch 48: Train Loss 2.8900, Val Dist 13.7622
Epoch 49: Train Loss 2.8875, Val Dist 13.8200
Epoch 50: Train Loss 2.8875, Val Dist 13.7088
  -> Saved Best Model (Dist: 13.7088)
Epoch 51: Train Loss 2.8857, Val Dist 13.8197
Epoch 52: Train Loss 2.8817, Val Dist 13.6369
  -> Saved Best Model (Dist: 13.6369)
Epoch 53: Train Loss 2.8794, Val Dist 13.7231
Epoch 54: Train Loss 2.8775, Val Dist 13.6620
Epoch 55: Train Loss 2.8762, Val Dist 13.8115
Epoch 56: Train Loss 2.8791, Val Dist 13.7458
Epoch 57: Train Loss 2.8732, Val Dist 13.7467
Epoch 58: Train Loss 2.8663, Val Dist 13.7362
Epoch 59: Train Loss 2.8655, Val Dist 13.6975
Epoch 60: Train Loss 2.8667, Val Dist 13.7066
Epoch 61: Train Loss 2.8623, Val Dist 13.6363
  -> Saved Best Model (Dist: 13.6363)
Epoch 62: Train Loss 2.8594, Val Dist 13.6555
Epoch 63: Train Loss 2.8628, Val Dist 13.7266
Epoch 64: Train Loss 2.8603, Val Dist 13.6620
Epoch 65: Train Loss 2.8605, Val Dist 13.6809
Epoch 66: Train Loss 2.8577, Val Dist 13.6612
Epoch 67: Train Loss 2.8597, Val Dist 13.6975
Epoch 68: Train Loss 2.8572, Val Dist 13.6550
Epoch 69: Train Loss 2.8587, Val Dist 13.6658
Epoch 70: Train Loss 2.8581, Val Dist 13.6824
Epoch 71: Train Loss 2.8573, Val Dist 13.6836
Epoch 72: Train Loss 2.8582, Val Dist 13.6340
  -> Saved Best Model (Dist: 13.6340)
Epoch 73: Train Loss 2.8570, Val Dist 13.6550
Epoch 74: Train Loss 2.8557, Val Dist 13.6099
  -> Saved Best Model (Dist: 13.6099)
Epoch 75: Train Loss 2.8594, Val Dist 13.6426
Epoch 76: Train Loss 2.8547, Val Dist 13.6698
Epoch 77: Train Loss 2.8576, Val Dist 13.6763
Epoch 78: Train Loss 2.8540, Val Dist 13.6459
Epoch 79: Train Loss 2.8564, Val Dist 13.6301
Epoch 80: Train Loss 2.8568, Val Dist 13.6825
Epoch 81: Train Loss 2.8568, Val Dist 13.6206
Epoch 82: Train Loss 2.8554, Val Dist 13.6191
Epoch 83: Train Loss 2.8536, Val Dist 13.6329
Epoch 84: Train Loss 2.8553, Val Dist 13.6506
Epoch 85: Train Loss 2.8556, Val Dist 13.6495
Epoch 86: Train Loss 2.8554, Val Dist 13.6561
Epoch 87: Train Loss 2.8530, Val Dist 13.6617
Epoch 88: Train Loss 2.8542, Val Dist 13.6456
Epoch 89: Train Loss 2.8513, Val Dist 13.6527
Early Stopping
Fold 8 Finished. Best Valid Dist: 13.6099

=== Fold 9/10 ===
Pre-rendering 13828 images (Cache Enabled)...

Caching Images: 100%|██████████| 13828/13828 [00:01<00:00, 13046.04it/s]

Pre-rendering 1600 images (Cache Enabled)...

Caching Images: 100%|██████████| 1600/1600 [00:00<00:00, 14575.23it/s]

Epoch 1: Train Loss 36.9517, Val Dist 18.1283
  -> Saved Best Model (Dist: 18.1283)
Epoch 2: Train Loss 29.8633, Val Dist 17.5511
  -> Saved Best Model (Dist: 17.5511)
Epoch 3: Train Loss 28.4078, Val Dist 17.6600
Epoch 4: Train Loss 27.7559, Val Dist 17.3214
  -> Saved Best Model (Dist: 17.3214)
Epoch 5: Train Loss 27.3257, Val Dist 17.1385
  -> Saved Best Model (Dist: 17.1385)
Epoch 6: Train Loss 11.1498, Val Dist 16.6202
  -> Saved Best Model (Dist: 16.6202)
Epoch 7: Train Loss 11.1063, Val Dist 17.0030
Epoch 8: Train Loss 11.0524, Val Dist 16.3847
  -> Saved Best Model (Dist: 16.3847)
Epoch 9: Train Loss 10.9913, Val Dist 16.1961
  -> Saved Best Model (Dist: 16.1961)
Epoch 10: Train Loss 10.9334, Val Dist 16.0984
  -> Saved Best Model (Dist: 16.0984)
Epoch 11: Train Loss 10.9242, Val Dist 16.3542
Epoch 12: Train Loss 10.8603, Val Dist 16.0700
  -> Saved Best Model (Dist: 16.0700)
Epoch 13: Train Loss 10.8025, Val Dist 15.8452
  -> Saved Best Model (Dist: 15.8452)
Epoch 14: Train Loss 10.7646, Val Dist 15.8032
  -> Saved Best Model (Dist: 15.8032)
Epoch 15: Train Loss 10.7276, Val Dist 15.6636
  -> Saved Best Model (Dist: 15.6636)
Epoch 16: Train Loss 10.6863, Val Dist 15.5912
  -> Saved Best Model (Dist: 15.5912)
Epoch 17: Train Loss 10.6589, Val Dist 15.3780
  -> Saved Best Model (Dist: 15.3780)
Epoch 18: Train Loss 10.6221, Val Dist 15.3703
  -> Saved Best Model (Dist: 15.3703)
Epoch 19: Train Loss 10.5966, Val Dist 15.6198
Epoch 20: Train Loss 10.5562, Val Dist 15.4186
Epoch 21: Train Loss 3.0196, Val Dist 15.2071
  -> Saved Best Model (Dist: 15.2071)
Epoch 22: Train Loss 3.0085, Val Dist 15.7278
Epoch 23: Train Loss 3.0221, Val Dist 15.2747
Epoch 24: Train Loss 3.0115, Val Dist 15.0436
  -> Saved Best Model (Dist: 15.0436)
Epoch 25: Train Loss 3.0028, Val Dist 15.0668
Epoch 26: Train Loss 2.9873, Val Dist 15.1682
Epoch 27: Train Loss 2.9868, Val Dist 14.9556
  -> Saved Best Model (Dist: 14.9556)
Epoch 28: Train Loss 2.9794, Val Dist 14.8564
  -> Saved Best Model (Dist: 14.8564)
Epoch 29: Train Loss 2.9853, Val Dist 14.8159
  -> Saved Best Model (Dist: 14.8159)
Epoch 30: Train Loss 2.9746, Val Dist 14.8060
  -> Saved Best Model (Dist: 14.8060)
Epoch 31: Train Loss 2.9862, Val Dist 14.8708
Epoch 32: Train Loss 2.9605, Val Dist 14.8552
Epoch 33: Train Loss 2.9688, Val Dist 14.8886
Epoch 34: Train Loss 2.9518, Val Dist 15.0478
Epoch 35: Train Loss 2.9394, Val Dist 14.5567
  -> Saved Best Model (Dist: 14.5567)
Epoch 36: Train Loss 2.9386, Val Dist 14.5830
Epoch 37: Train Loss 2.9261, Val Dist 14.6477
Epoch 38: Train Loss 2.9295, Val Dist 14.7544
Epoch 39: Train Loss 2.9305, Val Dist 14.6239
Epoch 40: Train Loss 2.9115, Val Dist 14.5314
  -> Saved Best Model (Dist: 14.5314)
Epoch 41: Train Loss 2.9094, Val Dist 14.6573
Epoch 42: Train Loss 2.9043, Val Dist 14.5050
  -> Saved Best Model (Dist: 14.5050)
Epoch 43: Train Loss 2.9030, Val Dist 14.4823
  -> Saved Best Model (Dist: 14.4823)
Epoch 44: Train Loss 2.9025, Val Dist 14.4471
  -> Saved Best Model (Dist: 14.4471)
Epoch 45: Train Loss 2.9020, Val Dist 14.4397
  -> Saved Best Model (Dist: 14.4397)
Epoch 46: Train Loss 2.9016, Val Dist 14.4190
  -> Saved Best Model (Dist: 14.4190)
Epoch 47: Train Loss 2.8965, Val Dist 14.3996
  -> Saved Best Model (Dist: 14.3996)
Epoch 48: Train Loss 2.8974, Val Dist 14.4951
Epoch 49: Train Loss 2.8947, Val Dist 14.3419
  -> Saved Best Model (Dist: 14.3419)
Epoch 50: Train Loss 2.8910, Val Dist 14.4296
Epoch 51: Train Loss 2.8928, Val Dist 14.4328
Epoch 52: Train Loss 2.8886, Val Dist 14.3588
Epoch 53: Train Loss 2.8886, Val Dist 14.4234
Epoch 54: Train Loss 2.8886, Val Dist 14.4482
Epoch 55: Train Loss 2.8807, Val Dist 14.3214
  -> Saved Best Model (Dist: 14.3214)
Epoch 56: Train Loss 2.8805, Val Dist 14.3218
Epoch 57: Train Loss 2.8818, Val Dist 14.3651
Epoch 58: Train Loss 2.8770, Val Dist 14.3271
Epoch 59: Train Loss 2.8774, Val Dist 14.3263
Epoch 60: Train Loss 2.8768, Val Dist 14.2984
  -> Saved Best Model (Dist: 14.2984)
Epoch 61: Train Loss 2.8716, Val Dist 14.2987
Epoch 62: Train Loss 2.8717, Val Dist 14.3348
Epoch 63: Train Loss 2.8744, Val Dist 14.2796
  -> Saved Best Model (Dist: 14.2796)
Epoch 64: Train Loss 2.8715, Val Dist 14.3352
Epoch 65: Train Loss 2.8710, Val Dist 14.2746
  -> Saved Best Model (Dist: 14.2746)
Epoch 66: Train Loss 2.8668, Val Dist 14.2801
Epoch 67: Train Loss 2.8708, Val Dist 14.2786
Epoch 68: Train Loss 2.8695, Val Dist 14.2673
  -> Saved Best Model (Dist: 14.2673)
Epoch 69: Train Loss 2.8681, Val Dist 14.3054
Epoch 70: Train Loss 2.8700, Val Dist 14.2799
Epoch 71: Train Loss 2.8688, Val Dist 14.2848
Epoch 72: Train Loss 2.8658, Val Dist 14.2967
Epoch 73: Train Loss 2.8676, Val Dist 14.3212
Epoch 74: Train Loss 2.8675, Val Dist 14.3256
Epoch 75: Train Loss 2.8673, Val Dist 14.3164
Epoch 76: Train Loss 2.8678, Val Dist 14.2719
Epoch 77: Train Loss 2.8638, Val Dist 14.3265
Epoch 78: Train Loss 2.8683, Val Dist 14.3012
Epoch 79: Train Loss 2.8664, Val Dist 14.3358
Epoch 80: Train Loss 2.8643, Val Dist 14.2562
  -> Saved Best Model (Dist: 14.2562)
Epoch 81: Train Loss 2.8632, Val Dist 14.2754
Epoch 82: Train Loss 2.8675, Val Dist 14.2828
Epoch 83: Train Loss 2.8664, Val Dist 14.3225
Epoch 84: Train Loss 2.8637, Val Dist 14.2646
Epoch 85: Train Loss 2.8637, Val Dist 14.2140
  -> Saved Best Model (Dist: 14.2140)
Epoch 86: Train Loss 2.8647, Val Dist 14.2517
Epoch 87: Train Loss 2.8609, Val Dist 14.2718
Epoch 88: Train Loss 2.8649, Val Dist 14.2772
Epoch 89: Train Loss 2.8610, Val Dist 14.3199
Epoch 90: Train Loss 2.8640, Val Dist 14.2639
Epoch 91: Train Loss 2.8628, Val Dist 14.3148
Epoch 92: Train Loss 2.8604, Val Dist 14.2726
Epoch 93: Train Loss 2.8628, Val Dist 14.2514
Epoch 94: Train Loss 2.8612, Val Dist 14.2951
Epoch 95: Train Loss 2.8645, Val Dist 14.2782
Epoch 96: Train Loss 2.8606, Val Dist 14.3236
Epoch 97: Train Loss 2.8627, Val Dist 14.2690
Epoch 98: Train Loss 2.8666, Val Dist 14.3277
Epoch 99: Train Loss 2.8656, Val Dist 14.2743
Epoch 100: Train Loss 2.8644, Val Dist 14.2793
Early Stopping
Fold 9 Finished. Best Valid Dist: 14.2140

=== Fold 10/10 ===
Pre-rendering 13858 images (Cache Enabled)...

Caching Images: 100%|██████████| 13858/13858 [00:00<00:00, 14306.12it/s]

Pre-rendering 1570 images (Cache Enabled)...

Caching Images: 100%|██████████| 1570/1570 [00:00<00:00, 13764.69it/s]

Epoch 1: Train Loss 36.5008, Val Dist 17.9561
  -> Saved Best Model (Dist: 17.9561)
Epoch 2: Train Loss 29.7039, Val Dist 16.9218
  -> Saved Best Model (Dist: 16.9218)
Epoch 3: Train Loss 28.4259, Val Dist 16.4428
  -> Saved Best Model (Dist: 16.4428)
Epoch 4: Train Loss 27.7940, Val Dist 16.7781
Epoch 5: Train Loss 27.3378, Val Dist 16.5967
Epoch 6: Train Loss 11.1408, Val Dist 16.1125
  -> Saved Best Model (Dist: 16.1125)
Epoch 7: Train Loss 11.0693, Val Dist 16.0684
  -> Saved Best Model (Dist: 16.0684)
Epoch 8: Train Loss 11.0003, Val Dist 15.8142
  -> Saved Best Model (Dist: 15.8142)
Epoch 9: Train Loss 10.9446, Val Dist 15.9056
Epoch 10: Train Loss 10.9057, Val Dist 16.2241
Epoch 11: Train Loss 10.8478, Val Dist 15.4572
  -> Saved Best Model (Dist: 15.4572)
Epoch 12: Train Loss 10.7975, Val Dist 15.3758
  -> Saved Best Model (Dist: 15.3758)
Epoch 13: Train Loss 10.7586, Val Dist 15.0524
  -> Saved Best Model (Dist: 15.0524)
Epoch 14: Train Loss 10.7501, Val Dist 15.3505
Epoch 15: Train Loss 10.6974, Val Dist 14.9555
  -> Saved Best Model (Dist: 14.9555)
Epoch 16: Train Loss 10.6612, Val Dist 14.8092
  -> Saved Best Model (Dist: 14.8092)
Epoch 17: Train Loss 10.6159, Val Dist 14.9210
Epoch 18: Train Loss 10.5914, Val Dist 14.9261
Epoch 19: Train Loss 10.5645, Val Dist 14.8679
Epoch 20: Train Loss 10.5404, Val Dist 14.5049
  -> Saved Best Model (Dist: 14.5049)
Epoch 21: Train Loss 2.9922, Val Dist 14.5029
  -> Saved Best Model (Dist: 14.5029)
Epoch 22: Train Loss 2.9991, Val Dist 15.1140
Epoch 23: Train Loss 2.9924, Val Dist 14.6239
Epoch 24: Train Loss 2.9779, Val Dist 14.6784
Epoch 25: Train Loss 2.9727, Val Dist 14.4557
  -> Saved Best Model (Dist: 14.4557)
Epoch 26: Train Loss 2.9703, Val Dist 14.4603
Epoch 27: Train Loss 2.9670, Val Dist 14.4436
  -> Saved Best Model (Dist: 14.4436)
Epoch 28: Train Loss 2.9589, Val Dist 14.5800
Epoch 29: Train Loss 2.9581, Val Dist 14.4310
  -> Saved Best Model (Dist: 14.4310)
Epoch 30: Train Loss 2.9582, Val Dist 14.6465
Epoch 31: Train Loss 2.9597, Val Dist 14.2805
  -> Saved Best Model (Dist: 14.2805)
Epoch 32: Train Loss 2.9553, Val Dist 14.4444
Epoch 33: Train Loss 2.9751, Val Dist 14.8288
Epoch 34: Train Loss 2.9618, Val Dist 14.3394
Epoch 35: Train Loss 2.9403, Val Dist 14.6419
Epoch 36: Train Loss 2.9231, Val Dist 14.1391
  -> Saved Best Model (Dist: 14.1391)
Epoch 37: Train Loss 2.9151, Val Dist 14.0957
  -> Saved Best Model (Dist: 14.0957)
Epoch 38: Train Loss 2.9120, Val Dist 14.0961
Epoch 39: Train Loss 2.9096, Val Dist 14.2738
Epoch 40: Train Loss 2.9103, Val Dist 14.0308
  -> Saved Best Model (Dist: 14.0308)
Epoch 41: Train Loss 2.9061, Val Dist 14.0853
Epoch 42: Train Loss 2.9003, Val Dist 13.9710
  -> Saved Best Model (Dist: 13.9710)
Epoch 43: Train Loss 2.8998, Val Dist 13.9250
  -> Saved Best Model (Dist: 13.9250)
Epoch 44: Train Loss 2.8994, Val Dist 13.9948
Epoch 45: Train Loss 2.8920, Val Dist 14.0702
Epoch 46: Train Loss 2.8940, Val Dist 13.9620
Epoch 47: Train Loss 2.8970, Val Dist 13.9416
Epoch 48: Train Loss 2.8826, Val Dist 13.8336
  -> Saved Best Model (Dist: 13.8336)
Epoch 49: Train Loss 2.8787, Val Dist 13.8544
Epoch 50: Train Loss 2.8737, Val Dist 13.9005
Epoch 51: Train Loss 2.8736, Val Dist 13.8455
Epoch 52: Train Loss 2.8757, Val Dist 13.7963
  -> Saved Best Model (Dist: 13.7963)
Epoch 53: Train Loss 2.8713, Val Dist 13.7816
  -> Saved Best Model (Dist: 13.7816)
Epoch 54: Train Loss 2.8671, Val Dist 13.8536
Epoch 55: Train Loss 2.8667, Val Dist 13.8698
Epoch 56: Train Loss 2.8649, Val Dist 13.7968
Epoch 57: Train Loss 2.8655, Val Dist 13.8295
Epoch 58: Train Loss 2.8577, Val Dist 13.7683
  -> Saved Best Model (Dist: 13.7683)
Epoch 59: Train Loss 2.8567, Val Dist 13.7700
Epoch 60: Train Loss 2.8564, Val Dist 13.8590
Epoch 61: Train Loss 2.8542, Val Dist 13.8258
Epoch 62: Train Loss 2.8518, Val Dist 13.8376
Epoch 63: Train Loss 2.8504, Val Dist 13.7818
Epoch 64: Train Loss 2.8514, Val Dist 13.8021
Epoch 65: Train Loss 2.8492, Val Dist 13.7974
Epoch 66: Train Loss 2.8495, Val Dist 13.7269
  -> Saved Best Model (Dist: 13.7269)
Epoch 67: Train Loss 2.8484, Val Dist 13.7376
Epoch 68: Train Loss 2.8464, Val Dist 13.7548
Epoch 69: Train Loss 2.8469, Val Dist 13.7753
Epoch 70: Train Loss 2.8452, Val Dist 13.7490
Epoch 71: Train Loss 2.8444, Val Dist 13.7342
Epoch 72: Train Loss 2.8451, Val Dist 13.7553
Epoch 73: Train Loss 2.8438, Val Dist 13.7705
Epoch 74: Train Loss 2.8463, Val Dist 13.7499
Epoch 75: Train Loss 2.8417, Val Dist 13.7627
Epoch 76: Train Loss 2.8439, Val Dist 13.7541
Epoch 77: Train Loss 2.8415, Val Dist 13.7570
Epoch 78: Train Loss 2.8419, Val Dist 13.7602
Epoch 79: Train Loss 2.8429, Val Dist 13.7547
Epoch 80: Train Loss 2.8413, Val Dist 13.7729
Epoch 81: Train Loss 2.8411, Val Dist 13.7552
Early Stopping
Fold 10 Finished. Best Valid Dist: 13.7269

========================================
           FINAL FOLD SCORES
========================================
Fold 01: 13.6538
Fold 02: 13.5301
Fold 03: 13.5851
Fold 04: 13.7638
Fold 05: 13.5681
Fold 06: 13.7249
Fold 07: 13.6660
Fold 08: 13.6099
Fold 09: 14.2140
Fold 10: 13.7269
----------------------------------------
AVERAGE: 13.7043
========================================

[np.float64(13.653775840786698),
 np.float64(13.530112266803945),
 np.float64(13.585134064930466),
 np.float64(13.763825114665499),
 np.float64(13.568061811524826),
 np.float64(13.724868084352737),
 np.float64(13.665983011036777),
 np.float64(13.609942018543851),
 np.float64(14.213962780144627),
 np.float64(13.726858415210453)]

## 5. Inference (Polar → Cartesian)

## 6. Create Submission

## 5. Inference (Polar Model with Rigorous TTA)

In [7]:
# ============================================================
# [FIXED] Robust Test Loading & Inference Pipeline (Polar, 10-Fold, TTA)
# ============================================================

import os
import numpy as np
import pandas as pd
import torch
import joblib
from tqdm import tqdm
from torch.utils.data import DataLoader
import sys
sys.path.append("src")
from polar_utils import polar_to_cartesian

# ------------------------------------------------------------
# Config
# ------------------------------------------------------------
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 64
N_FOLDS = 10
USE_TTA = True

SUBMISSION_PATH = "sample_submission.csv"
TEST_META_PATH = "test.csv"
MODEL_DIR = "models"
OUT_PATH = "submission_polar_h96_optimized.csv"

# ------------------------------------------------------------
# Utilities
# ------------------------------------------------------------
def _fix_rel_path(p: str) -> str:
    return p[2:] if isinstance(p, str) and p.startswith("./") else p

def load_full_test_df(test_meta_path: str) -> pd.DataFrame:
    """Merge all episode CSVs referenced in test.csv into one DataFrame."""
    test_meta = pd.read_csv(test_meta_path)
    all_rows = []

    for _, row in tqdm(test_meta.iterrows(), total=len(test_meta), desc="Reading episode CSVs"):
        path = _fix_rel_path(row["path"])
        if not os.path.exists(path):
            pass
        df = pd.read_csv(path)
        df = df.reset_index(drop=True)
        df["row_idx"] = np.arange(len(df), dtype=np.int32)
        df["game_id"] = row["game_id"]
        # In test.csv, game_episode is the unique string ID (e.g., '12345_1')
        df["game_episode"] = row["game_episode"]
        all_rows.append(df)

    full_df = pd.concat(all_rows, ignore_index=True)
    full_df = full_df.sort_values(["game_id", "game_episode", "row_idx"]).reset_index(drop=True)
    return full_df

def sanity_check_alignment(test_df_full: pd.DataFrame, submission: pd.DataFrame):
    uniq = test_df_full[["game_id", "game_episode"]].drop_duplicates()
    if len(uniq) != len(submission):
        print(f"⚠️ WARNING: unique episodes ({len(uniq)}) != submission rows ({len(submission)})")
    else:
        print("✅ Episode count matches submission.")

def build_canonical_test_episodes(base_preprocessor, test_df_full: pd.DataFrame):
    """Create test_episodes ONCE to enforce a single canonical order."""
    test_episodes = base_preprocessor.transform(test_df_full, is_train=False)
    keys = []
    for ep in test_episodes:
        gid = ep.get("game_id", 0) 
        gep = ep.get("game_episode", 0)
        keys.append((gid, gep))
    return test_episodes, keys

def infer_fold_preds(model, preprocessor, test_episodes, tta: bool):
    """Return [N, 3] predictions (d_norm, sin, cos) for a single fold."""
    test_dataset = MultiModalDataset(test_episodes, augment=False, cache_images=True)
    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=multimodal_collate_fn
    )

    preds = []
    model.eval()

    if tta:
        scaler = preprocessor.scaler
        mean = torch.tensor(scaler.mean_, device=DEVICE, dtype=torch.float32)
        std = torch.tensor(scaler.scale_, device=DEVICE, dtype=torch.float32)

    with torch.no_grad():
        for batch in tqdm(test_loader, desc="Infer"):
            imgs, cont, cat, lengths, _, _, _, _ = batch

            imgs = imgs.to(DEVICE)
            cont = cont.to(DEVICE)
            cat = cat.to(DEVICE)
            lengths = lengths.to(DEVICE)

            p_d, p_sin, p_cos, _ = model(imgs, cont, cat, lengths)

            if tta:
                imgs_f = torch.flip(imgs, dims=[2])
                cont_raw = cont * std + mean
                if cont_raw.shape[-1] > 5:
                    cont_raw[:, :, 1] = 1.0 - cont_raw[:, :, 1]
                    cont_raw[:, :, 3] = 1.0 - cont_raw[:, :, 3]
                    cont_raw[:, :, 5] = -cont_raw[:, :, 5]
                cont_f = (cont_raw - mean) / std

                p_d_f, p_sin_f, p_cos_f, _ = model(imgs_f, cont_f, cat, lengths)
                p_sin_f = -p_sin_f
                p_d = 0.5 * (p_d + p_d_f)
                p_sin = 0.5 * (p_sin + p_sin_f)
                p_cos = 0.5 * (p_cos + p_cos_f)

            p_d = p_d.detach().cpu().numpy().reshape(-1)
            p_sin = p_sin.detach().cpu().numpy().reshape(-1)
            p_cos = p_cos.detach().cpu().numpy().reshape(-1)

            pred = np.stack([p_d, p_sin, p_cos], axis=1)
            preds.append(pred)

    preds = np.concatenate(preds, axis=0)
    return preds

def polar_preds_to_cartesian(test_episodes, avg_preds):
    final_xy = []
    pred_keys = []
    for i, ep in enumerate(test_episodes):
        d_norm = float(avg_preds[i, 0])
        sin_t = float(avg_preds[i, 1])
        cos_t = float(avg_preds[i, 2])

        p_x, p_y = polar_to_cartesian(
            d_norm, sin_t, cos_t,
            ep["start_x"], ep["start_y"],
            d_scale=ep["d_scale"],
            normalize_direction=True,
            clip_field=True
        )
        final_xy.append([p_x, p_y])
        pred_keys.append((ep.get("game_id", None), ep.get("game_episode", None)))
    return np.array(final_xy), pred_keys

# ------------------------------------------------------------
# Main Execution Block
# ------------------------------------------------------------
if __name__ == "__main__":
    if not os.path.exists(SUBMISSION_PATH) or not os.path.exists(TEST_META_PATH):
        print(f"⚠️ Files not found! {SUBMISSION_PATH} or {TEST_META_PATH}")
    else:
        submission = pd.read_csv(SUBMISSION_PATH)
        test_df_full = load_full_test_df(TEST_META_PATH)
        sanity_check_alignment(test_df_full, submission)

        # 1. Load Base Preprocessor
        base_preprocessor_path = os.path.join(MODEL_DIR, "preprocessor_polar_h96_1.pkl")
        if not os.path.exists(base_preprocessor_path):
            print(f"⚠️ Base preprocessor not found! {base_preprocessor_path}")
        else:
            base_preprocessor = joblib.load(base_preprocessor_path)
            test_episodes, canonical_keys = build_canonical_test_episodes(base_preprocessor, test_df_full)
            
            # 2. K-Fold Inference
            all_fold_preds = []
            for fold in range(1, N_FOLDS + 1):
                print(f"\n=== Inference Fold {fold}/{N_FOLDS} ===")
                
                pp_path = os.path.join(MODEL_DIR, f"preprocessor_polar_h96_{fold}.pkl")
                md_path = os.path.join(MODEL_DIR, f"multimodal_polar_h96_{fold}.pth")
                
                if not os.path.exists(pp_path) or not os.path.exists(md_path):
                    continue
                
                preprocessor = joblib.load(pp_path)
                
                # [ROBUST FIX 1] Dynamic Model Init from Checkpoint
                state_dict = torch.load(md_path, map_location=DEVICE)
                chk_types = state_dict['type_emb.weight'].shape[0]
                chk_results = state_dict['result_emb.weight'].shape[0]
                input_dim_cont = preprocessor.get_input_dim()
                
                model = PolarMultiModalNet(
                    input_dim_cont, 
                    chk_types, 
                    chk_results, 
                    gru_hidden=96
                ).to(DEVICE)
                
                model.load_state_dict(state_dict, strict=True)
                
                fold_preds = infer_fold_preds(model, preprocessor, test_episodes, tta=USE_TTA)
                all_fold_preds.append(fold_preds)
            
            if len(all_fold_preds) > 0:
                all_fold_preds = np.stack(all_fold_preds, axis=0) # [F, N, 3]
                avg_preds = all_fold_preds.mean(axis=0)           # [N, 3]
                
                coords, pred_keys = polar_preds_to_cartesian(test_episodes, avg_preds)
                
                # [ROBUST FIX 2] Merge Key Fix (Only use game_episode)
                pred_df = pd.DataFrame(coords, columns=["end_x", "end_y"])
                
                # pred_keys is [(game_id, game_episode), ...]
                # test.csv's game_episode maps to k[1] (e.g., '153363_1')
                pred_df["game_episode"] = [k[1] for k in pred_keys]
                
                # sample_submission only has 'game_episode', 'end_x', 'end_y' columns
                # We simply replace end_x/end_y by merging onto the template
                final_sub = submission[["game_episode"]].merge(
                    pred_df[["game_episode", "end_x", "end_y"]], 
                    on="game_episode", 
                    how="left"
                )
                
                final_sub["end_x"] = final_sub["end_x"].clip(0, 105)
                final_sub["end_y"] = final_sub["end_y"].clip(0, 68)
                final_sub = final_sub.fillna(0)
                
                final_sub.to_csv(OUT_PATH, index=False)
                print(f"✅ Submission saved: {OUT_PATH}")
                print(final_sub.head())
            else:
                print("❌ No folds inferred!")

Reading episode CSVs: 100%|██████████| 2414/2414 [00:03<00:00, 627.26it/s]

✅ Episode count matches submission.

C:\Users\semic\AppData\Local\Temp\ipykernel_49836\4044936417.py:179: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(md_path, map_location=DEVICE)

=== Inference Fold 1/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 13532.38it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 15.03it/s]

=== Inference Fold 2/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 16606.99it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 17.51it/s]

=== Inference Fold 3/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 17262.69it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 17.36it/s]

=== Inference Fold 4/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 17310.09it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 17.60it/s]

=== Inference Fold 5/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 15703.69it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 17.82it/s]

=== Inference Fold 6/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 16757.31it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 17.85it/s]

=== Inference Fold 7/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 17668.86it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 17.89it/s]

=== Inference Fold 8/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 17663.62it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 18.18it/s]

=== Inference Fold 9/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 17524.54it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 18.01it/s]

=== Inference Fold 10/10 ===
Pre-rendering 2414 images (Cache Enabled)...

Caching Images: 100%|██████████| 2414/2414 [00:00<00:00, 16596.18it/s]
Infer: 100%|██████████| 38/38 [00:02<00:00, 17.90it/s]

✅ Submission saved: submission_polar_h96_optimized.csv
  game_episode      end_x      end_y
0     153363_1  67.953806  12.721565
1     153363_2  30.406996  50.059748
2     153363_6  35.886074  61.653611
3     153363_7  51.559660   8.285633
4     153363_8  80.418792   9.127678

In [8]:
result_v7_foldseed_h96_tta_corrected = pd.read_csv("submission_multimodal/multimodal_v7_h96_tta_corrected.csv")
result_v7_foldseed_h96_tta_corrected.head()

  game_episode      end_x      end_y
0     153363_1  63.744760  10.535255
1     153363_2  25.247570  50.701256
2     153363_6  26.461975  63.656200
3     153363_7  53.256310   4.663423
4     153363_8  81.452260   8.473086

In [9]:
result_v7_foldseed_h64_tta_corrected = pd.read_csv("submission_multimodal/multimodal_v7_h64_tta_corrected.csv")
result_v7_foldseed_h64_tta_corrected.head()

  game_episode      end_x      end_y
0     153363_1  61.837930   9.095944
1     153363_2  25.033142  47.295547
2     153363_6  31.202053  63.940987
3     153363_7  53.329033   5.811836
4     153363_8  81.128800   8.247789

In [11]:
import os
import pandas as pd

# ✅ 너 파일명/경로만 맞춰서 수정
H96_PATH = "submission_multimodal/multimodal_v7_h96_tta_corrected.csv"   # H96 tta 결과
POLAR_PATH = "submission_polar_h96_optimized.csv"                       # polar 결과

OUT_DIR = "submission_ensemble"
os.makedirs(OUT_DIR, exist_ok=True)

h96 = pd.read_csv(H96_PATH)
polar = pd.read_csv(POLAR_PATH)

# game_episode 기준으로 정렬/매칭
df = h96.merge(polar, on="game_episode", suffixes=("_h96", "_polar"), how="inner")

assert len(df) == len(h96), "Merge mismatch: check game_episode uniqueness / file alignment"

def make_ens(w_h96: float):
    w_polar = 1.0 - w_h96
    out = pd.DataFrame({
        "game_episode": df["game_episode"],
        "end_x": (w_h96 * df["end_x_h96"] + w_polar * df["end_x_polar"]).clip(0, 105),
        "end_y": (w_h96 * df["end_y_h96"] + w_polar * df["end_y_polar"]).clip(0, 68),
    })
    return out

for w in [0.7, 0.6]:
    out = make_ens(w)
    out_path = f"{OUT_DIR}/ens_h96{int(w*100)}_polar{int((1-w)*100)}.csv"
    out.to_csv(out_path, index=False)
    print("Saved:", out_path)
    print(out.head())

Saved: submission_ensemble/ens_h9670_polar30.csv
  game_episode      end_x      end_y
0     153363_1  65.007474  11.191148
1     153363_2  26.795398  50.508804
2     153363_6  29.289205  63.055423
3     153363_7  52.747315   5.750086
4     153363_8  81.142220   8.669463
Saved: submission_ensemble/ens_h9660_polar40.csv
  game_episode      end_x      end_y
0     153363_1  65.428378  11.409779
1     153363_2  27.311340  50.444653
2     153363_6  30.231615  62.855164
3     153363_7  52.577650   6.112307
4     153363_8  81.038873   8.734923

In [12]:
import pandas as pd
import numpy as np

FILES = {
    "H96": "submission_multimodal/multimodal_v7_h96_tta_corrected.csv",
    "H64": "submission_multimodal/multimodal_v7_h64_tta_corrected.csv",
    "Polar": "submission_polar_h96_optimized.csv",
    "Ens_70_30": "submission_ensemble/ens_h9670_polar30.csv",
    "Ens_60_40": "submission_ensemble/ens_h9660_polar40.csv",
}

def summarize(df, name):
    stats = {}
    for col in ["end_x", "end_y"]:
        s = df[col]
        stats[f"{col}_mean"] = s.mean()
        stats[f"{col}_std"] = s.std()
        stats[f"{col}_min"] = s.min()
        stats[f"{col}_max"] = s.max()
        stats[f"{col}_q25"] = s.quantile(0.25)
        stats[f"{col}_q75"] = s.quantile(0.75)
    return pd.Series(stats, name=name)

summary = []

for name, path in FILES.items():
    df = pd.read_csv(path)
    summary.append(summarize(df, name))

summary_df = pd.concat(summary, axis=1).T
pd.set_option("display.float_format", "{:.4f}".format)
print(summary_df)

           end_x_mean  end_x_std  end_x_min  end_x_max  end_x_q25  end_x_q75  \
H96           66.8816    21.7833     5.2596   101.4013    50.7169    85.8554
H64           66.9383    21.4831     5.2903   100.4247    50.5651    85.8319
Polar         68.2053    20.9974     0.0000   105.0000    53.7820    85.4752
Ens_70_30     67.2787    21.4890     3.6817   101.5910    51.7970    85.6933
Ens_60_40     67.4111    21.4018     3.1557   101.7682    52.0510    85.7804

           end_y_mean  end_y_std  end_y_min  end_y_max  end_y_q25  end_y_q75
H96           33.3093    22.7188     1.0082    66.9495     9.2238    57.7500
H64           33.2392    22.5938     1.4247    66.3395     9.5039    57.5747
Polar         33.4161    21.5765     0.0000    68.0000    12.2912    54.5446
Ens_70_30     33.3413    22.3095     0.7058    66.8242    10.1520    56.8546
Ens_60_40     33.3520    22.1853     0.6049    66.9534    10.4557    56.5071

In [13]:
def pairwise_distance(df1, df2):
    dx = df1["end_x"] - df2["end_x"]
    dy = df1["end_y"] - df2["end_y"]
    dist = np.sqrt(dx**2 + dy**2)
    return {
        "mean_dist": dist.mean(),
        "std_dist": dist.std(),
        "max_dist": dist.max(),
    }

h96 = pd.read_csv(FILES["H96"])
polar = pd.read_csv(FILES["Polar"])

print("H96 vs Polar:", pairwise_distance(h96, polar))

H96 vs Polar: {'mean_dist': np.float64(4.483949349855328), 'std_dist': np.float64(3.122136108692705), 'max_dist': np.float64(25.112079929601844)}

In [14]:
import pandas as pd
import numpy as np

POLAR_PATH = "submission_polar_h96_optimized.csv"
df = pd.read_csv(POLAR_PATH)

N = len(df)

def pct(mask):
    return 100 * mask.sum() / N

stats = {
    # 정확히 경계
    "end_x == 0": pct(df["end_x"] == 0),
    "end_x == 105": pct(df["end_x"] == 105),
    "end_y == 0": pct(df["end_y"] == 0),
    "end_y == 68": pct(df["end_y"] == 68),

    # 거의 경계 (1m 이내)
    "end_x <= 1": pct(df["end_x"] <= 1),
    "end_x >= 104": pct(df["end_x"] >= 104),
    "end_y <= 1": pct(df["end_y"] <= 1),
    "end_y >= 67": pct(df["end_y"] >= 67),
}

print("=== Polar Boundary Hit Ratio (%) ===")
for k, v in stats.items():
    print(f"{k:15s}: {v:6.3f}%")

=== Polar Boundary Hit Ratio (%) ===
end_x == 0     :  0.041%
end_x == 105   :  0.041%
end_y == 0     :  0.994%
end_y == 68    :  0.704%
end_x <= 1     :  0.041%
end_x >= 104   :  0.041%
end_y <= 1     :  1.574%
end_y >= 67    :  1.408%

In [15]:
def boundary_stats(path, name):
    df = pd.read_csv(path)
    N = len(df)
    return {
        "model": name,
        "x_min_or_max_%": 100 * ((df["end_x"] <= 1) | (df["end_x"] >= 104)).sum() / N,
        "y_min_or_max_%": 100 * ((df["end_y"] <= 1) | (df["end_y"] >= 67)).sum() / N,
    }

rows = []
rows.append(boundary_stats("submission_multimodal/multimodal_v7_h96_tta_corrected.csv", "H96"))
rows.append(boundary_stats("submission_polar_h96_optimized.csv", "Polar"))

pd.DataFrame(rows)

   model  x_min_or_max_%  y_min_or_max_%
0    H96          0.0000          0.0000
1  Polar          0.0829          2.9826