# Multi-modal Model V2.5 - Fast GRU & Y-Flip Augmentation

이 노트북은 `MultiModal_v2_4`의 속도 이슈를 해결하고, 데이터 증강을 통해 성능을 극대화하는 버전입니다.

## 주요 변경 사항 (V2.5)

1.  **GRU Architecture (Speed)**:
    - LSTM 대신 구조가 단순한 **GRU (Gated Recurrent Unit)**를 사용합니다.
    - 파라미터 수가 적어 학습 속도가 빠르고, 적은 데이터셋에서 과적합 위험이 적습니다.
2.  **Random Y-Flip Augmentation (Robustness)**:
    - 축구장은 Y축(가로 중심선) 기준으로 대칭입니다.
    - 학습 시 **50% 확률로 위아래를 뒤집어(Flip)** 데이터를 2배로 늘리는 효과를 냅니다.
3.  **Visualization Revert (Efficiency)**:
    - v2.4의 속도 저하 원인이었던 Thick Trajectory를 제거하고, 다시 **1px 선 그리기**로 복귀하여 빠른 데이터 로딩 속도를 확보합니다.

## 모델 개요
- **Feature**: v2.2와 동일 (안정적 베이스라인)
- **Model**: CNN + **Bi-GRU** + Fusion
- **Augmentation**: Random Y-Flip (Train Only)

In [1]:
import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence, pad_sequence
from sklearn.model_selection import GroupKFold
import cv2  # OpenCV Import
from tqdm import tqdm
import joblib

# [v7 Fix] Use Fixed Preprocessor (No Rounding)
from src.preprocessing_multimodal_fixed import FootballPreprocessorMultimodal

# Fold-specific Seeds for Diversity
FOLD_SEEDS = {
    1: 42,
    2: 43,
    3: 44,
    4: 45,
    5: 46,
    6: 47,
    7: 48,
    8: 49,
    9: 50,
    10: 51,
}

# Set Seed
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {DEVICE}")

Device: cuda

## 1. 데이터 로드 및 전처리 (Preprocessing V2.5)

## 2. 이미지 생성 및 증강 (Random Y-Flip)

In [2]:
# Load Raw Training Data
train_df = pd.read_csv("train.csv")
print(f"Loaded {len(train_df)} rows")

Loaded 356721 rows

In [3]:
class MultiModalDataset(Dataset):
    def __init__(self, episodes, img_size=(68, 105), augment=False, cache_images=True):
        self.episodes = episodes
        self.H, self.W = img_size
        self.augment = augment
        self.cache_images = cache_images
        self.img_cache = None
        
        # [v7 Fix] Image Caching (Speed Optimization)
        if self.cache_images:
            print(f"Pre-rendering {len(episodes)} images (Cache Enabled)...")
            # Generate Base Images (No Augmentation applied yet)
            self.img_cache = [self._generate_image(ep['cont']) for ep in tqdm(episodes, desc="Caching Images")]

    def __len__(self):
        return len(self.episodes)

    def _generate_image(self, cont_data):
        # [v6 Optimization] Fast Generation with OpenCV
        img_np = np.zeros((2, self.H, self.W), dtype=np.float32)
        if len(cont_data) == 0:
             return torch.tensor(img_np, dtype=torch.float32)

        seq_len = cont_data.shape[0]
        
        xs = cont_data[:, 0]
        ys = cont_data[:, 1]
        
        # 좌표 변환 (0~1 -> Grid)
        # Note: Input is float (fixed preprocessor), map to int index
        x_idxs = (xs * (self.W - 1)).round().astype(int).clip(0, self.W - 1)
        y_idxs = (ys * (self.H - 1)).round().astype(int).clip(0, self.H - 1)
        
        for t in range(seq_len):
            px, py = x_idxs[t], y_idxs[t]
            
            # Channel 0: Dots
            img_np[0, py, px] = 1.0
            
            decay_val = (t + 1) / seq_len
            
            # Channel 1: Line
            if t > 0:
                prev_px, prev_py = x_idxs[t-1], y_idxs[t-1]
                cv2.line(img_np[1], (prev_px, prev_py), (px, py), color=decay_val, thickness=1)
            else:
                img_np[1, py, px] = decay_val
        return torch.tensor(img_np, dtype=torch.float32)

    def __getitem__(self, idx):
        data = self.episodes[idx]
        
        cont = data['cont'].copy()
        target = data['target'].copy()
        
        # Augmentation Logic (Y-Flip)
        if self.augment and random.random() < 0.5:
            # 1. Flip Continuous Features
            cont[:, 1] = 1.0 - cont[:, 1] # start_y
            cont[:, 3] = 1.0 - cont[:, 3] # end_y_prev
            cont[:, 5] = -cont[:, 5]      # dy_prev (Vector Flip)
            target[1] = 1.0 - target[1]   # Target Flip
            
            # 2. Get Image
            if self.cache_images:
                # Retrieve Base Image from Cache
                base_img = self.img_cache[idx]
                # Apply Flip (Y-Flip = Flip H dimension = dim 1)
                img = torch.flip(base_img, [1])
            else:
                img = self._generate_image(cont) # Generate from flipped coords
        else:
            # No Augmentation
            if self.cache_images:
                img = self.img_cache[idx]
            else:
                img = self._generate_image(cont)
        
        cont_tensor = torch.tensor(cont, dtype=torch.float32)
        cat_tensor = torch.tensor(data['cat'], dtype=torch.long)
        target_tensor = torch.tensor(target, dtype=torch.float32)
        
        # Deep Supervision Targets
        seq_len = cont.shape[0]
        aux_target = np.zeros((seq_len, 2), dtype=np.float32)
        if seq_len > 1:
            aux_target[:-1] = cont[1:, 0:2]
        aux_target[-1] = target # Last step target is GT
        aux_target_tensor = torch.tensor(aux_target, dtype=torch.float32)
        
        return img, cont_tensor, cat_tensor, target_tensor, aux_target_tensor

## 3. 모델 아키텍처 (GRU 적용)

In [4]:
class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super(SpatialAttention, self).__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x_cat = torch.cat([avg_out, max_out], dim=1)
        x_out = self.conv(x_cat)
        return self.sigmoid(x_out)

class ImprovedCNN(nn.Module):
    def __init__(self):
        super(ImprovedCNN, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(2, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128), nn.ReLU(),
        )
        self.sa = SpatialAttention()
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(128, 128)
        
    def forward(self, x):
        x = self.features(x)
        sa_map = self.sa(x)
        x = x * sa_map
        x = self.pool(x).flatten(1)
        x = F.relu(self.fc(x))
        return x

class LSTMAttention(nn.Module):
    def __init__(self, hidden_dim):
        super(LSTMAttention, self).__init__()
        self.attention = nn.Linear(hidden_dim, 1)
    def forward(self, rnn_output):
        attn_weights = torch.softmax(self.attention(rnn_output), dim=1)
        return torch.sum(attn_weights * rnn_output, dim=1)

class MultiModalNetV6(nn.Module):
    def __init__(self, input_dim_cont, num_types, num_results, gru_hidden=96):
        super(MultiModalNetV6, self).__init__()
        self.cnn = ImprovedCNN()
        self.type_emb = nn.Embedding(num_types, 8)
        self.result_emb = nn.Embedding(num_results, 8)
        
        total_input_dim = input_dim_cont + 8 + 8
        self.gru_hidden = gru_hidden
        
        # [변경] Split GRU (Anti-Leakage)
        # Forward와 Backward를 물리적으로 분리하여, Forward GRU에 미래 정보가 유입되는 것을 원천 차단
        self.gru_fwd = nn.GRU(
            input_size=total_input_dim,
            hidden_size=gru_hidden,
            num_layers=2, # Multi-layer OK (Forward끼리만 연결됨)
            batch_first=True,
            bidirectional=False, # 단방향
            dropout=0.1
        )
        
        self.gru_bwd = nn.GRU(
            input_size=total_input_dim,
            hidden_size=gru_hidden,
            num_layers=2,
            batch_first=True,
            bidirectional=False, # 단방향
            dropout=0.1
        )
        
        self.gru_attn = LSTMAttention(gru_hidden * 2)
        self.gru_fc = nn.Linear(gru_hidden * 2, 128)
        
        # [New] Deep Supervision Head
        # Use ONLY Forward Hidden State for Aux Output
        self.aux_fc = nn.Linear(gru_hidden, 2) 
        
        self.fusion_fc = nn.Sequential(
            nn.BatchNorm1d(256), nn.Dropout(0.3),
            nn.Linear(256, 128), nn.ReLU(),
            nn.Linear(128, 2)
        )

    def forward(self, img, cont, cat, lengths):
        # 1. Feature Extraction
        img_feat = self.cnn(img)
        emb_type = self.type_emb(cat[:, :, 0])
        emb_result = self.result_emb(cat[:, :, 1])
        x_seq = torch.cat([cont, emb_type, emb_result], dim=2)
        
        # 2. Forward GRU
        packed_fwd = pack_padded_sequence(x_seq, lengths.cpu(), batch_first=True, enforce_sorted=False)
        out_fwd_packed, _ = self.gru_fwd(packed_fwd)
        out_fwd, _ = pad_packed_sequence(out_fwd_packed, batch_first=True)
        
        # 3. Backward GRU (Manual Flip)
        # Reverse sequence for backward pass
        # Note: Padding should remain at the end, so we need careful reversal?
        # pack_padded_sequence handles lengths correctly, verifying...
        # For simplicity and correctness with variable lengths:
        # We can just reverse the input tensor in time dim, pack, run GRU, unpack, reverse back.
        # But we need to handle padding.
        
        # Optimized Backward Strategy:
        # Since we use pack_padded_sequence with enforce_sorted=False, 
        # we can just flip the non-padded parts? Or just flip the whole tensor and let pack handle it?
        # Actually, PyTorch's pad_packed_sequence output is padded with zeros.
        # It's safer to rely on PyTorch's bidirectional implementation but we can't because of the leakage.
        # So manual flip is needed.
        
        # Manual Flip Logic:
        x_seq_bwd = x_seq.clone()
        for i, length in enumerate(lengths):
            x_seq_bwd[i, :length] = x_seq[i, :length].flip(0)
            
        packed_bwd = pack_padded_sequence(x_seq_bwd, lengths.cpu(), batch_first=True, enforce_sorted=False)
        out_bwd_packed, _ = self.gru_bwd(packed_bwd)
        out_bwd, _ = pad_packed_sequence(out_bwd_packed, batch_first=True)
        
        # Reverse output back to original order
        for i, length in enumerate(lengths):
            out_bwd[i, :length] = out_bwd[i, :length].flip(0)
            
        # 4. Concatenate: [Forward, Backward]
        # out_fwd: [B, L, H], out_bwd: [B, L, H]
        gru_out_combined = torch.cat([out_fwd, out_bwd], dim=2) # [B, L, H*2]
        
        # 5. Main Output (Legacy)
        gru_ctx = self.gru_attn(gru_out_combined)
        seq_feat = F.relu(self.gru_fc(gru_ctx))
        concat_feat = torch.cat([img_feat, seq_feat], dim=1)
        final_out = self.fusion_fc(concat_feat)
        
        # 6. Aux Output (Deep Supervision)
        # Use ONLY out_fwd (Pure Past->Future info)
        aux_out = self.aux_fc(out_fwd) # [B, L, 2]
        
        return final_out, aux_out

class EuclideanLoss(nn.Module):
    def __init__(self):
        super(EuclideanLoss, self).__init__()
    def forward(self, pred, target):
        pred_real = pred * torch.tensor([105.0, 68.0], device=pred.device)
        target_real = target * torch.tensor([105.0, 68.0], device=target.device)
        return torch.mean(torch.sqrt(torch.sum((pred_real - target_real)**2, dim=1) + 1e-6))
        
class MaskedSeqEuclideanLoss(nn.Module):
    def __init__(self):
        super(MaskedSeqEuclideanLoss, self).__init__()
        
    def forward(self, pred, target, lengths):
        # pred: [B, L, 2]
        # target: [B, L, 2]
        # lengths: [B]
        
        mask = torch.arange(pred.size(1), device=pred.device)[None, :] < lengths[:, None]
        mask = mask.unsqueeze(-1) # [B, L, 1]
        
        pred_real = pred * torch.tensor([105.0, 68.0], device=pred.device)
        target_real = target * torch.tensor([105.0, 68.0], device=target.device)
        
        diff = pred_real - target_real
        dist = torch.sqrt(torch.sum(diff**2, dim=2) + 1e-6) # [B, L]
        
        # Masking
        dist = dist * mask.squeeze(-1)
        
        return dist.sum() / mask.sum()

## 4. 학습

In [5]:
def multimodal_collate_fn(batch):
    imgs, conts, cats, targets, aux_targets = zip(*batch)
    imgs_batched = torch.stack(imgs, dim=0)
    lengths = torch.tensor([len(c) for c in conts], dtype=torch.long)
    conts_padded = pad_sequence(conts, batch_first=True)
    cats_padded = pad_sequence(cats, batch_first=True)
    targets = torch.stack(targets, dim=0)
    aux_targets_padded = pad_sequence(aux_targets, batch_first=True)
    return imgs_batched, conts_padded, cats_padded, lengths, targets, aux_targets_padded

In [6]:
# [v7 Fix] Leakage-Free Training Function
# Now receives Raw DataFrame instead of transformed episodes
def train_multimodal_v7(train_df, n_splits=10, epochs=100, batch_size=64, lr=0.001):
    gkf = GroupKFold(n_splits=n_splits)
    groups = train_df['game_id'] 
    
    fold_scores = []

    # Get dimensions from first fold (will be same for all folds)
    input_dim_cont = None
    num_types = None
    num_results = None
    
    # K-Fold Loop
    for fold, (train_idx, val_idx) in enumerate(gkf.split(train_df, groups=groups)):
        
        # Set fold-specific seed for diversity
        fold_seed = FOLD_SEEDS[fold + 1]
        seed_everything(fold_seed)
        print(f"[Fold {fold+1}] Seed fixed to {fold_seed}")
        print(f"\n=== Fold {fold+1}/{n_splits} ===")
        
        # 1. Split Raw Data
        train_sub_df = train_df.iloc[train_idx].copy()
        val_sub_df = train_df.iloc[val_idx].copy()
        
        # 2. Fit Preprocessor (Inside Loop -> No Leakage)
        preprocessor = FootballPreprocessorMultimodal()
        preprocessor.fit(train_sub_df)

        # Get dimensions (only once, on first fold)
        if input_dim_cont is None:
            input_dim_cont = preprocessor.get_input_dim()
            num_types, num_results = preprocessor.get_num_classes()
            print(f"Model Dimensions: input={input_dim_cont}, types={num_types}, results={num_results}")
        
        # 3. Transform Data
        # 3. Transform Data
        train_episodes = preprocessor.transform(train_sub_df, is_train=True)
        val_episodes = preprocessor.transform(val_sub_df, is_train=True) # Val also needs targets
        
        input_dim_cont = preprocessor.get_input_dim()
        num_types, num_results = preprocessor.get_num_classes()
        
        # 4. Dataset & Loader (With Caching)
        # Train: Cache Enabled, Augment Enabled
        train_dataset = MultiModalDataset(train_episodes, augment=True, cache_images=True)
        # Val: Cache Enabled, No Augment
        val_dataset = MultiModalDataset(val_episodes, augment=False, cache_images=True)
        
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=multimodal_collate_fn, drop_last=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, collate_fn=multimodal_collate_fn)
        
        # Model (Split-GRU v6 Architecture)
        model = MultiModalNetV6(input_dim_cont, num_types, num_results).to(DEVICE)
        
        criterion_main = EuclideanLoss()
        criterion_aux = MaskedSeqEuclideanLoss() 
        
        optimizer = optim.Adam(model.parameters(), lr=lr) 
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)
        
        best_dist = float('inf')
        best_state = None
        patience_counter = 0
        patience_limit = 15
        
        for epoch in range(epochs):
            model.train()
            train_loss = 0
            
            # Tqdm for progress tracking (optional, maybe noisy for user logs)
            # for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
            for batch in train_loader:
                imgs, cont, cat, lengths, target, aux_target = batch
                imgs, cont, cat, lengths, target, aux_target = imgs.to(DEVICE), cont.to(DEVICE), cat.to(DEVICE), lengths.to(DEVICE), target.to(DEVICE), aux_target.to(DEVICE)
                
                optimizer.zero_grad()
                pred, aux_pred = model(imgs, cont, cat, lengths)
                
                loss_m = criterion_main(pred, target)
                loss_a = criterion_aux(aux_pred, aux_target, lengths)
                
                loss = loss_m + 0.5 * loss_a
                loss.backward()
                optimizer.step()
                train_loss += loss.item()
            
            train_loss /= len(train_loader)
            
            model.eval()
            val_dists = []
            with torch.no_grad():
                for batch in val_loader:
                    imgs, cont, cat, lengths, target, aux_target = batch
                    imgs, cont, cat, lengths, target, aux_target = imgs.to(DEVICE), cont.to(DEVICE), cat.to(DEVICE), lengths.to(DEVICE), target.to(DEVICE), aux_target.to(DEVICE)
                    
                    pred, _ = model(imgs, cont, cat, lengths)
                    
                    pred_real = pred.cpu().numpy() * np.array([105.0, 68.0])
                    target_real = target.cpu().numpy() * np.array([105.0, 68.0])
                    val_dists.extend(np.sqrt(np.sum((pred_real - target_real)**2, axis=1)))
            
            mean_dist = np.mean(val_dists)
            scheduler.step(mean_dist)
            print(f"Epoch {epoch+1}: Train Loss {train_loss:.4f}, Val Dist {mean_dist:.4f}")
            
            if mean_dist < best_dist:
                best_dist = mean_dist
                best_state = model.state_dict()
                # Save with v7 suffix
                torch.save(best_state, f"models/multimodal_v7_h96_{fold+1}.pth")
                joblib.dump(preprocessor, f"models/preprocessor_v7_h96_{fold+1}.pkl")
                print(f"  -> Saved Best Model (Dist: {best_dist:.4f})")
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= patience_limit:
                    print("Early Stopping")
                    break
        
        print(f"Fold {fold+1} Finished. Best Valid Dist: {best_dist:.4f}")
        fold_scores.append(best_dist)
        
    print(f"Average Score: {np.mean(fold_scores):.4f}")

In [7]:
# [v7 Execution]
train_multimodal_v7(train_df, n_splits=10, epochs=100, batch_size=32, lr=0.001)

[Fold 1] Seed fixed to 42

=== Fold 1/10 ===
Model Dimensions: input=10, types=27, results=21
Pre-rendering 13847 images (Cache Enabled)...

Caching Images: 100%|██████████| 13847/13847 [00:01<00:00, 12328.81it/s]

Pre-rendering 1581 images (Cache Enabled)...

Caching Images: 100%|██████████| 1581/1581 [00:00<00:00, 12512.21it/s]

Epoch 1: Train Loss 61.7265, Val Dist 22.2160
  -> Saved Best Model (Dist: 22.2160)
Epoch 2: Train Loss 49.2726, Val Dist 20.5656
  -> Saved Best Model (Dist: 20.5656)
Epoch 3: Train Loss 46.7672, Val Dist 17.7305
  -> Saved Best Model (Dist: 17.7305)
Epoch 4: Train Loss 45.3608, Val Dist 17.2045
  -> Saved Best Model (Dist: 17.2045)
Epoch 5: Train Loss 44.4426, Val Dist 16.6557
  -> Saved Best Model (Dist: 16.6557)
Epoch 6: Train Loss 43.6645, Val Dist 15.5423
  -> Saved Best Model (Dist: 15.5423)
Epoch 7: Train Loss 42.8739, Val Dist 15.3880
  -> Saved Best Model (Dist: 15.3880)
Epoch 8: Train Loss 42.4313, Val Dist 15.2548
  -> Saved Best Model (Dist: 15.2548)
Epoch 9: Train Loss 41.9955, Val Dist 14.8284
  -> Saved Best Model (Dist: 14.8284)
Epoch 10: Train Loss 41.7008, Val Dist 14.9495
Epoch 11: Train Loss 41.3675, Val Dist 14.6827
  -> Saved Best Model (Dist: 14.6827)
Epoch 12: Train Loss 41.0648, Val Dist 14.6355
  -> Saved Best Model (Dist: 14.6355)
Epoch 13: Train Loss 40.7825, Val Dist 14.6198
  -> Saved Best Model (Dist: 14.6198)
Epoch 14: Train Loss 40.7076, Val Dist 14.9343
Epoch 15: Train Loss 40.4461, Val Dist 14.6511
Epoch 16: Train Loss 40.3256, Val Dist 14.6708
Epoch 17: Train Loss 40.0752, Val Dist 14.4669
  -> Saved Best Model (Dist: 14.4669)
Epoch 18: Train Loss 39.9728, Val Dist 14.0508
  -> Saved Best Model (Dist: 14.0508)
Epoch 19: Train Loss 39.8274, Val Dist 14.2099
Epoch 20: Train Loss 39.7400, Val Dist 14.0003
  -> Saved Best Model (Dist: 14.0003)
Epoch 21: Train Loss 39.6825, Val Dist 14.0863
Epoch 22: Train Loss 39.4531, Val Dist 14.1314
Epoch 23: Train Loss 39.4142, Val Dist 14.0226
Epoch 24: Train Loss 39.2395, Val Dist 14.3062
Epoch 25: Train Loss 38.6965, Val Dist 13.8318
  -> Saved Best Model (Dist: 13.8318)
Epoch 26: Train Loss 38.5525, Val Dist 13.8514
Epoch 27: Train Loss 38.4448, Val Dist 13.6161
  -> Saved Best Model (Dist: 13.6161)
Epoch 28: Train Loss 38.4157, Val Dist 13.7729
Epoch 29: Train Loss 38.2869, Val Dist 13.8149
Epoch 30: Train Loss 38.3107, Val Dist 13.8164
Epoch 31: Train Loss 38.1896, Val Dist 13.8961
Epoch 32: Train Loss 37.9134, Val Dist 13.7115
Epoch 33: Train Loss 37.8216, Val Dist 13.7746
Epoch 34: Train Loss 37.7250, Val Dist 13.8050
Epoch 35: Train Loss 37.6760, Val Dist 13.7226
Epoch 36: Train Loss 37.6026, Val Dist 13.6436
Epoch 37: Train Loss 37.4780, Val Dist 13.6848
Epoch 38: Train Loss 37.4537, Val Dist 13.6304
Epoch 39: Train Loss 37.4385, Val Dist 13.6245
Epoch 40: Train Loss 37.3599, Val Dist 13.6310
Epoch 41: Train Loss 37.3865, Val Dist 13.6361
Epoch 42: Train Loss 37.2880, Val Dist 13.6623
Early Stopping
Fold 1 Finished. Best Valid Dist: 13.6161
[Fold 2] Seed fixed to 43

=== Fold 2/10 ===
Pre-rendering 13934 images (Cache Enabled)...

Caching Images: 100%|██████████| 13934/13934 [00:00<00:00, 14956.53it/s]

Pre-rendering 1494 images (Cache Enabled)...

Caching Images: 100%|██████████| 1494/1494 [00:00<00:00, 13156.13it/s]

Epoch 1: Train Loss 62.4253, Val Dist 26.3090
  -> Saved Best Model (Dist: 26.3090)
Epoch 2: Train Loss 48.7180, Val Dist 20.2228
  -> Saved Best Model (Dist: 20.2228)
Epoch 3: Train Loss 46.6042, Val Dist 17.3504
  -> Saved Best Model (Dist: 17.3504)
Epoch 4: Train Loss 45.1720, Val Dist 16.2360
  -> Saved Best Model (Dist: 16.2360)
Epoch 5: Train Loss 44.1505, Val Dist 16.3294
Epoch 6: Train Loss 43.4958, Val Dist 15.3266
  -> Saved Best Model (Dist: 15.3266)
Epoch 7: Train Loss 42.7996, Val Dist 15.3695
Epoch 8: Train Loss 42.3572, Val Dist 14.6738
  -> Saved Best Model (Dist: 14.6738)
Epoch 9: Train Loss 42.1544, Val Dist 14.6354
  -> Saved Best Model (Dist: 14.6354)
Epoch 10: Train Loss 41.8224, Val Dist 15.2250
Epoch 11: Train Loss 41.5500, Val Dist 14.6607
Epoch 12: Train Loss 41.2937, Val Dist 14.8332
Epoch 13: Train Loss 41.0200, Val Dist 14.5090
  -> Saved Best Model (Dist: 14.5090)
Epoch 14: Train Loss 40.8452, Val Dist 14.6302
Epoch 15: Train Loss 40.5432, Val Dist 14.3965
  -> Saved Best Model (Dist: 14.3965)
Epoch 16: Train Loss 40.5062, Val Dist 14.4868
Epoch 17: Train Loss 40.2512, Val Dist 14.5323
Epoch 18: Train Loss 40.0832, Val Dist 14.6387
Epoch 19: Train Loss 39.9751, Val Dist 14.1056
  -> Saved Best Model (Dist: 14.1056)
Epoch 20: Train Loss 39.7710, Val Dist 14.3611
Epoch 21: Train Loss 39.7938, Val Dist 14.2377
Epoch 22: Train Loss 39.6898, Val Dist 14.5754
Epoch 23: Train Loss 39.4324, Val Dist 14.0114
  -> Saved Best Model (Dist: 14.0114)
Epoch 24: Train Loss 39.3705, Val Dist 14.1933
Epoch 25: Train Loss 39.4037, Val Dist 14.3694
Epoch 26: Train Loss 39.2448, Val Dist 29.0880
Epoch 27: Train Loss 39.1011, Val Dist 13.8889
  -> Saved Best Model (Dist: 13.8889)
Epoch 28: Train Loss 38.9871, Val Dist 13.7795
  -> Saved Best Model (Dist: 13.7795)
Epoch 29: Train Loss 38.9699, Val Dist 13.8607
Epoch 30: Train Loss 38.8689, Val Dist 14.2335
Epoch 31: Train Loss 38.8213, Val Dist 13.9353
Epoch 32: Train Loss 38.6964, Val Dist 14.0496
Epoch 33: Train Loss 38.2193, Val Dist 13.7710
  -> Saved Best Model (Dist: 13.7710)
Epoch 34: Train Loss 38.0960, Val Dist 14.0447
Epoch 35: Train Loss 38.0359, Val Dist 13.9043
Epoch 36: Train Loss 37.9354, Val Dist 13.7321
  -> Saved Best Model (Dist: 13.7321)
Epoch 37: Train Loss 37.9110, Val Dist 13.9383
Epoch 38: Train Loss 37.7766, Val Dist 14.0885
Epoch 39: Train Loss 37.7659, Val Dist 13.6809
  -> Saved Best Model (Dist: 13.6809)
Epoch 40: Train Loss 37.6822, Val Dist 13.7802
Epoch 41: Train Loss 37.7090, Val Dist 13.8962
Epoch 42: Train Loss 37.6853, Val Dist 13.8315
Epoch 43: Train Loss 37.6013, Val Dist 13.8234
Epoch 44: Train Loss 37.2026, Val Dist 14.1747
Epoch 45: Train Loss 37.2028, Val Dist 13.9684
Epoch 46: Train Loss 37.1462, Val Dist 13.8481
Epoch 47: Train Loss 37.0805, Val Dist 13.8443
Epoch 48: Train Loss 36.9777, Val Dist 13.7091
Epoch 49: Train Loss 36.9176, Val Dist 13.7622
Epoch 50: Train Loss 36.8781, Val Dist 13.7545
Epoch 51: Train Loss 36.8078, Val Dist 13.7697
Epoch 52: Train Loss 36.7634, Val Dist 13.7975
Epoch 53: Train Loss 36.8072, Val Dist 13.7684
Epoch 54: Train Loss 36.7300, Val Dist 13.7629
Early Stopping
Fold 2 Finished. Best Valid Dist: 13.6809
[Fold 3] Seed fixed to 44

=== Fold 3/10 ===
Pre-rendering 13865 images (Cache Enabled)...

Caching Images: 100%|██████████| 13865/13865 [00:00<00:00, 15570.57it/s]

Pre-rendering 1563 images (Cache Enabled)...

Caching Images: 100%|██████████| 1563/1563 [00:00<00:00, 14408.41it/s]

Epoch 1: Train Loss 60.8498, Val Dist 19.6787
  -> Saved Best Model (Dist: 19.6787)
Epoch 2: Train Loss 48.3137, Val Dist 17.4842
  -> Saved Best Model (Dist: 17.4842)
Epoch 3: Train Loss 46.3315, Val Dist 17.6973
Epoch 4: Train Loss 45.0104, Val Dist 15.5596
  -> Saved Best Model (Dist: 15.5596)
Epoch 5: Train Loss 43.9562, Val Dist 15.5947
Epoch 6: Train Loss 43.3146, Val Dist 15.0044
  -> Saved Best Model (Dist: 15.0044)
Epoch 7: Train Loss 42.6639, Val Dist 15.0645
Epoch 8: Train Loss 42.2649, Val Dist 14.7279
  -> Saved Best Model (Dist: 14.7279)
Epoch 9: Train Loss 41.9103, Val Dist 14.8982
Epoch 10: Train Loss 41.7085, Val Dist 15.1029
Epoch 11: Train Loss 41.3462, Val Dist 14.3536
  -> Saved Best Model (Dist: 14.3536)
Epoch 12: Train Loss 41.1299, Val Dist 14.3844
Epoch 13: Train Loss 40.8468, Val Dist 14.5614
Epoch 14: Train Loss 40.5655, Val Dist 14.4739
Epoch 15: Train Loss 40.5574, Val Dist 14.4840
Epoch 16: Train Loss 39.8561, Val Dist 14.0301
  -> Saved Best Model (Dist: 14.0301)
Epoch 17: Train Loss 39.8067, Val Dist 13.9817
  -> Saved Best Model (Dist: 13.9817)
Epoch 18: Train Loss 39.6551, Val Dist 14.1289
Epoch 19: Train Loss 39.5462, Val Dist 14.0501
Epoch 20: Train Loss 39.5701, Val Dist 13.9912
Epoch 21: Train Loss 39.3706, Val Dist 13.7543
  -> Saved Best Model (Dist: 13.7543)
Epoch 22: Train Loss 39.2682, Val Dist 14.1425
Epoch 23: Train Loss 39.2196, Val Dist 13.9556
Epoch 24: Train Loss 39.0968, Val Dist 14.0269
Epoch 25: Train Loss 39.0313, Val Dist 13.8863
Epoch 26: Train Loss 38.7461, Val Dist 13.7366
  -> Saved Best Model (Dist: 13.7366)
Epoch 27: Train Loss 38.6866, Val Dist 13.6246
  -> Saved Best Model (Dist: 13.6246)
Epoch 28: Train Loss 38.5689, Val Dist 13.5711
  -> Saved Best Model (Dist: 13.5711)
Epoch 29: Train Loss 38.5344, Val Dist 13.6890
Epoch 30: Train Loss 38.5607, Val Dist 13.7381
Epoch 31: Train Loss 38.5372, Val Dist 13.7669
Epoch 32: Train Loss 38.4111, Val Dist 13.6310
Epoch 33: Train Loss 38.2418, Val Dist 13.5603
  -> Saved Best Model (Dist: 13.5603)
Epoch 34: Train Loss 38.1876, Val Dist 13.5985
Epoch 35: Train Loss 38.2375, Val Dist 13.5527
  -> Saved Best Model (Dist: 13.5527)
Epoch 36: Train Loss 38.1597, Val Dist 13.6450
Epoch 37: Train Loss 38.1738, Val Dist 13.5694
Epoch 38: Train Loss 38.1103, Val Dist 13.5307
  -> Saved Best Model (Dist: 13.5307)
Epoch 39: Train Loss 38.0917, Val Dist 13.5007
  -> Saved Best Model (Dist: 13.5007)
Epoch 40: Train Loss 38.0913, Val Dist 13.5481
Epoch 41: Train Loss 38.0895, Val Dist 13.4808
  -> Saved Best Model (Dist: 13.4808)
Epoch 42: Train Loss 37.9992, Val Dist 13.5536
Epoch 43: Train Loss 38.1121, Val Dist 13.5692
Epoch 44: Train Loss 37.9996, Val Dist 13.4931
Epoch 45: Train Loss 37.9515, Val Dist 13.5241
Epoch 46: Train Loss 37.8742, Val Dist 13.5009
Epoch 47: Train Loss 37.8201, Val Dist 13.5239
Epoch 48: Train Loss 37.7636, Val Dist 13.5310
Epoch 49: Train Loss 37.8025, Val Dist 13.5447
Epoch 50: Train Loss 37.7918, Val Dist 13.5730
Epoch 51: Train Loss 37.7567, Val Dist 13.5393
Epoch 52: Train Loss 37.7521, Val Dist 13.5189
Epoch 53: Train Loss 37.7609, Val Dist 13.4971
Epoch 54: Train Loss 37.7916, Val Dist 13.5101
Epoch 55: Train Loss 37.7495, Val Dist 13.5230
Epoch 56: Train Loss 37.7136, Val Dist 13.5413
Early Stopping
Fold 3 Finished. Best Valid Dist: 13.4808
[Fold 4] Seed fixed to 45

=== Fold 4/10 ===
Pre-rendering 13857 images (Cache Enabled)...

Caching Images: 100%|██████████| 13857/13857 [00:00<00:00, 15566.38it/s]

Pre-rendering 1571 images (Cache Enabled)...

Caching Images: 100%|██████████| 1571/1571 [00:00<00:00, 13130.81it/s]

Epoch 1: Train Loss 60.1010, Val Dist 21.6523
  -> Saved Best Model (Dist: 21.6523)
Epoch 2: Train Loss 48.1894, Val Dist 17.4164
  -> Saved Best Model (Dist: 17.4164)
Epoch 3: Train Loss 46.2568, Val Dist 16.7646
  -> Saved Best Model (Dist: 16.7646)
Epoch 4: Train Loss 44.8993, Val Dist 16.5256
  -> Saved Best Model (Dist: 16.5256)
Epoch 5: Train Loss 44.1094, Val Dist 15.4532
  -> Saved Best Model (Dist: 15.4532)
Epoch 6: Train Loss 43.2356, Val Dist 15.6880
Epoch 7: Train Loss 42.7186, Val Dist 15.2482
  -> Saved Best Model (Dist: 15.2482)
Epoch 8: Train Loss 42.1548, Val Dist 15.0692
  -> Saved Best Model (Dist: 15.0692)
Epoch 9: Train Loss 41.9413, Val Dist 14.6527
  -> Saved Best Model (Dist: 14.6527)
Epoch 10: Train Loss 41.5899, Val Dist 14.8686
Epoch 11: Train Loss 41.3910, Val Dist 14.5745
  -> Saved Best Model (Dist: 14.5745)
Epoch 12: Train Loss 41.0492, Val Dist 14.4784
  -> Saved Best Model (Dist: 14.4784)
Epoch 13: Train Loss 40.8520, Val Dist 14.3593
  -> Saved Best Model (Dist: 14.3593)
Epoch 14: Train Loss 40.6298, Val Dist 14.4968
Epoch 15: Train Loss 40.5209, Val Dist 14.3134
  -> Saved Best Model (Dist: 14.3134)
Epoch 16: Train Loss 40.3900, Val Dist 14.1692
  -> Saved Best Model (Dist: 14.1692)
Epoch 17: Train Loss 40.2169, Val Dist 14.4431
Epoch 18: Train Loss 40.0339, Val Dist 14.3256
Epoch 19: Train Loss 39.8433, Val Dist 14.8135
Epoch 20: Train Loss 39.8307, Val Dist 14.0747
  -> Saved Best Model (Dist: 14.0747)
Epoch 21: Train Loss 39.7118, Val Dist 14.5240
Epoch 22: Train Loss 39.5234, Val Dist 14.3333
Epoch 23: Train Loss 39.4178, Val Dist 14.3934
Epoch 24: Train Loss 39.3123, Val Dist 14.2482
Epoch 25: Train Loss 38.8165, Val Dist 13.9337
  -> Saved Best Model (Dist: 13.9337)
Epoch 26: Train Loss 38.6087, Val Dist 14.0871
Epoch 27: Train Loss 38.5992, Val Dist 14.2173
Epoch 28: Train Loss 38.5159, Val Dist 14.0705
Epoch 29: Train Loss 38.3973, Val Dist 14.0986
Epoch 30: Train Loss 38.1734, Val Dist 13.9223
  -> Saved Best Model (Dist: 13.9223)
Epoch 31: Train Loss 38.1070, Val Dist 13.8548
  -> Saved Best Model (Dist: 13.8548)
Epoch 32: Train Loss 38.0345, Val Dist 13.8324
  -> Saved Best Model (Dist: 13.8324)
Epoch 33: Train Loss 37.9376, Val Dist 13.8518
Epoch 34: Train Loss 37.9172, Val Dist 13.8677
Epoch 35: Train Loss 37.8557, Val Dist 14.0219
Epoch 36: Train Loss 37.8491, Val Dist 13.8610
Epoch 37: Train Loss 37.6835, Val Dist 13.8163
  -> Saved Best Model (Dist: 13.8163)
Epoch 38: Train Loss 37.6646, Val Dist 13.8197
Epoch 39: Train Loss 37.5543, Val Dist 13.9078
Epoch 40: Train Loss 37.5360, Val Dist 13.8422
Epoch 41: Train Loss 37.5765, Val Dist 13.8509
Epoch 42: Train Loss 37.4899, Val Dist 13.8232
Epoch 43: Train Loss 37.4255, Val Dist 13.7837
  -> Saved Best Model (Dist: 13.7837)
Epoch 44: Train Loss 37.3954, Val Dist 13.8054
Epoch 45: Train Loss 37.5194, Val Dist 13.7556
  -> Saved Best Model (Dist: 13.7556)
Epoch 46: Train Loss 37.3857, Val Dist 13.8171
Epoch 47: Train Loss 37.4799, Val Dist 13.7901
Epoch 48: Train Loss 37.3777, Val Dist 13.7732
Epoch 49: Train Loss 37.3617, Val Dist 13.8055
Epoch 50: Train Loss 37.3447, Val Dist 13.8406
Epoch 51: Train Loss 37.3157, Val Dist 13.8364
Epoch 52: Train Loss 37.3363, Val Dist 13.8226
Epoch 53: Train Loss 37.3369, Val Dist 13.9170
Epoch 54: Train Loss 37.2645, Val Dist 13.8167
Epoch 55: Train Loss 37.3257, Val Dist 13.8032
Epoch 56: Train Loss 37.2727, Val Dist 13.7967
Epoch 57: Train Loss 37.2729, Val Dist 13.7884
Epoch 58: Train Loss 37.3010, Val Dist 13.8128
Epoch 59: Train Loss 37.2657, Val Dist 13.8141
Epoch 60: Train Loss 37.2702, Val Dist 13.7865
Early Stopping
Fold 4 Finished. Best Valid Dist: 13.7556
[Fold 5] Seed fixed to 46

=== Fold 5/10 ===
Pre-rendering 13965 images (Cache Enabled)...

Caching Images: 100%|██████████| 13965/13965 [00:00<00:00, 14397.12it/s]

Pre-rendering 1463 images (Cache Enabled)...

Caching Images: 100%|██████████| 1463/1463 [00:00<00:00, 13250.47it/s]

Epoch 1: Train Loss 61.2533, Val Dist 19.2154
  -> Saved Best Model (Dist: 19.2154)
Epoch 2: Train Loss 48.2910, Val Dist 17.6335
  -> Saved Best Model (Dist: 17.6335)
Epoch 3: Train Loss 46.2060, Val Dist 17.9314
Epoch 4: Train Loss 44.9286, Val Dist 16.1731
  -> Saved Best Model (Dist: 16.1731)
Epoch 5: Train Loss 43.9876, Val Dist 15.7589
  -> Saved Best Model (Dist: 15.7589)
Epoch 6: Train Loss 43.2432, Val Dist 15.1871
  -> Saved Best Model (Dist: 15.1871)
Epoch 7: Train Loss 42.7684, Val Dist 15.4395
Epoch 8: Train Loss 42.1472, Val Dist 15.0431
  -> Saved Best Model (Dist: 15.0431)
Epoch 9: Train Loss 41.9615, Val Dist 14.7852
  -> Saved Best Model (Dist: 14.7852)
Epoch 10: Train Loss 41.6086, Val Dist 14.8244
Epoch 11: Train Loss 41.3413, Val Dist 15.0999
Epoch 12: Train Loss 41.0480, Val Dist 14.4500
  -> Saved Best Model (Dist: 14.4500)
Epoch 13: Train Loss 40.8057, Val Dist 14.6893
Epoch 14: Train Loss 40.5322, Val Dist 14.4405
  -> Saved Best Model (Dist: 14.4405)
Epoch 15: Train Loss 40.4616, Val Dist 14.4477
Epoch 16: Train Loss 40.3442, Val Dist 14.3790
  -> Saved Best Model (Dist: 14.3790)
Epoch 17: Train Loss 40.1067, Val Dist 14.2418
  -> Saved Best Model (Dist: 14.2418)
Epoch 18: Train Loss 40.0007, Val Dist 14.4811
Epoch 19: Train Loss 39.9044, Val Dist 14.1577
  -> Saved Best Model (Dist: 14.1577)
Epoch 20: Train Loss 39.8502, Val Dist 13.9224
  -> Saved Best Model (Dist: 13.9224)
Epoch 21: Train Loss 39.6291, Val Dist 14.1161
Epoch 22: Train Loss 39.6449, Val Dist 14.0338
Epoch 23: Train Loss 39.3809, Val Dist 14.4574
Epoch 24: Train Loss 39.3561, Val Dist 13.8243
  -> Saved Best Model (Dist: 13.8243)
Epoch 25: Train Loss 39.2327, Val Dist 14.3582
Epoch 26: Train Loss 39.1862, Val Dist 13.9246
Epoch 27: Train Loss 39.0434, Val Dist 14.1128
Epoch 28: Train Loss 38.9916, Val Dist 13.8284
Epoch 29: Train Loss 38.4049, Val Dist 13.6568
  -> Saved Best Model (Dist: 13.6568)
Epoch 30: Train Loss 38.2941, Val Dist 13.7184
Epoch 31: Train Loss 38.2379, Val Dist 13.6297
  -> Saved Best Model (Dist: 13.6297)
Epoch 32: Train Loss 38.1252, Val Dist 13.7415
Epoch 33: Train Loss 37.9879, Val Dist 13.5754
  -> Saved Best Model (Dist: 13.5754)
Epoch 34: Train Loss 37.9624, Val Dist 13.6862
Epoch 35: Train Loss 37.9391, Val Dist 13.8015
Epoch 36: Train Loss 37.8296, Val Dist 13.8028
Epoch 37: Train Loss 37.8513, Val Dist 13.7406
Epoch 38: Train Loss 37.5311, Val Dist 13.5611
  -> Saved Best Model (Dist: 13.5611)
Epoch 39: Train Loss 37.4463, Val Dist 13.6875
Epoch 40: Train Loss 37.3888, Val Dist 13.6410
Epoch 41: Train Loss 37.3556, Val Dist 13.6172
Epoch 42: Train Loss 37.2846, Val Dist 13.7919
Epoch 43: Train Loss 37.1899, Val Dist 13.6082
Epoch 44: Train Loss 37.1307, Val Dist 13.6192
Epoch 45: Train Loss 37.0616, Val Dist 13.7587
Epoch 46: Train Loss 37.1004, Val Dist 13.5926
Epoch 47: Train Loss 36.9837, Val Dist 13.6036
Epoch 48: Train Loss 36.9905, Val Dist 13.6344
Epoch 49: Train Loss 36.9298, Val Dist 13.6325
Epoch 50: Train Loss 36.9169, Val Dist 13.6506
Epoch 51: Train Loss 36.9717, Val Dist 13.5980
Epoch 52: Train Loss 36.8804, Val Dist 13.6409
Epoch 53: Train Loss 36.8902, Val Dist 13.6379
Early Stopping
Fold 5 Finished. Best Valid Dist: 13.5611
[Fold 6] Seed fixed to 47

=== Fold 6/10 ===
Pre-rendering 13870 images (Cache Enabled)...

Caching Images: 100%|██████████| 13870/13870 [00:00<00:00, 14288.40it/s]

Pre-rendering 1558 images (Cache Enabled)...

Caching Images: 100%|██████████| 1558/1558 [00:00<00:00, 13647.90it/s]

Epoch 1: Train Loss 61.0720, Val Dist 21.0870
  -> Saved Best Model (Dist: 21.0870)
Epoch 2: Train Loss 48.3845, Val Dist 17.2990
  -> Saved Best Model (Dist: 17.2990)
Epoch 3: Train Loss 46.2909, Val Dist 16.7967
  -> Saved Best Model (Dist: 16.7967)
Epoch 4: Train Loss 45.0827, Val Dist 15.8668
  -> Saved Best Model (Dist: 15.8668)
Epoch 5: Train Loss 43.8775, Val Dist 15.9091
Epoch 6: Train Loss 43.1976, Val Dist 15.4585
  -> Saved Best Model (Dist: 15.4585)
Epoch 7: Train Loss 42.7441, Val Dist 15.4572
  -> Saved Best Model (Dist: 15.4572)
Epoch 8: Train Loss 42.3428, Val Dist 14.8963
  -> Saved Best Model (Dist: 14.8963)
Epoch 9: Train Loss 41.9427, Val Dist 14.5437
  -> Saved Best Model (Dist: 14.5437)
Epoch 10: Train Loss 41.6749, Val Dist 14.7024
Epoch 11: Train Loss 41.3976, Val Dist 15.0481
Epoch 12: Train Loss 41.2424, Val Dist 14.3949
  -> Saved Best Model (Dist: 14.3949)
Epoch 13: Train Loss 41.0491, Val Dist 14.4885
Epoch 14: Train Loss 40.8384, Val Dist 14.3567
  -> Saved Best Model (Dist: 14.3567)
Epoch 15: Train Loss 40.6139, Val Dist 14.5131
Epoch 16: Train Loss 40.3789, Val Dist 14.3256
  -> Saved Best Model (Dist: 14.3256)
Epoch 17: Train Loss 40.3166, Val Dist 14.3383
Epoch 18: Train Loss 40.0157, Val Dist 14.0181
  -> Saved Best Model (Dist: 14.0181)
Epoch 19: Train Loss 40.0443, Val Dist 14.4874
Epoch 20: Train Loss 39.9317, Val Dist 14.0025
  -> Saved Best Model (Dist: 14.0025)
Epoch 21: Train Loss 39.6577, Val Dist 13.9357
  -> Saved Best Model (Dist: 13.9357)
Epoch 22: Train Loss 39.6191, Val Dist 14.0417
Epoch 23: Train Loss 39.4688, Val Dist 14.0361
Epoch 24: Train Loss 39.4883, Val Dist 14.0884
Epoch 25: Train Loss 39.2501, Val Dist 14.2506
Epoch 26: Train Loss 38.8224, Val Dist 13.6314
  -> Saved Best Model (Dist: 13.6314)
Epoch 27: Train Loss 38.6930, Val Dist 13.8857
Epoch 28: Train Loss 38.5390, Val Dist 13.7624
Epoch 29: Train Loss 38.4187, Val Dist 13.6866
Epoch 30: Train Loss 38.5045, Val Dist 13.7046
Epoch 31: Train Loss 38.1374, Val Dist 13.4776
  -> Saved Best Model (Dist: 13.4776)
Epoch 32: Train Loss 38.0603, Val Dist 13.6356
Epoch 33: Train Loss 38.0149, Val Dist 13.5481
Epoch 34: Train Loss 37.9420, Val Dist 13.5211
Epoch 35: Train Loss 37.9146, Val Dist 13.4969
Epoch 36: Train Loss 37.7900, Val Dist 13.4295
  -> Saved Best Model (Dist: 13.4295)
Epoch 37: Train Loss 37.7288, Val Dist 13.4274
  -> Saved Best Model (Dist: 13.4274)
Epoch 38: Train Loss 37.7071, Val Dist 13.3818
  -> Saved Best Model (Dist: 13.3818)
Epoch 39: Train Loss 37.6661, Val Dist 13.4845
Epoch 40: Train Loss 37.6380, Val Dist 13.4051
Epoch 41: Train Loss 37.6127, Val Dist 13.4174
Epoch 42: Train Loss 37.6150, Val Dist 13.5126
Epoch 43: Train Loss 37.4934, Val Dist 13.4087
Epoch 44: Train Loss 37.4380, Val Dist 13.3955
Epoch 45: Train Loss 37.4814, Val Dist 13.4215
Epoch 46: Train Loss 37.4393, Val Dist 13.4093
Epoch 47: Train Loss 37.3986, Val Dist 13.4050
Epoch 48: Train Loss 37.3966, Val Dist 13.3730
  -> Saved Best Model (Dist: 13.3730)
Epoch 49: Train Loss 37.3932, Val Dist 13.3914
Epoch 50: Train Loss 37.3654, Val Dist 13.3702
  -> Saved Best Model (Dist: 13.3702)
Epoch 51: Train Loss 37.3783, Val Dist 13.3706
Epoch 52: Train Loss 37.3198, Val Dist 13.3997
Epoch 53: Train Loss 37.3589, Val Dist 13.3689
  -> Saved Best Model (Dist: 13.3689)
Epoch 54: Train Loss 37.3112, Val Dist 13.3633
  -> Saved Best Model (Dist: 13.3633)
Epoch 55: Train Loss 37.3107, Val Dist 13.4533
Epoch 56: Train Loss 37.3332, Val Dist 13.4089
Epoch 57: Train Loss 37.3971, Val Dist 13.3773
Epoch 58: Train Loss 37.2741, Val Dist 13.4198
Epoch 59: Train Loss 37.2918, Val Dist 13.3599
  -> Saved Best Model (Dist: 13.3599)
Epoch 60: Train Loss 37.3544, Val Dist 13.3596
  -> Saved Best Model (Dist: 13.3596)
Epoch 61: Train Loss 37.2810, Val Dist 13.3884
Epoch 62: Train Loss 37.2889, Val Dist 13.4367
Epoch 63: Train Loss 37.3281, Val Dist 13.3822
Epoch 64: Train Loss 37.2496, Val Dist 13.4254
Epoch 65: Train Loss 37.2608, Val Dist 13.3935
Epoch 66: Train Loss 37.3136, Val Dist 13.4235
Epoch 67: Train Loss 37.2498, Val Dist 13.4240
Epoch 68: Train Loss 37.2581, Val Dist 13.3598
Epoch 69: Train Loss 37.2575, Val Dist 13.3982
Epoch 70: Train Loss 37.2609, Val Dist 13.4101
Epoch 71: Train Loss 37.2611, Val Dist 13.3854
Epoch 72: Train Loss 37.2961, Val Dist 13.3888
Epoch 73: Train Loss 37.2331, Val Dist 13.4735
Epoch 74: Train Loss 37.2575, Val Dist 13.4379
Epoch 75: Train Loss 37.2555, Val Dist 13.3816
Early Stopping
Fold 6 Finished. Best Valid Dist: 13.3596
[Fold 7] Seed fixed to 48

=== Fold 7/10 ===
Pre-rendering 13918 images (Cache Enabled)...

Caching Images: 100%|██████████| 13918/13918 [00:01<00:00, 13666.66it/s]

Pre-rendering 1510 images (Cache Enabled)...

Caching Images: 100%|██████████| 1510/1510 [00:00<00:00, 13723.66it/s]

Epoch 1: Train Loss 60.6550, Val Dist 19.3788
  -> Saved Best Model (Dist: 19.3788)
Epoch 2: Train Loss 48.2352, Val Dist 18.3291
  -> Saved Best Model (Dist: 18.3291)
Epoch 3: Train Loss 46.0178, Val Dist 17.0355
  -> Saved Best Model (Dist: 17.0355)
Epoch 4: Train Loss 45.0290, Val Dist 15.7958
  -> Saved Best Model (Dist: 15.7958)
Epoch 5: Train Loss 44.0184, Val Dist 15.7430
  -> Saved Best Model (Dist: 15.7430)
Epoch 6: Train Loss 43.3395, Val Dist 15.5201
  -> Saved Best Model (Dist: 15.5201)
Epoch 7: Train Loss 42.8362, Val Dist 15.3343
  -> Saved Best Model (Dist: 15.3343)
Epoch 8: Train Loss 42.4027, Val Dist 14.9785
  -> Saved Best Model (Dist: 14.9785)
Epoch 9: Train Loss 42.2089, Val Dist 14.9234
  -> Saved Best Model (Dist: 14.9234)
Epoch 10: Train Loss 41.8931, Val Dist 14.7487
  -> Saved Best Model (Dist: 14.7487)
Epoch 11: Train Loss 41.5039, Val Dist 14.7192
  -> Saved Best Model (Dist: 14.7192)
Epoch 12: Train Loss 41.3118, Val Dist 14.8599
Epoch 13: Train Loss 40.9860, Val Dist 14.5725
  -> Saved Best Model (Dist: 14.5725)
Epoch 14: Train Loss 40.6416, Val Dist 14.7378
Epoch 15: Train Loss 40.6932, Val Dist 14.8557
Epoch 16: Train Loss 40.4386, Val Dist 14.2097
  -> Saved Best Model (Dist: 14.2097)
Epoch 17: Train Loss 40.2163, Val Dist 14.6832
Epoch 18: Train Loss 40.0886, Val Dist 14.2296
Epoch 19: Train Loss 40.0502, Val Dist 14.1936
  -> Saved Best Model (Dist: 14.1936)
Epoch 20: Train Loss 39.8057, Val Dist 14.1009
  -> Saved Best Model (Dist: 14.1009)
Epoch 21: Train Loss 39.6501, Val Dist 13.9379
  -> Saved Best Model (Dist: 13.9379)
Epoch 22: Train Loss 39.5922, Val Dist 14.6359
Epoch 23: Train Loss 39.3840, Val Dist 14.2092
Epoch 24: Train Loss 39.3779, Val Dist 14.0308
Epoch 25: Train Loss 39.2734, Val Dist 14.0303
Epoch 26: Train Loss 38.6619, Val Dist 13.8610
  -> Saved Best Model (Dist: 13.8610)
Epoch 27: Train Loss 38.5768, Val Dist 13.7606
  -> Saved Best Model (Dist: 13.7606)
Epoch 28: Train Loss 38.5367, Val Dist 13.8705
Epoch 29: Train Loss 38.4331, Val Dist 14.0613
Epoch 30: Train Loss 38.3607, Val Dist 13.7356
  -> Saved Best Model (Dist: 13.7356)
Epoch 31: Train Loss 38.3203, Val Dist 13.8941
Epoch 32: Train Loss 38.2444, Val Dist 14.0111
Epoch 33: Train Loss 38.2018, Val Dist 13.7218
  -> Saved Best Model (Dist: 13.7218)
Epoch 34: Train Loss 38.1994, Val Dist 13.7976
Epoch 35: Train Loss 38.1082, Val Dist 13.7029
  -> Saved Best Model (Dist: 13.7029)
Epoch 36: Train Loss 38.0573, Val Dist 13.6913
  -> Saved Best Model (Dist: 13.6913)
Epoch 37: Train Loss 37.9853, Val Dist 13.7432
Epoch 38: Train Loss 37.9867, Val Dist 13.8242
Epoch 39: Train Loss 37.8982, Val Dist 14.3362
Epoch 40: Train Loss 37.8032, Val Dist 13.8715
Epoch 41: Train Loss 37.5452, Val Dist 13.8322
Epoch 42: Train Loss 37.4344, Val Dist 13.7469
Epoch 43: Train Loss 37.3878, Val Dist 13.7866
Epoch 44: Train Loss 37.3929, Val Dist 13.7251
Epoch 45: Train Loss 37.1985, Val Dist 13.7053
Epoch 46: Train Loss 37.1608, Val Dist 13.6823
  -> Saved Best Model (Dist: 13.6823)
Epoch 47: Train Loss 37.1109, Val Dist 13.7419
Epoch 48: Train Loss 37.1564, Val Dist 13.6991
Epoch 49: Train Loss 37.0854, Val Dist 13.6766
  -> Saved Best Model (Dist: 13.6766)
Epoch 50: Train Loss 37.0053, Val Dist 13.7430
Epoch 51: Train Loss 36.9528, Val Dist 13.7700
Epoch 52: Train Loss 36.9530, Val Dist 13.7747
Epoch 53: Train Loss 36.9780, Val Dist 13.8279
Epoch 54: Train Loss 36.9161, Val Dist 13.8214
Epoch 55: Train Loss 36.9378, Val Dist 13.7884
Epoch 56: Train Loss 36.7861, Val Dist 13.8124
Epoch 57: Train Loss 36.8144, Val Dist 13.7585
Epoch 58: Train Loss 36.8396, Val Dist 13.7737
Epoch 59: Train Loss 36.7922, Val Dist 13.7628
Epoch 60: Train Loss 36.7747, Val Dist 13.7327
Epoch 61: Train Loss 36.7961, Val Dist 13.7232
Epoch 62: Train Loss 36.7966, Val Dist 13.7527
Epoch 63: Train Loss 36.7307, Val Dist 13.7516
Epoch 64: Train Loss 36.6815, Val Dist 13.7609
Early Stopping
Fold 7 Finished. Best Valid Dist: 13.6766
[Fold 8] Seed fixed to 49

=== Fold 8/10 ===
Pre-rendering 13910 images (Cache Enabled)...

Caching Images: 100%|██████████| 13910/13910 [00:00<00:00, 14848.62it/s]

Pre-rendering 1518 images (Cache Enabled)...

Caching Images: 100%|██████████| 1518/1518 [00:00<00:00, 13979.02it/s]

Epoch 1: Train Loss 61.7221, Val Dist 19.1007
  -> Saved Best Model (Dist: 19.1007)
Epoch 2: Train Loss 48.3902, Val Dist 18.2109
  -> Saved Best Model (Dist: 18.2109)
Epoch 3: Train Loss 45.9250, Val Dist 16.5755
  -> Saved Best Model (Dist: 16.5755)
Epoch 4: Train Loss 44.8580, Val Dist 15.7295
  -> Saved Best Model (Dist: 15.7295)
Epoch 5: Train Loss 43.9640, Val Dist 15.4102
  -> Saved Best Model (Dist: 15.4102)
Epoch 6: Train Loss 43.3066, Val Dist 15.7598
Epoch 7: Train Loss 42.6927, Val Dist 14.7957
  -> Saved Best Model (Dist: 14.7957)
Epoch 8: Train Loss 42.2732, Val Dist 14.8004
Epoch 9: Train Loss 41.8964, Val Dist 14.3644
  -> Saved Best Model (Dist: 14.3644)
Epoch 10: Train Loss 41.5272, Val Dist 15.1496
Epoch 11: Train Loss 41.3812, Val Dist 14.5125
Epoch 12: Train Loss 41.0866, Val Dist 14.7410
Epoch 13: Train Loss 40.8537, Val Dist 14.0789
  -> Saved Best Model (Dist: 14.0789)
Epoch 14: Train Loss 40.6076, Val Dist 14.0651
  -> Saved Best Model (Dist: 14.0651)
Epoch 15: Train Loss 40.4613, Val Dist 14.1918
Epoch 16: Train Loss 40.2532, Val Dist 14.4312
Epoch 17: Train Loss 40.0528, Val Dist 13.9460
  -> Saved Best Model (Dist: 13.9460)
Epoch 18: Train Loss 39.9373, Val Dist 14.3139
Epoch 19: Train Loss 39.8665, Val Dist 14.3809
Epoch 20: Train Loss 39.6586, Val Dist 13.8484
  -> Saved Best Model (Dist: 13.8484)
Epoch 21: Train Loss 39.5968, Val Dist 14.2066
Epoch 22: Train Loss 39.5028, Val Dist 13.8898
Epoch 23: Train Loss 39.3249, Val Dist 13.9295
Epoch 24: Train Loss 39.2551, Val Dist 13.7538
  -> Saved Best Model (Dist: 13.7538)
Epoch 25: Train Loss 39.1365, Val Dist 14.3277
Epoch 26: Train Loss 39.0497, Val Dist 13.8240
Epoch 27: Train Loss 39.0621, Val Dist 13.7477
  -> Saved Best Model (Dist: 13.7477)
Epoch 28: Train Loss 38.8998, Val Dist 13.8964
Epoch 29: Train Loss 38.7802, Val Dist 13.8081
Epoch 30: Train Loss 38.7988, Val Dist 13.9523
Epoch 31: Train Loss 38.5770, Val Dist 13.9892
Epoch 32: Train Loss 38.1803, Val Dist 13.6444
  -> Saved Best Model (Dist: 13.6444)
Epoch 33: Train Loss 37.9685, Val Dist 13.5759
  -> Saved Best Model (Dist: 13.5759)
Epoch 34: Train Loss 37.9110, Val Dist 13.5788
Epoch 35: Train Loss 37.8659, Val Dist 13.6365
Epoch 36: Train Loss 37.8071, Val Dist 13.9376
Epoch 37: Train Loss 37.7901, Val Dist 13.7167
Epoch 38: Train Loss 37.4733, Val Dist 13.4321
  -> Saved Best Model (Dist: 13.4321)
Epoch 39: Train Loss 37.3808, Val Dist 13.6604
Epoch 40: Train Loss 37.2630, Val Dist 13.5509
Epoch 41: Train Loss 37.3352, Val Dist 13.5745
Epoch 42: Train Loss 37.2517, Val Dist 13.5771
Epoch 43: Train Loss 37.1087, Val Dist 13.5280
Epoch 44: Train Loss 37.1117, Val Dist 13.6427
Epoch 45: Train Loss 36.9596, Val Dist 13.5646
Epoch 46: Train Loss 37.0293, Val Dist 13.6068
Epoch 47: Train Loss 36.9693, Val Dist 13.5552
Epoch 48: Train Loss 36.8787, Val Dist 13.6054
Epoch 49: Train Loss 36.9019, Val Dist 13.5505
Epoch 50: Train Loss 36.8466, Val Dist 13.6062
Epoch 51: Train Loss 36.7708, Val Dist 13.5210
Epoch 52: Train Loss 36.8206, Val Dist 13.5572
Epoch 53: Train Loss 36.8651, Val Dist 13.5174
Early Stopping
Fold 8 Finished. Best Valid Dist: 13.4321
[Fold 9] Seed fixed to 50

=== Fold 9/10 ===
Pre-rendering 13828 images (Cache Enabled)...

Caching Images: 100%|██████████| 13828/13828 [00:00<00:00, 14300.96it/s]

Pre-rendering 1600 images (Cache Enabled)...

Caching Images: 100%|██████████| 1600/1600 [00:00<00:00, 14097.08it/s]

Epoch 1: Train Loss 60.9232, Val Dist 23.3203
  -> Saved Best Model (Dist: 23.3203)
Epoch 2: Train Loss 48.1708, Val Dist 18.5484
  -> Saved Best Model (Dist: 18.5484)
Epoch 3: Train Loss 46.1194, Val Dist 16.8056
  -> Saved Best Model (Dist: 16.8056)
Epoch 4: Train Loss 44.9212, Val Dist 17.2141
Epoch 5: Train Loss 44.0632, Val Dist 16.6737
  -> Saved Best Model (Dist: 16.6737)
Epoch 6: Train Loss 43.2871, Val Dist 15.9448
  -> Saved Best Model (Dist: 15.9448)
Epoch 7: Train Loss 42.6463, Val Dist 16.0539
Epoch 8: Train Loss 42.3506, Val Dist 16.2115
Epoch 9: Train Loss 41.9578, Val Dist 15.2220
  -> Saved Best Model (Dist: 15.2220)
Epoch 10: Train Loss 41.6495, Val Dist 15.0458
  -> Saved Best Model (Dist: 15.0458)
Epoch 11: Train Loss 41.3472, Val Dist 14.9750
  -> Saved Best Model (Dist: 14.9750)
Epoch 12: Train Loss 41.0516, Val Dist 15.1179
Epoch 13: Train Loss 40.7314, Val Dist 15.0812
Epoch 14: Train Loss 40.5792, Val Dist 14.9730
  -> Saved Best Model (Dist: 14.9730)
Epoch 15: Train Loss 40.4145, Val Dist 14.9505
  -> Saved Best Model (Dist: 14.9505)
Epoch 16: Train Loss 40.3004, Val Dist 14.6639
  -> Saved Best Model (Dist: 14.6639)
Epoch 17: Train Loss 40.1121, Val Dist 14.6347
  -> Saved Best Model (Dist: 14.6347)
Epoch 18: Train Loss 39.9559, Val Dist 15.1293
Epoch 19: Train Loss 39.8868, Val Dist 76.6461
Epoch 20: Train Loss 39.7544, Val Dist 14.4429
  -> Saved Best Model (Dist: 14.4429)
Epoch 21: Train Loss 39.5480, Val Dist 14.7193
Epoch 22: Train Loss 39.5038, Val Dist 14.6431
Epoch 23: Train Loss 39.3642, Val Dist 14.7228
Epoch 24: Train Loss 39.2356, Val Dist 14.6607
Epoch 25: Train Loss 38.7128, Val Dist 14.2743
  -> Saved Best Model (Dist: 14.2743)
Epoch 26: Train Loss 38.6071, Val Dist 14.4788
Epoch 27: Train Loss 38.5299, Val Dist 14.3649
Epoch 28: Train Loss 38.4088, Val Dist 14.2282
  -> Saved Best Model (Dist: 14.2282)
Epoch 29: Train Loss 38.4007, Val Dist 14.4085
Epoch 30: Train Loss 38.3088, Val Dist 14.2068
  -> Saved Best Model (Dist: 14.2068)
Epoch 31: Train Loss 38.3496, Val Dist 14.3636
Epoch 32: Train Loss 38.1315, Val Dist 14.3635
Epoch 33: Train Loss 38.1449, Val Dist 14.2222
Epoch 34: Train Loss 38.0700, Val Dist 14.3662
Epoch 35: Train Loss 37.7719, Val Dist 14.2626
Epoch 36: Train Loss 37.7217, Val Dist 14.2236
Epoch 37: Train Loss 37.6560, Val Dist 14.1185
  -> Saved Best Model (Dist: 14.1185)
Epoch 38: Train Loss 37.6336, Val Dist 14.1471
Epoch 39: Train Loss 37.5714, Val Dist 14.1501
Epoch 40: Train Loss 37.5099, Val Dist 14.1724
Epoch 41: Train Loss 37.5273, Val Dist 14.1756
Epoch 42: Train Loss 37.3500, Val Dist 14.0986
  -> Saved Best Model (Dist: 14.0986)
Epoch 43: Train Loss 37.3207, Val Dist 14.0897
  -> Saved Best Model (Dist: 14.0897)
Epoch 44: Train Loss 37.2568, Val Dist 14.1505
Epoch 45: Train Loss 37.2623, Val Dist 14.1288
Epoch 46: Train Loss 37.2100, Val Dist 14.2474
Epoch 47: Train Loss 37.1973, Val Dist 14.1696
Epoch 48: Train Loss 37.1489, Val Dist 14.0737
  -> Saved Best Model (Dist: 14.0737)
Epoch 49: Train Loss 37.0833, Val Dist 14.0882
Epoch 50: Train Loss 37.0046, Val Dist 14.1013
Epoch 51: Train Loss 37.0460, Val Dist 14.1153
Epoch 52: Train Loss 37.0835, Val Dist 14.1215
Epoch 53: Train Loss 37.0196, Val Dist 14.1232
Epoch 54: Train Loss 37.0307, Val Dist 14.1530
Epoch 55: Train Loss 37.0108, Val Dist 14.1579
Epoch 56: Train Loss 37.0140, Val Dist 14.1094
Epoch 57: Train Loss 36.9988, Val Dist 14.1254
Epoch 58: Train Loss 36.9540, Val Dist 14.1049
Epoch 59: Train Loss 36.9403, Val Dist 14.1297
Epoch 60: Train Loss 36.9671, Val Dist 14.1621
Epoch 61: Train Loss 36.9809, Val Dist 14.0691
  -> Saved Best Model (Dist: 14.0691)
Epoch 62: Train Loss 36.9407, Val Dist 14.1281
Epoch 63: Train Loss 36.9591, Val Dist 14.1030
Epoch 64: Train Loss 36.8694, Val Dist 14.1007
Epoch 65: Train Loss 36.9308, Val Dist 14.1043
Epoch 66: Train Loss 36.9354, Val Dist 14.1136
Epoch 67: Train Loss 36.8903, Val Dist 14.0760
Epoch 68: Train Loss 36.9326, Val Dist 14.0788
Epoch 69: Train Loss 36.9578, Val Dist 14.0880
Epoch 70: Train Loss 36.9307, Val Dist 14.0891
Epoch 71: Train Loss 36.9433, Val Dist 14.1333
Epoch 72: Train Loss 36.8971, Val Dist 14.1491
Epoch 73: Train Loss 36.8780, Val Dist 14.0859
Epoch 74: Train Loss 36.8845, Val Dist 14.0771
Epoch 75: Train Loss 36.9678, Val Dist 14.1167
Epoch 76: Train Loss 36.9161, Val Dist 14.0638
  -> Saved Best Model (Dist: 14.0638)
Epoch 77: Train Loss 36.9164, Val Dist 14.1405
Epoch 78: Train Loss 36.8807, Val Dist 14.1331
Epoch 79: Train Loss 36.8879, Val Dist 14.0928
Epoch 80: Train Loss 36.8612, Val Dist 14.0824
Epoch 81: Train Loss 36.9583, Val Dist 14.1059
Epoch 82: Train Loss 36.8954, Val Dist 14.1664
Epoch 83: Train Loss 36.9348, Val Dist 14.1091
Epoch 84: Train Loss 36.9911, Val Dist 14.1357
Epoch 85: Train Loss 36.9025, Val Dist 14.1138
Epoch 86: Train Loss 36.9254, Val Dist 14.1139
Epoch 87: Train Loss 36.9426, Val Dist 14.1551
Epoch 88: Train Loss 36.9526, Val Dist 14.1402
Epoch 89: Train Loss 36.8367, Val Dist 14.1058
Epoch 90: Train Loss 36.9067, Val Dist 14.2121
Epoch 91: Train Loss 36.8585, Val Dist 14.1451
Early Stopping
Fold 9 Finished. Best Valid Dist: 14.0638
[Fold 10] Seed fixed to 51

=== Fold 10/10 ===
Pre-rendering 13858 images (Cache Enabled)...

Caching Images: 100%|██████████| 13858/13858 [00:01<00:00, 13203.17it/s]

Pre-rendering 1570 images (Cache Enabled)...

Caching Images: 100%|██████████| 1570/1570 [00:00<00:00, 13920.01it/s]

Epoch 1: Train Loss 61.4081, Val Dist 19.5568
  -> Saved Best Model (Dist: 19.5568)
Epoch 2: Train Loss 48.3333, Val Dist 17.6906
  -> Saved Best Model (Dist: 17.6906)
Epoch 3: Train Loss 46.1646, Val Dist 16.5409
  -> Saved Best Model (Dist: 16.5409)
Epoch 4: Train Loss 44.7186, Val Dist 16.4845
  -> Saved Best Model (Dist: 16.4845)
Epoch 5: Train Loss 43.9346, Val Dist 15.2780
  -> Saved Best Model (Dist: 15.2780)
Epoch 6: Train Loss 43.2475, Val Dist 15.5605
Epoch 7: Train Loss 42.7104, Val Dist 15.3338
Epoch 8: Train Loss 42.2584, Val Dist 16.0877
Epoch 9: Train Loss 41.9622, Val Dist 14.9958
  -> Saved Best Model (Dist: 14.9958)
Epoch 10: Train Loss 41.5859, Val Dist 14.8706
  -> Saved Best Model (Dist: 14.8706)
Epoch 11: Train Loss 41.4411, Val Dist 14.6179
  -> Saved Best Model (Dist: 14.6179)
Epoch 12: Train Loss 41.1461, Val Dist 15.0519
Epoch 13: Train Loss 40.8704, Val Dist 14.8316
Epoch 14: Train Loss 40.7849, Val Dist 14.5292
  -> Saved Best Model (Dist: 14.5292)
Epoch 15: Train Loss 40.4756, Val Dist 14.1950
  -> Saved Best Model (Dist: 14.1950)
Epoch 16: Train Loss 40.3095, Val Dist 14.2824
Epoch 17: Train Loss 40.1609, Val Dist 14.3526
Epoch 18: Train Loss 40.0416, Val Dist 14.5204
Epoch 19: Train Loss 39.8312, Val Dist 14.6726
Epoch 20: Train Loss 39.3712, Val Dist 14.0929
  -> Saved Best Model (Dist: 14.0929)
Epoch 21: Train Loss 39.1733, Val Dist 14.0009
  -> Saved Best Model (Dist: 14.0009)
Epoch 22: Train Loss 39.0243, Val Dist 13.9011
  -> Saved Best Model (Dist: 13.9011)
Epoch 23: Train Loss 38.9687, Val Dist 13.9554
Epoch 24: Train Loss 38.8556, Val Dist 13.9159
Epoch 25: Train Loss 38.9075, Val Dist 14.1387
Epoch 26: Train Loss 38.7537, Val Dist 14.5183
Epoch 27: Train Loss 38.4304, Val Dist 13.8145
  -> Saved Best Model (Dist: 13.8145)
Epoch 28: Train Loss 38.3556, Val Dist 13.8734
Epoch 29: Train Loss 38.3156, Val Dist 13.9503
Epoch 30: Train Loss 38.3166, Val Dist 13.8267
Epoch 31: Train Loss 38.2510, Val Dist 13.8305
Epoch 32: Train Loss 38.0568, Val Dist 13.7878
  -> Saved Best Model (Dist: 13.7878)
Epoch 33: Train Loss 37.9811, Val Dist 13.7758
  -> Saved Best Model (Dist: 13.7758)
Epoch 34: Train Loss 37.9832, Val Dist 13.8650
Epoch 35: Train Loss 37.9565, Val Dist 13.8686
Epoch 36: Train Loss 37.9057, Val Dist 13.8377
Epoch 37: Train Loss 37.9218, Val Dist 13.8787
Epoch 38: Train Loss 37.8360, Val Dist 13.8709
Epoch 39: Train Loss 37.8404, Val Dist 13.7674
  -> Saved Best Model (Dist: 13.7674)
Epoch 40: Train Loss 37.7701, Val Dist 13.7236
  -> Saved Best Model (Dist: 13.7236)
Epoch 41: Train Loss 37.8251, Val Dist 13.7626
Epoch 42: Train Loss 37.8193, Val Dist 13.7990
Epoch 43: Train Loss 37.7955, Val Dist 13.7838
Epoch 44: Train Loss 37.7477, Val Dist 13.7800
Epoch 45: Train Loss 37.7584, Val Dist 13.7268
Epoch 46: Train Loss 37.7397, Val Dist 13.7386
Epoch 47: Train Loss 37.6402, Val Dist 13.7613
Epoch 48: Train Loss 37.6279, Val Dist 13.7707
Epoch 49: Train Loss 37.5705, Val Dist 13.7337
Epoch 50: Train Loss 37.6283, Val Dist 13.7314
Epoch 51: Train Loss 37.6071, Val Dist 13.7537
Epoch 52: Train Loss 37.6230, Val Dist 13.8443
Epoch 53: Train Loss 37.5851, Val Dist 13.7359
Epoch 54: Train Loss 37.5949, Val Dist 13.7841
Epoch 55: Train Loss 37.6140, Val Dist 13.7624
Early Stopping
Fold 10 Finished. Best Valid Dist: 13.7236
Average Score: 13.6350

## 5. 추론 (Inference)

In [8]:
import os
import joblib
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import cv2
from tqdm import tqdm

os.makedirs("submission_multimodal", exist_ok=True)

# =========================
# Dataset (기존과 동일)
# =========================
class TestMultiModalDataset(Dataset):
    def __init__(self, submission_df, preprocessor, img_size=(68, 105)):
        self.submission_df = submission_df
        self.preprocessor = preprocessor
        self.H, self.W = img_size

    def __len__(self):
        return len(self.submission_df)

    def _generate_image(self, cont_data):
        img_np = np.zeros((2, self.H, self.W), dtype=np.float32)
        if len(cont_data) == 0:
            return torch.tensor(img_np, dtype=torch.float32)

        seq_len = cont_data.shape[0]
        xs = cont_data[:, 0]
        ys = cont_data[:, 1]

        x_idxs = (xs * (self.W - 1)).round().astype(int).clip(0, self.W - 1)
        y_idxs = (ys * (self.H - 1)).round().astype(int).clip(0, self.H - 1)

        for t in range(seq_len):
            px, py = x_idxs[t], y_idxs[t]
            img_np[0, py, px] = 1.0
            decay_val = (t + 1) / seq_len
            if t > 0:
                prev_px, prev_py = x_idxs[t-1], y_idxs[t-1]
                cv2.line(img_np[1], (prev_px, prev_py), (px, py), color=decay_val, thickness=1)
            else:
                img_np[1, py, px] = decay_val

        return torch.tensor(img_np, dtype=torch.float32)

    def __getitem__(self, idx):
        row = self.submission_df.iloc[idx]
        raw_path = row['path']
        path = raw_path[2:] if raw_path.startswith("./") else raw_path

        df = pd.read_csv(path)
        episodes = self.preprocessor.transform(df, is_train=False)

        if len(episodes) == 0:
            input_dim = self.preprocessor.get_input_dim()
            cont = torch.zeros((1, input_dim), dtype=torch.float32)
            cat = torch.zeros((1, 2), dtype=torch.long)
            img = torch.zeros((2, self.H, self.W), dtype=torch.float32)
        else:
            data = episodes[0]
            cont_np = data['cont']
            img = self._generate_image(cont_np)
            cont = torch.tensor(cont_np, dtype=torch.float32)
            cat = torch.tensor(data['cat'], dtype=torch.long)

        return img, cont, cat


def test_mm_collate_fn(batch):
    imgs, conts, cats = zip(*batch)
    imgs_batched = torch.stack(imgs, dim=0)
    lengths = torch.tensor([len(c) for c in conts], dtype=torch.long)
    conts_padded = pad_sequence(conts, batch_first=True)
    cats_padded = pad_sequence(cats, batch_first=True)
    return imgs_batched, conts_padded, cats_padded, lengths


# =========================
# Load Submission Meta
# =========================
submission = pd.read_csv("sample_submission.csv")
test_meta = pd.read_csv("test.csv")
submission = submission.merge(test_meta, on="game_episode", how="left")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =========================
# Fold-wise Inference
# =========================
NUM_FOLDS = 10
all_fold_preds = []

for fold in range(1, NUM_FOLDS + 1):
    print(f"\n=== Inference Fold {fold} ===")

    # 1. Load preprocessor
    preprocessor = joblib.load(f"models/preprocessor_v7_h96_{fold}.pkl")

    # 2. Dataset / Loader
    test_dataset = TestMultiModalDataset(submission, preprocessor)
    test_loader = DataLoader(
        test_dataset,
        batch_size=128,
        shuffle=False,
        collate_fn=test_mm_collate_fn
    )

    # 3. Load model
    input_dim_cont = preprocessor.get_input_dim()
    num_types, num_results = preprocessor.get_num_classes()

    model = MultiModalNetV6(input_dim_cont, num_types, num_results).to(DEVICE)
    model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))
    model.eval()

    fold_preds = []

    # 4. Inference
    with torch.no_grad():
        for imgs, cont, cat, lengths in tqdm(test_loader):
            imgs, cont, cat, lengths = (
                imgs.to(DEVICE),
                cont.to(DEVICE),
                cat.to(DEVICE),
                lengths.to(DEVICE),
            )

            pred, _ = model(imgs, cont, cat, lengths)
            pred_np = pred.cpu().numpy()
            pred_np[:, 0] *= 105.0
            pred_np[:, 1] *= 68.0
            fold_preds.append(pred_np)

    fold_preds = np.vstack(fold_preds)
    all_fold_preds.append(fold_preds)

# =========================
# Ensemble (Mean)
# =========================
final_preds = np.mean(all_fold_preds, axis=0)

submission["end_x"] = final_preds[:, 0].clip(0, 105)
submission["end_y"] = final_preds[:, 1].clip(0, 68)

submission[["game_episode", "end_x", "end_y"]].to_csv(
    "submission_multimodal/multimodal_v7_h96.csv", index=False
)

print("Saved submission_multimodal/multimodal_v7_h96.csv")

C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 1 ===

100%|██████████| 19/19 [01:08<00:00,  3.58s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 2 ===

100%|██████████| 19/19 [00:41<00:00,  2.21s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 3 ===

100%|██████████| 19/19 [00:41<00:00,  2.19s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 4 ===

100%|██████████| 19/19 [00:41<00:00,  2.20s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 5 ===

100%|██████████| 19/19 [00:41<00:00,  2.20s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 6 ===

100%|██████████| 19/19 [00:42<00:00,  2.21s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 7 ===

100%|██████████| 19/19 [00:41<00:00,  2.19s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 8 ===

100%|██████████| 19/19 [00:41<00:00,  2.20s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 9 ===

100%|██████████| 19/19 [00:41<00:00,  2.19s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2167706117.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth"))

=== Inference Fold 10 ===

100%|██████████| 19/19 [00:41<00:00,  2.19s/it]

Saved submission_multimodal/multimodal_v7_h96.csv

In [9]:
import os
import joblib
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import cv2
from tqdm import tqdm

os.makedirs("submission_multimodal", exist_ok=True)

# =========================
# Dataset
# =========================
class TestMultiModalDataset(Dataset):
    def __init__(self, submission_df, preprocessor, img_size=(68, 105)):
        self.submission_df = submission_df
        self.preprocessor = preprocessor
        self.H, self.W = img_size

    def __len__(self):
        return len(self.submission_df)

    def _generate_image(self, cont_data):
        img_np = np.zeros((2, self.H, self.W), dtype=np.float32)
        if len(cont_data) == 0:
            return torch.tensor(img_np, dtype=torch.float32)

        seq_len = cont_data.shape[0]
        xs = cont_data[:, 0]
        ys = cont_data[:, 1]

        x_idxs = (xs * (self.W - 1)).round().astype(int).clip(0, self.W - 1)
        y_idxs = (ys * (self.H - 1)).round().astype(int).clip(0, self.H - 1)

        for t in range(seq_len):
            px, py = x_idxs[t], y_idxs[t]
            img_np[0, py, px] = 1.0
            decay_val = (t + 1) / seq_len
            if t > 0:
                prev_px, prev_py = x_idxs[t-1], y_idxs[t-1]
                cv2.line(img_np[1], (prev_px, prev_py), (px, py), color=decay_val, thickness=1)
            else:
                img_np[1, py, px] = decay_val

        return torch.tensor(img_np, dtype=torch.float32)

    def __getitem__(self, idx):
        row = self.submission_df.iloc[idx]
        raw_path = row['path']
        path = raw_path[2:] if raw_path.startswith("./") else raw_path

        df = pd.read_csv(path)
        episodes = self.preprocessor.transform(df, is_train=False)

        if len(episodes) == 0:
            input_dim = self.preprocessor.get_input_dim()
            cont = torch.zeros((1, input_dim), dtype=torch.float32)
            cat = torch.zeros((1, 2), dtype=torch.long)
            img = torch.zeros((2, self.H, self.W), dtype=torch.float32)
        else:
            data = episodes[0]
            cont_np = data['cont']
            img = self._generate_image(cont_np)
            cont = torch.tensor(cont_np, dtype=torch.float32)
            cat = torch.tensor(data['cat'], dtype=torch.long)

        return img, cont, cat


def test_mm_collate_fn(batch):
    imgs, conts, cats = zip(*batch)
    imgs_batched = torch.stack(imgs, dim=0)
    lengths = torch.tensor([len(c) for c in conts], dtype=torch.long)
    conts_padded = pad_sequence(conts, batch_first=True)
    cats_padded = pad_sequence(cats, batch_first=True)
    return imgs_batched, conts_padded, cats_padded, lengths


# =========================
# Load Submission Meta
# =========================
submission = pd.read_csv("sample_submission.csv")
test_meta = pd.read_csv("test.csv")
submission = submission.merge(test_meta, on="game_episode", how="left")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =========================
# 10-Fold Inference with TTA
# =========================
NUM_FOLDS = 10
all_fold_preds = []

for fold in range(1, NUM_FOLDS + 1):
    print(f"\n=== Inference Fold {fold} with TTA ===")

    # 1. Load preprocessor
    preprocessor = joblib.load(f"models/preprocessor_v7_h96_{fold}.pkl")

    # 2. Dataset / Loader
    test_dataset = TestMultiModalDataset(submission, preprocessor)
    test_loader = DataLoader(
        test_dataset,
        batch_size=128,
        shuffle=False,
        collate_fn=test_mm_collate_fn
    )

    # 3. Load model
    input_dim_cont = preprocessor.get_input_dim()
    num_types, num_results = preprocessor.get_num_classes()

    model = MultiModalNetV6(input_dim_cont, num_types, num_results).to(DEVICE)
    model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))
    model.eval()

    fold_preds = []

    # 4. Inference with TTA
    with torch.no_grad():
        for imgs, cont, cat, lengths in tqdm(test_loader, desc=f"Fold {fold}"):
            imgs, cont, cat, lengths = (
                imgs.to(DEVICE),
                cont.to(DEVICE),
                cat.to(DEVICE),
                lengths.to(DEVICE),
            )

            # -------------------------
            # (1) 원본 예측
            # -------------------------
            pred1, _ = model(imgs, cont, cat, lengths)

            # -------------------------
            # (2) Y-Flip TTA 예측
            # -------------------------
            imgs_f = torch.flip(imgs, dims=[2])  # Y-axis flip

            cont_f = cont.clone()
            # Y 관련 feature flip
            cont_f[:, :, 1] = 1.0 - cont_f[:, :, 1]  # start_y
            cont_f[:, :, 3] = 1.0 - cont_f[:, :, 3]  # end_y_prev
            cont_f[:, :, 5] = -cont_f[:, :, 5]       # dy_prev

            pred2, _ = model(imgs_f, cont_f, cat, lengths)

            # 예측값 다시 flip
            pred2[:, 1] = 1.0 - pred2[:, 1]

            # -------------------------
            # (3) 평균
            # -------------------------
            pred = 0.5 * (pred1 + pred2)

            pred_np = pred.cpu().numpy()
            pred_np[:, 0] *= 105.0
            pred_np[:, 1] *= 68.0
            fold_preds.append(pred_np)

    fold_preds = np.vstack(fold_preds)
    all_fold_preds.append(fold_preds)

# =========================
# Ensemble (Mean)
# =========================
final_preds = np.mean(all_fold_preds, axis=0)

submission["end_x"] = final_preds[:, 0].clip(0, 105)
submission["end_y"] = final_preds[:, 1].clip(0, 68)

submission[["game_episode", "end_x", "end_y"]].to_csv(
    "submission_multimodal/multimodal_v7_h96_tta.csv", index=False
)

print("\n✅ Saved: submission_multimodal/multimodal_v7_h96_tta.csv")

C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 1 with TTA ===

Fold 1: 100%|██████████| 19/19 [00:42<00:00,  2.22s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 2 with TTA ===

Fold 2: 100%|██████████| 19/19 [00:43<00:00,  2.31s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 3 with TTA ===

Fold 3: 100%|██████████| 19/19 [00:43<00:00,  2.28s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 4 with TTA ===

Fold 4: 100%|██████████| 19/19 [00:43<00:00,  2.31s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 5 with TTA ===

Fold 5: 100%|██████████| 19/19 [00:43<00:00,  2.29s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 6 with TTA ===

Fold 6: 100%|██████████| 19/19 [00:43<00:00,  2.27s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 7 with TTA ===

Fold 7: 100%|██████████| 19/19 [00:43<00:00,  2.28s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 8 with TTA ===

Fold 8: 100%|██████████| 19/19 [00:44<00:00,  2.34s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 9 with TTA ===

Fold 9: 100%|██████████| 19/19 [00:43<00:00,  2.30s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\2450104897.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 10 with TTA ===

Fold 10: 100%|██████████| 19/19 [00:43<00:00,  2.30s/it]

✅ Saved: submission_multimodal/multimodal_v7_h96_tta.csv

In [ ]:
import os
import joblib
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import cv2
from tqdm import tqdm

os.makedirs("submission_multimodal", exist_ok=True)

# =========================
# Dataset
# =========================
class TestMultiModalDataset(Dataset):
    def __init__(self, submission_df, preprocessor, img_size=(68, 105)):
        self.submission_df = submission_df
        self.preprocessor = preprocessor
        self.H, self.W = img_size

    def __len__(self):
        return len(self.submission_df)

    def _generate_image(self, cont_data):
        img_np = np.zeros((2, self.H, self.W), dtype=np.float32)
        if len(cont_data) == 0:
            return torch.tensor(img_np, dtype=torch.float32)

        seq_len = cont_data.shape[0]
        xs = cont_data[:, 0]
        ys = cont_data[:, 1]

        x_idxs = (xs * (self.W - 1)).round().astype(int).clip(0, self.W - 1)
        y_idxs = (ys * (self.H - 1)).round().astype(int).clip(0, self.H - 1)

        for t in range(seq_len):
            px, py = x_idxs[t], y_idxs[t]
            img_np[0, py, px] = 1.0
            decay_val = (t + 1) / seq_len
            if t > 0:
                prev_px, prev_py = x_idxs[t-1], y_idxs[t-1]
                cv2.line(img_np[1], (prev_px, prev_py), (px, py), color=decay_val, thickness=1)
            else:
                img_np[1, py, px] = decay_val

        return torch.tensor(img_np, dtype=torch.float32)

    def __getitem__(self, idx):
        row = self.submission_df.iloc[idx]
        raw_path = row['path']
        path = raw_path[2:] if raw_path.startswith("./") else raw_path

        df = pd.read_csv(path)
        episodes = self.preprocessor.transform(df, is_train=False)

        if len(episodes) == 0:
            input_dim = self.preprocessor.get_input_dim()
            cont = torch.zeros((1, input_dim), dtype=torch.float32)
            cat = torch.zeros((1, 2), dtype=torch.long)
            img = torch.zeros((2, self.H, self.W), dtype=torch.float32)
        else:
            data = episodes[0]
            cont_np = data['cont']
            img = self._generate_image(cont_np)
            cont = torch.tensor(cont_np, dtype=torch.float32)
            cat = torch.tensor(data['cat'], dtype=torch.long)

        return img, cont, cat


def test_mm_collate_fn(batch):
    imgs, conts, cats = zip(*batch)
    imgs_batched = torch.stack(imgs, dim=0)
    lengths = torch.tensor([len(c) for c in conts], dtype=torch.long)
    conts_padded = pad_sequence(conts, batch_first=True)
    cats_padded = pad_sequence(cats, batch_first=True)
    return imgs_batched, conts_padded, cats_padded, lengths


# =========================
# Load Submission Meta
# =========================
submission = pd.read_csv("sample_submission.csv")
test_meta = pd.read_csv("test.csv")
submission = submission.merge(test_meta, on="game_episode", how="left")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =========================
# 10-Fold Inference with CORRECTED TTA
# =========================
NUM_FOLDS = 10
all_fold_preds = []

for fold in range(1, NUM_FOLDS + 1):
    print(f"\n=== Inference Fold {fold} with Corrected TTA ===")

    # 1. Load preprocessor
    preprocessor = joblib.load(f"models/preprocessor_v7_h96_{fold}.pkl")

    # 2. Dataset / Loader
    test_dataset = TestMultiModalDataset(submission, preprocessor)
    test_loader = DataLoader(
        test_dataset,
        batch_size=128,
        shuffle=False,
        collate_fn=test_mm_collate_fn
    )

    # 3. Load model
    input_dim_cont = preprocessor.get_input_dim()
    num_types, num_results = preprocessor.get_num_classes()

    model = MultiModalNetV6(input_dim_cont, num_types, num_results).to(DEVICE)
    model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))
    model.eval()

    fold_preds = []

    # 4. Inference with CORRECTED TTA
    with torch.no_grad():
        for imgs, cont, cat, lengths in tqdm(test_loader, desc=f"Fold {fold}"):
            imgs, cont, cat, lengths = (
                imgs.to(DEVICE),
                cont.to(DEVICE),
                cat.to(DEVICE),
                lengths.to(DEVICE),
            )

            # -------------------------
            # (1) 원본 예측
            # -------------------------
            pred1, _ = model(imgs, cont, cat, lengths)

            # -------------------------
            # (2) Y-Flip TTA 예측 (CORRECTED!)
            # -------------------------
            imgs_f = torch.flip(imgs, dims=[2])  # Y-axis flip

            # ✅ CORRECTED: Raw → Flip → Scale
            scaler = preprocessor.scaler
            mean = torch.tensor(scaler.mean_, device=cont.device, dtype=cont.dtype)
            std = torch.tensor(scaler.scale_, device=cont.device, dtype=cont.dtype)

            # Step 1: z-score → raw(norm)
            cont_raw = cont * std + mean

            # Step 2: Y-Flip in raw space
            cont_raw[:, :, 1] = 1.0 - cont_raw[:, :, 1]  # start_y_norm
            cont_raw[:, :, 3] = 1.0 - cont_raw[:, :, 3]  # end_y_prev_norm
            cont_raw[:, :, 5] = -cont_raw[:, :, 5]       # dy_prev_norm

            # Step 3: raw → z-score
            cont_f = (cont_raw - mean) / std

            pred2, _ = model(imgs_f, cont_f, cat, lengths)

            # 예측값 다시 flip
            pred2[:, 1] = 1.0 - pred2[:, 1]

            # -------------------------
            # (3) 평균
            # -------------------------
            pred = 0.5 * (pred1 + pred2)

            pred_np = pred.cpu().numpy()
            pred_np[:, 0] *= 105.0
            pred_np[:, 1] *= 68.0
            fold_preds.append(pred_np)

    fold_preds = np.vstack(fold_preds)
    all_fold_preds.append(fold_preds)

# =========================
# Ensemble (Mean)
# =========================
final_preds = np.mean(all_fold_preds, axis=0)

submission["end_x"] = final_preds[:, 0].clip(0, 105)
submission["end_y"] = final_preds[:, 1].clip(0, 68)

submission[["game_episode", "end_x", "end_y"]].to_csv(
    "submission_multimodal/multimodal_v7_h96_tta_corrected.csv", index=False
)

print("\n✅ Saved: submission_multimodal/multimodal_v7_h96_tta_corrected.csv")
print("📊 TTA Fix Applied: Raw → Flip → Scale")

C:\Users\semic\AppData\Local\Temp\ipykernel_83332\246526493.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 1 with Corrected TTA ===

Fold 1: 100%|██████████| 19/19 [01:13<00:00,  3.89s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\246526493.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 2 with Corrected TTA ===

Fold 2: 100%|██████████| 19/19 [00:45<00:00,  2.39s/it]
C:\Users\semic\AppData\Local\Temp\ipykernel_83332\246526493.py:116: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f"models/multimodal_v7_h96_{fold}.pth", map_location=DEVICE))

=== Inference Fold 3 with Corrected TTA ===

Fold 3:   5%|▌         | 1/19 [00:02<00:42,  2.36s/it]

In [10]:
result = pd.read_csv("submission_multimodal.csv")
result.head()

  game_episode      end_x      end_y
0     153363_1  63.607921  11.172691
1     153363_2  24.612310  56.282756
2     153363_6  31.860115  64.409105
3     153363_7  52.938785   5.637901
4     153363_8  82.286735   7.873227

In [11]:
result_100 = pd.read_csv("submission_multimodal/submission_multimodal_epochs100.csv")
result_100.head()

  game_episode      end_x      end_y
0     153363_1  62.625419   8.007021
1     153363_2  21.414417  53.239441
2     153363_6  32.698217  64.080480
3     153363_7  57.145877   3.871556
4     153363_8  82.507950   8.292343

In [12]:
result_100_32 = pd.read_csv("submission_multimodal/submission_multimodal_epochs100_32.csv")
result_100_32.head()

  game_episode      end_x      end_y
0     153363_1  66.829318   8.926390
1     153363_2  25.648449  54.653327
2     153363_6  33.047745  64.115743
3     153363_7  58.226136   4.716273
4     153363_8  82.273184   7.475297

In [13]:
result_100_32_v6 = pd.read_csv("submission_multimodal/submission_multimodal_epochs100_32_v6.csv")
result_100_32_v6.head()

  game_episode      end_x      end_y
0     153363_1  64.597333   8.189129
1     153363_2  26.559090  50.912119
2     153363_6  31.622801  61.919090
3     153363_7  52.369850   3.774227
4     153363_8  84.277331   8.135580

In [14]:
result_v7 = pd.read_csv("submission_multimodal/multimodal_v7.csv")
result_v7.head()

  game_episode      end_x      end_y
0     153363_1  64.898580   9.964928
1     153363_2  26.757336  52.302315
2     153363_6  29.749920  63.453846
3     153363_7  56.788654   5.046815
4     153363_8  82.100350   8.899534

In [15]:
result_v7_fold = pd.read_csv("submission_multimodal/multimodal_v7_fold10.csv")
result_v7_fold.head()

  game_episode      end_x      end_y
0     153363_1  62.648010   9.487803
1     153363_2  26.349102  50.654480
2     153363_6  30.616455  63.448414
3     153363_7  53.435190   4.815488
4     153363_8  81.505226   8.122751

In [16]:
result_v7_fold_tta = pd.read_csv("submission_multimodal/multimodal_v7_fold10_tta.csv")
result_v7_fold_tta.head()

  game_episode      end_x      end_y
0     153363_1  62.602947  10.580890
1     153363_2  26.541010  49.843010
2     153363_6  30.677760  63.525776
3     153363_7  54.284637   4.835038
4     153363_8  81.609910   8.414079

In [17]:
result_v7_foldseed = pd.read_csv("submission_multimodal/multimodal_v7_foldseed.csv")
result_v7_foldseed.head()

  game_episode      end_x      end_y
0     153363_1  63.421947  10.237642
1     153363_2  26.759787  49.413464
2     153363_6  29.883270  62.548830
3     153363_7  55.195984   5.207705
4     153363_8  82.545845   8.009755

In [18]:
result_v7_foldseed_tta = pd.read_csv("submission_multimodal/multimodal_v7_foldseed_tta.csv")
result_v7_foldseed_tta.head()

  game_episode      end_x      end_y
0     153363_1  63.095875  11.823668
1     153363_2  26.836575  49.308430
2     153363_6  30.428274  63.259560
3     153363_7  56.232758   5.196191
4     153363_8  82.745255   8.249907

In [19]:
result_v7_h96= pd.read_csv("submission_multimodal/multimodal_v7_h96.csv")
result_v7_h96.head()

  game_episode      end_x      end_y
0     153363_1  64.615486  10.832696
1     153363_2  25.001268  49.346035
2     153363_6  27.185059  63.219980
3     153363_7  55.024788   5.205964
4     153363_8  81.562614   8.390555

In [20]:
result_v7_foldseed_h96_tta = pd.read_csv("submission_multimodal/multimodal_v7_h96_tta.csv")
result_v7_foldseed_h96_tta.head()

  game_episode      end_x      end_y
0     153363_1  64.885360  11.527712
1     153363_2  25.639957  48.075230
2     153363_6  28.853336  63.301735
3     153363_7  53.528250   5.063232
4     153363_8  81.424120   8.359509

In [ ]:
result_v7_foldseed_h96_tta_corrected = pd.read_csv("submission_multimodal/multimodal_v7_h96_tta_corrected.csv")
result_v7_foldseed_h96_tta_corrected.head()

  game_episode      end_x      end_y
0     153363_1  64.885360  11.527712
1     153363_2  25.639957  48.075230
2     153363_6  28.853336  63.301735
3     153363_7  53.528250   5.063232
4     153363_8  81.424120   8.359509